### ISSUE TITLE
Allow param definitions in route_param

### ISSUE THREAD

**Issue by ctembreull** [ruby-grape/grape#1009]
It seems like it would make sense to at least allow the 'type' modifier in a route param call. Instead of doing:

    route_param :foo do
        params do
            requires :foo, type: String
        end
        #...
    end

it would make a lot more sense to simply say:

    route_param :foo, type: String do
        #...
    end

**Comment by dblock** [comment]
:+1:

**Comment by kuraga** [comment]
No ambigiouty or conflicts?

**Comment by ctembreull** [comment]
I wouldn't believe so, but I haven't started looking at what it would take to do this, either. It should function the same as `required :param_name, type: Type, {...}` in other params definitions, but it would have the extra power to declare a new route section as it does now. `route_param` already requires that parameter to be in place to access any of its nested routes.

**Comment by namusyaka** [comment]
@dblock This issue can be closed by #1255

**Comment by dblock** [comment]
:+1:
