### ISSUE TITLE
Rails 4.2.1 Header 404 error 

### ISSUE THREAD

**Issue by oncity** [ruby-grape/grape#1011]
Rails 4.2.1 + grape 
====================
HTTP/1.1 404 Not Found
Server: openresty
Date: Tue, 05 May 2015 16:15:27 GMT
Content-Type: text/html; charset=utf-8
Content-Length: 183884
Connection: keep-alive
Keep-Alive: timeout=5
Vary: Accept-Encoding
Status: 404 Not Found
X-Request-Id: 883ad0d1-9add-4a0d-bf4e-d45b580a894d
X-Runtime: 0.514069

====================
Rails 4.2  is OK

**Comment by dblock** [comment]
What's the question?

**Comment by oncity** [comment]
grape run at Rails 4.2.1 , always responder 404 status 

but same app run at  Rails 4.2 is ok.

**Comment by dblock** [comment]
I upgraded https://github.com/dblock/grape-on-rails to Rails 4.2.1 and everything works as before. Show us the problem please.

**Comment by dblock** [comment]
Are you trying to demonstrate https://github.com/intridea/grape/issues/1014?

**Comment by roxer** [comment]
After upgrading to Rails 4.2.1 from 4.2.0
I had to explicitly add format in root api class regardless of format in mounted classes
https://github.com/dblock/grape-on-rails/blob/master/app/api/api.rb

**Comment by roxer** [comment]
After upgrading to Rails 4.2.1 from 4.2.0
I had to explicitly add format in root api class regardless of format in mounted classes
https://github.com/dblock/grape-on-rails/blob/master/app/api/api.rb

**Comment by dblock** [comment]
Bump @oncity

**Comment by dblock** [comment]
Closing, please reopen if you can describe the issue.
