### ISSUE TITLE
How grape recognizes a path?

### ISSUE THREAD

**Issue by vasilakisfil** [ruby-grape/grape#1072]
In rails there is Rails.application.routes.recognize_path: http://www.rubydoc.info/docs/rails/ActionDispatch/Routing/RouteSet#recognize_path-instance_method

Is there anything similar for Grape?

**Comment by dblock** [comment]
Grape uses Rack::Mount, which is now yanked from Github. I actually would like to use this opportunity to figure out what the recommended replacement is and maybe find out a bit about the history of why it was yanked? /cc: @joshpeek

**Comment by vasilakisfil** [comment]
anyone?

**Comment by dblock** [comment]
@vasilakisfil The "how" part is rack-mount, and you can look at the source via `bundle show rack-mount` in any project that has a Grape dependency. But the question of what we should do with it remains, I now [asked rack-devel](https://groups.google.com/forum/?fromgroups#!topic/rack-devel/nNjuNIEZJis).

**Comment by vasilakisfil** [comment]
I hate it when such vital gems don't have documentation......... and why on earth they removed it? it's free to have it somewhere on github...

After 2 hours looking on the rack-mount code, I couldn't figure out what object accepts recognize method of RouteSet class...

Any help is really appreciated.. I have a route string ('/api/v1/foobars') and some request options (like {method: :get} etc) and I need somehow to get the path from grape api.....

**Comment by dm1try** [comment]
>After 2 hours looking on the rack-mount code, I couldn't figure out what object accepts recognize method of RouteSet class...

seems it's just an instance of Rack::Request(or Grape)

```ruby
@request_class = options.delete(:request_class) || Rack::Request
...
req = @request_class.new(env)
recognize(req) do |route, matches, params|
...
end
```

so you can prepare `env` using Rack::MockRequest
then build an instance of Rack::Request
then call `recognize`
```ruby
mocked_env = Rack::MockRequest.env_for('/api/v1/foobars', {:method => 'GET', :params => { foo: 'bar' }})
request = Rack::Request.new(mocked_env)
routes = route_set.recognize(request)
```
or smth similar

>why it was yanked?
really interesting..

**Comment by vasilakisfil** [comment]
Thanks!

**Comment by dblock** [comment]
Nice work @dm1try. Should Grape provide a helper? Or maybe an extension or a separate gem?

**Comment by dm1try** [comment]
@dblock I honestly don't have a good use-case of using this feature in my flow(debugging? seems we need  to make `grape-console` first :) )
Anyway, it will be great  for a start if someone can implement a helper/extension.

**Comment by voxik** [comment]
As far as I remember, rack-mount used to be router used by Rails up to 3.1 [1], then the Journey was developed as a replacement and later subsumed into Rails, where it still lives [2].

[1] https://github.com/rails/rails/commit/5f0b37c486dcc735b5817852932e761f5ff60152
[2] https://github.com/rails/rails/commits/master/actionpack/lib/action_dispatch/journey

**Comment by voxik** [comment]
Just FTR, there is attempt to package Grape for Fedora [1], since it is in GitLab's dependency chain and it'd be great if the rack-mount dependency could be avoided. As much as I hate to say that, it might be even reasonable to vendor the rack-mount, if the functionality fit Grape's needs.


[1] https://bugzilla.redhat.com/show_bug.cgi?id=1268771

**Comment by dblock** [comment]
I would take a PR that replaces rack-mount with journey, vendors it, or whatever is needed.

**Comment by dblock** [comment]
We should try https://github.com/hanami/router.

**Comment by dblock** [comment]
We replaced the router in https://github.com/ruby-grape/grape/pull/1276. Maybe we can do something about this now? /cc: @namusyaka

**Comment by namusyaka** [comment]
Yeah, I guess we can do provide the helper, I'm going to try to implement it.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1339.
