### ISSUE TITLE
unable to reach endpoint with same URL, different method

### ISSUE THREAD

**Issue by jpaas** [ruby-grape/grape#1076]
This may be related to #968, but it has nothing to do with versions. I have an endpoint that looks like this...

```ruby
resource :users do
  resource :password do
    post do
    ....
    end

    put do
    ....
    end
  end
end
```

I can call the POST ok, but calls to the PUT always return a 401. If I rename the put to `put ':something' do` it works fine.

**Comment by dblock** [comment]
This has to be something unrelated to Grape proper, try to put a repro together?

**Comment by dblock** [comment]
Closing, there's no actionable info here.
