### ISSUE TITLE
`route :any` doesn't catch everything in a namespace

### ISSUE THREAD

**Issue by wagenet** [ruby-grape/grape#1081]
```rb
    namespace :super do
      get :ping do
        pong = params[:pong] || 'pong'
        { ping: "#{pong.upcase}!!!" }
      end

      route :any, '*path' do
        { path: params[:path] }
      end
    end
```

`GET /super/ping` works but `GET /super` errors. However, I am able to do `POST /super/ping` and have it get picked up by the `route :any`. I would expect that nothing to `/super` would error.

**Comment by dblock** [comment]
Yes, this seems wrong. Try writing a test that reproduces this, and lets fix it.

**Comment by wagenet** [comment]
See: https://github.com/wagenet/grape-on-rails/commit/11f1e5828a90202693000239dab460fcac5a334c

`curl http://localhost:3000/api/super` - Fails, expected `{"path":"fail"}`.
`curl http://localhost:3000/api/super/ping` - Returns `{"ping":"PONG!!!"}` as expected.
`curl http://localhost:3000/api/super/ping/fail` - Returns `{"path":"ping/fail"}`. I think this is expected.
`curl http://localhost:3000/api/super/ping -X POST -d "pong=bar"` - Returns `{"path":"ping"}`. Expected since only `get` is defined.

**Comment by dblock** [comment]
Can you try to turn this into a Grape test. The demo is definitely good, but if we want to fix it we need a proper spec here.

**Comment by wagenet** [comment]
Understood, I'll see what I can do. I've actually never written a real Grape app yet :) Just been working on writing a plugin for Skylight (https://skylight.io).

**Comment by wagenet** [comment]
See #1089.
