### ISSUE TITLE
Hash#except not defined

### ISSUE THREAD

**Issue by wagenet** [ruby-grape/grape#1087]
If you try to use Grape without Rails, you can run into an issue where `Hash#except` is not defined.

https://github.com/ruby-grape/grape/blob/0dfc1cc1cc2f43d49e09d14f737397f087668577/lib/grape/endpoint.rb#L161

`Hash#except` is not part of the standard API and is provided by Rails.

**Comment by dblock** [comment]
We use Grape plenty without Rails. Is this coming from ActiveSupport (which is required)? Do you have a repro case?

**Comment by wagenet** [comment]
Hmm, I ran into it in tests embedded in Skylight. Let me investigate more and get back to you.

**Comment by wagenet** [comment]
Ah, the issue is if you're using ActiveSupport 3. Currently, grape does rely on `active_support/core_ext/hash/except` but it never explicitly requires it. However, you do require `active_support/core_ext/object/conversions`. In ActiveSupport 4, this implicitly requires `except`, but in version 3 it does not.

**Comment by dblock** [comment]
Should we explicitly require it? I would take a PR.

**Comment by wagenet** [comment]
@dblock either that or lock down the ActiveSupport version to 4+. However, it seems nice to support older versions as long as there aren't any other known issues.

**Comment by dblock** [comment]
I agree. Grape tests with Rails 3, via https://github.com/ruby-grape/grape/blob/master/gemfiles/rails_3.gemfile, maybe you can ensure that locks with activesupport 3 and fails without a code change?

**Comment by wagenet** [comment]
@dblock well it's probably ok with Rails 3 since Rails itself requires the file in question. The issue happens if you are running without Rails but do have ActiveSupport 3.

**Comment by wagenet** [comment]
Closing in favor of the PR at #1088.
