### ISSUE TITLE
Auto-publish Ruby/Yard docs

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1090]
We need a process by which every release publishes the Yard docs or links them from the README.

**Comment by ramkumar-kr** [comment]
Hi @dblock ,

Doesn't rubygems already do the publishing part?
Link - [http://www.rubydoc.info/gems/grape/1.0.1](http://www.rubydoc.info/gems/grape/1.0.1)

**Comment by dblock** [comment]
Yeah this issue is very old. Care to PR any changes to README and we can close this @ramkumar-kr?

**Comment by ramkumar-kr** [comment]
https://github.com/ruby-grape/grape/pull/1688
