### ISSUE TITLE
Attach metadata to an endpoint

### ISSUE THREAD

**Issue by harmoney-danc** [ruby-grape/grape#1103]
I have an after: callback set up on a namespace (to be executed for almost all APIs inside it). Now, for some of the APIs in the namespace I need to skip this after: callback. What are my best options?

I would like to be able to add some metadata to the particular APIs and test it in the callback:
Ex.
```ruby
  namespace :investor do
    after do
      unless(self.metadata[:skip_cache_buster])
        # disable caching
      end
    end

    get '/odd_numbers', skip_cache_buster: true do
      set_ttl(TTL)
      # do something useful that can be cached
    end

    get '/current_time' do
      # no cache please for this one
    end
  end
```

**Comment by dblock** [comment]
Attaching metadata to an endpoint is fairly easy. Here's one that adds a sort keyword, so you can have `sort :whatever` above the endpoint (annotation style DSL is nicer than the option passed as an additional parameter to the endpoint, this is how we do `params`).

```ruby
module Grape
  module Extensions
    module SortExtension
      def sort(value)
        route_setting :sort, sort: value
        value
      end

      Grape::API.extend self
    end
  end
end
```

I believe this is directly accessible via `ENV['api.endpoint'].route ...` in an `after` block. Can you confirm?

**Comment by dblock** [comment]
Generally these things are better brought up in the mailing list. I am going to close this, start a thread there or continue it here if you can't make it work.
