### ISSUE TITLE
params = declared(params) throws undefined method [] for nil:NilClass

### ISSUE THREAD

**Issue by 23tux** [ruby-grape/grape#1106]
Hi,

when I try to overwrite my params like this

```ruby
params = declared(params)
```

an error is thrown:

```
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/user1/.gems/gems/grape-0.13.0/lib/grape/dsl/inside_route.rb:48:in `block (2 levels) in declared'
```

When I don't overwrite `params` or when I duplicate the params hash everything works fine:

```ruby
foobar = declared(params) # this works

dup_params = params.dup
params = delcared(dup_params) # this also works

# but this doesn't work
params = declared(params.dup) # here the same error as above is thrown
```

Any idea on how to fix this?

**Comment by dblock** [comment]
Interesting. We do `params.inject ...` and then a bunch of other stuff in https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/inside_route.rb#L48. Clearly `params` has been nil-ed in this context, you would have to debug why, I don't see it. Reference counting?!

**Comment by rnubel** [comment]
This is actually just standard Ruby behavior when you're defining a local variable with the same name as a method; as soon as Ruby sees you're assigning that local variable, it changes the reference of that identifier to the variable, hiding the fact that the method exists (this is called "shadowing"). A simple, non-Grape related example:

```ruby
irb(main):001:0> def foo
irb(main):002:1>   [ 1 ]
irb(main):003:1> end
=> :foo
irb(main):004:0> foo = foo << 1
NoMethodError: undefined method `<<' for nil:NilClass
	from (irb):4
```

To fix it, use a different variable name, or one of your workarounds.

**Comment by dblock** [comment]
![](http://i.imgur.com/iopCOZ4.gif)

I am going to close this, thanks @rnubel for the explanation I had no idea about this.
