### ISSUE TITLE
README.md: block for "HTTP Status Code" needs to be moved

### ISSUE THREAD

**Issue by jf** [ruby-grape/grape#1117]
Within the TOC, it's between "Cookies", and "Redirecting"; but right now it's right smack confusingly in the middle of the section about "Versioning"... See  https://github.com/ruby-grape/grape#http-status-code

**Comment by dblock** [comment]
Please PR! Thx.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1118.
