### ISSUE TITLE
require grape slow down app

### ISSUE THREAD

**Issue by yokas** [ruby-grape/grape#1121]
I've written a 'Hello World' app using Goliath, and I decided to mount Grape on top of it:

```
#!/usr/bin/env ruby

require 'rubygems'
require 'bundler/setup'
Bundler.setup :default
require 'goliath'
require 'grape'   # <-- Comment out this line will hugely increase performance, but why?

class Server < Goliath::API
  def response(env)
    [200, {}, 'Hello, world!']
  end
end
```
I benchmarked it:

`ab -n 1000 -c 100 http://localhost:9000/`

It shows that about 250 requests can be handled per second. But when I comment out the line require 'grape', this value suddenly increased to about 700. Can anybody answer why the simple require can bring such a huge difference?

P.S. I use MRI 2.2.2

**Comment by marshall-lee** [comment]
Interesting...

**Comment by marshall-lee** [comment]
@yokas 

It's all because of dependency bloat. Look at #1122.
But I also think that in a real I/O bound application you will not depend on CPU so much.

**Comment by dblock** [comment]
I've merged #1122, @yokas, can you please rerun and update your benchmark against HEAD. Lets see how much better it got? Thanks.

**Comment by yokas** [comment]
@marshall-lee @dblock Thanks, I will do a benchmark and feedback here.

**Comment by yokas** [comment]
@marshall-lee @dblock 
Test result:
without `require 'grape'`: Requests per second:    430.80 [#/sec] (mean)
with `require 'grape'` original one: Requests per second:    126.40 [#/sec] (mean)
with `require 'grape'`, HEAD: Requests per second:    260.69 [#/sec] (mean)

**Comment by marshall-lee** [comment]
Twice, as I expected, but huge overhead still remains comparing to example without grape.

**Comment by marshall-lee** [comment]
@dblock I think you should close it. More info here: https://github.com/postrank-labs/goliath/issues/319#issuecomment-135345269

**Comment by dblock** [comment]
Makes sense, in development mode it reloads code every request. On goliath needs to run with `-prod`.
