### ISSUE TITLE
Requiring Grape appears to break the ruby YAML parser!

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1123]
```
require 'yaml'

my_yaml = '!!omap 
  - doc: 0'
yml = YAML::load(my_yaml)
puts "#{yml}"

require 'grape'

my_yaml2 = '!!omap 
  - doc: 0'
yml2 = YAML::load(my_yaml2)
puts "#{yml2}"
```
Output from the first puts is : ```{"doc"=>0}```
Output from the second puts is : ```{}``` and the following error is thrown by the line YAML::load(my_yaml2) :

```
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/ordered_hash.rb:4: warning: wrong element type String at 0 (expected array)
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/ordered_hash.rb:4: warning: ignoring wrong elements is deprecated, remove them explicitly
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.3/lib/active_support/ordered_hash.rb:4: warning: this causes ArgumentError in the next release
```

As if this were not strange enough, if I change ```!!omap``` to ```!omap``` all works fine and no errors.

Any idea what's going on here?

**Comment by marshall-lee** [comment]
Interesting...

**Comment by dblock** [comment]
This is nuts.

**Comment by marshall-lee** [comment]
So many related issues in one day!
This is again `ActiveSupport`'s quirk.
`ordered_hash.rb` doesn't simply define `OrderedHash`, it adds some extension to `YAML`
https://github.com/rails/rails/blob/7779e63371d1248bce5f30ebbae43e13ee7abb6a/activesupport/lib/active_support/ordered_hash.rb#L3

I think we don't need `OrderedHash` in `Grape` at all. I'll open PR soon.

**Comment by marshall-lee** [comment]
@atomless 

I guess you maybe use `omap` wrong. But I agree with you, `Grape` should not affect `YAML` behavior.

**Comment by atomless** [comment]
@marshall-lee good catch! The yaml I need to parse is coming in from an external source and appears to be valid according to http://www.yamllint.com/

**Comment by marshall-lee** [comment]
@atomless please report it to rails!

**Comment by atomless** [comment]
@marshall-lee since you'r merge that apparently fixed this issue I updated my Gemfile and now running bundle I see : ```Using grape 0.13.1 from git://github.com/ruby-grape/grape.git (at 82d7c70)```

However requiring grape STILL breaks the ruby yaml parser in the exact same way outlined above.

**Comment by marshall-lee** [comment]
@atomless I cannot reproduce it anymore.

Look:
```
$ git clone git@github.com:ruby-grape/grape.git
$ cd grape
$ bundle
$ bundle exec ruby example.rb
{"doc"=>0}
{"doc"=>0}
$ git checkout c8b657e # commit before removing OrderedHash
$ bundle exec ruby example.rb
{"doc"=>0}
/home/vkochnev/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/ordered_hash.rb:4: warning: wrong element type String at 0 (expected array)
/home/vkochnev/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/ordered_hash.rb:4: warning: ignoring wrong elements is deprecated, remove them explicitly
/home/vkochnev/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/ordered_hash.rb:4: warning: this causes ArgumentError in the next release
{}
```

Are you sure  you load `grape` from Gemfile, not the globally installed one? It's easy to check:

```
$ ruby -e "require 'grape'; puts Grape::VERSION"
0.13.0
$ bundle exec ruby -e "require 'grape'; puts Grape::VERSION"
0.13.1
```

Maybe you load another dependencies that `require 'active_support/ordered_hash'`? Check the value of `defined?(ActiveSupport::OrderedHash)`? It should be `nil`.

**Comment by marshall-lee** [comment]
Also, I recommend this for projects with `Gemfile`:
```ruby
require 'rubygems'
require 'bundler/setup'
```

**Comment by atomless** [comment]
@marshall-lee - apologies - you are absolutely right. I had an issue with bundler. All is working now and can confirm that your fix solves the issue for me too. Thanks!
