### ISSUE TITLE
grape no response and high CPU usage when exception raise.

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape#1132]
If there is a code throw an exception, and request grape api again, it will always processing request, and high CPU usage, other requests cannot be processed.

In Rails 4 development environment

**Comment by dblock** [comment]
This seems odd, you should try to provide a sample project where this happens. What's the process doing?

**Comment by dnesteryuk** [comment]
No response for more than 4 year, our company use Grape+Rails for 6 years, we didn't notice anything like that.
