### ISSUE TITLE
Support JSON as a first class group parameter type

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1135]
Today Grape supports Hash and Array as a group parameter type and [raises UnsupportedGroupTypeError](https://github.com/ruby-grape/grape/blob/cc1e46f218b8d0029c6533c81716289c44335192/lib/grape/dsl/parameters.rb#L114) for everything else. We would like to be able to do `type: JSON`, like so: 

```ruby
   resource :reticulated_splines do
      params do
        requires :splines, type: JSON do
          requires :id, type: Integer
          requires :reticulated, type: Boolean
        end
      end
      get do
        params[:splines].map do |spline|
          spline.merge(reticulated: !spline[:reticulated])
        end
      end
    end
```

Today you have to workaround this, see https://github.com/ruby-grape/grape-on-rack/commit/0f904bfe7f17603ce605a3458d6bcbbaad1a96ea:

```ruby
   resource :reticulated_splines do
      before do
        params.each_pair do |k, v|
          params[k] = JSON.parse(v) rescue v
        end
      end
      params do
        requires :splines, type: Array do
          requires :id, type: Integer
          requires :reticulated, type: Boolean
        end
      end
      get do
        params[:splines].map do |spline|
          spline.merge(reticulated: !spline[:reticulated])
        end
      end
    end
```

Note that the JSON itself can be an array or a hash. So maybe we can just generalize:

```ruby
requires :splines, type: Array, coerce_type: JSON do

requires :splines, type: Array, coerce_method: ->(val) { JSON.parse(val) }

requires :splines, type: Array, coerce_method: JSON.method(:parse) 
```

**Comment by dslh** [comment]
Here's my attempt. I've gone with a generalized solution to support both hashes and arrays, but it seemed natural to support primitive types as well so things like `type: Time, coerce_using: Chronic` are also possible.

At the moment it cannot be supplied without a `type` or `coerce` parameter. You could drop this constraint by either implicitly setting type to `String`, which the documentation already gives as the default type. Or with some adjustments it could bypass type checking altogether, but I don't know if that's good flexible API design or an invitation to lazy programmers.

I called it `coerce_using` to cover both classes and methods. Maybe that's confusing given the `using` parameter? `coerce_with` maybe?

**Comment by dblock** [comment]
Very nice work @dslh! I just commented on `coerce_with` vs. `coerce_using` in the PR, so sounds like we both think it's more natural to do `coerce_with`. LMK when you have updated it.

**Comment by dblock** [comment]
So after #1161 is merged can I write `type: JSON`, since `JSON.parse` exists or do we need to do more work?

**Comment by dslh** [comment]
I've updated the name to `coerce_with`. `type: JSON` will be extra work I believe, it would be passed to `Virtus::Attribute.build` as the type, and even if that somehow works I think it will fail in the last clause of `CoerceValidator::_valid_single_type?`.

I'm tempted to say implement it as `type: Array, coerce_with: ->(json) { Array.wrap JSON.parse(json, symbolize_names: true) }`. It might seem a bit hackish but I think it saves implementers from type checking every time. I think it's probably neater in terms of changes to `CoerceValidator` also. Let me know and I can either revise this patch or submit another building on it.

**Comment by dblock** [comment]
Lets leave this open until we can do `type: JSON`. Want to give an implementation a try?

**Comment by dslh** [comment]
Sure. Any objection to wrapping hashes in an array?

```ruby
it 'allows JSON as type' do
  subject.params do
    requires :ints, type: JSON do
      requires :int, Integer
    end
  end
  subject.get '/' do
    'json works' if params[:ints].first[:int] == 1
  end

  get '/', ints: '{"int":1}'
  expect(last_response.status).to eq(200)
  expect(last_response.body).to eq('json works')

  get '/', ints: '[{"int":1},{"int":2}]'
  expect(last_response.status).to eq(200)
  expect(last_response.body).to eq('json works')
end
```

**Comment by dblock** [comment]
You mean *always* wrapping them into an array? Maybe instead we could have `JSON` and `Array[JSON]`? Is that crazy?

**Comment by dslh** [comment]
My thinking is that `type: JSON` then becomes a shorthand for "one or many objects encoded as JSON", a pattern I've seen implemented in endpoints in the past. People wanting more control can then fall back to `type: Array/Hash, coerce_with: JSON`. We could also detect `Array[JSON]` as a shorthand but I don't know what you'd then use as an analogue for hashes.

This is why the first effort has `type` mandatory; without it there's no "most obvious" way things should work. `Array[JSON]` with `JSON` for hashes isn't crazy, it's maybe not immediately intuitive but neither is my proposal. It does leave people who don't care which is supplied with nowhere to go, but I don't know that any such people actually exist.

I suppose if anyone does want one-or-many functionality it could and probably should be uncoupled from JSON coercion. Some decorator like `type: one_or_many(Integer/JSON/Whatever)` could probably be achieved if anyone asks for it. `JSON` and `Array[JSON]` as shorthands, then? Should be pretty straight-forward to implement as such.

**Comment by dblock** [comment]
@dslh I am with you re: _one or many objects encoded as JSON_ but I am not a huge fan to forcing it to be an array of 1. If someone cares they can always do `x = Array(params[:x])`.

**Comment by dslh** [comment]
OK, I am probably over thinking things. I'll see what I can come up with for an ambiguous `type: JSON` directive.

**Comment by dslh** [comment]
There we are. `Array[JSON]` wraps single objects, `JSON` does not. `Array[JSON]` could be made to reject single objects easily enough but there doesn't seem to be a good reason for it. I am wondering if the documentation could be clearer or more concise, it makes sense to me but then I just wrote it.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1163.
