### ISSUE TITLE
A POST endpoint should not be reachable via GET

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1136]
If I define a POST endpoint like so:
```
params do
  requires :action, type: String
end
post :action do
  { status: 200 }
end
```
When this endpoint is targeted with a GET request I feel it should throw a 404 but the error is not getting through to my catchall error handler and instead I see an html page with the message:
```
This page contains the following errors:

error on line 1 at column 1: Document is empty
Below is a rendering of the page up to the first error.
```
If the endpoint is not defined at all then I do see the 404 response from the exception catch all. At the moment my exception catch all is just:
```
rescue_from :all do |e|
   error_response(message: e.message, status: 404)
end
```
Incidentally is there a way to have a rescue from specific to certain http statuses? I'd like to at least specify the actual http status in the response.

**Comment by dblock** [comment]
It should be returning a 406, Method not Allowed. Can you `curl` it and confirm that that's the case?

**Comment by towanda** [comment]
@atomless The error you mention is not from grape, It's from chrome trying to render in xml grape response. If you try to access it from firefox, It returns a more descriptive error:
```
XML Parsing Error: not well-formed
Location: http://localhost:9292/action
Line Number 1, Column 1:{:message=>"cannot convert String to xml"}
^
```

But if you try it with curl, it returns a 404 method, as @dblock says:
```
➜  ~  curl -v -X GET http://localhost:9292/action
* Adding handle: conn: 0x7fb714003a00
* Adding handle: send: 0
* Adding handle: recv: 0
* Curl_addHandleToPipeline: length: 1
* - Conn 0 (0x7fb714003a00) send_pipe: 1, recv_pipe: 0
* About to connect() to localhost port 9292 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 9292 (#0)
> GET /action HTTP/1.1
> User-Agent: curl/7.30.0
> Host: localhost:9292
> Accept: */*
>
< HTTP/1.1 405 Method Not Allowed
< Allow: OPTIONS, POST
< Content-Type: text/plain
< Content-Length: 0
* Server WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08) is not blacklisted
< Server: WEBrick/1.3.1 (Ruby/2.1.2/2014-05-08)
< Date: Mon, 31 Aug 2015 18:09:09 GMT
< Connection: Keep-Alive
<
* Connection #0 to host localhost left intact
```

To specify an http status, you can use ```status```, see https://github.com/ruby-grape/grape#http-status-code

**Comment by dblock** [comment]
@towanda Thanks, minor correction, It returns a 405 as expected (see above) :)

I am going to close this.

**Comment by atomless** [comment]
Sorry for the late reply, I was unable to look at this again until just now.

Here's the curl output to confirm the bug.
The "target/clear" endpoint is defined as a POST endpoint. 

Sending a POST request works as expected:
```
curl -d '' http://localhost/api/v1/target/clear

{"status":201}
```

Sending a GET request returns a 404:
```
curl -i -H "Accept: application/json" -H "Content-Type: application/json" -X GET http://localhost/api/v1/target/clear

HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 82
Vary: Origin
Connection: keep-alive
Server: thin

{"error":"API endpoint not found for request path: /api/v1/target/clear"}
```

Please can you reopen this issue?
