### ISSUE TITLE
jsonapi.org and custom vendor content type

### ISSUE THREAD

**Issue by igas** [ruby-grape/grape#1141]
Hi. According to spec http://jsonapi.org/format/#content-negotiation Content Negotiation part, I must use `application/vnd.api+json`.

If I do:
``` ruby
content_type :jsonapi, "application/vnd.api+json"
formatter :jsonapi, -> (object, _env) { Oj.dump(object) }
```
It return 406 cause try to use `json`. I found https://github.com/ruby-grape/grape/commit/3409da564294044a88b275f0651e6826988cec6c where vendor part drops. Is there any reason to do this?

From my point of view formatter should only format data, but it also overwrite content type but it is [here](https://github.com/ruby-grape/grape/blob/3409da564294044a88b275f0651e6826988cec6c/lib/grape/middleware/formatter.rb#L37).

Current implementation https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/formatter.rb#L170 & https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/formatter.rb#L122

Do I miss something?

**Comment by dblock** [comment]
You need to tell Grape which format to use, so `format :jsonapi` I think will do it?

**Comment by dblock** [comment]
Bring it up to the mailing list if you're still having problems, I'll close this here.
