### ISSUE TITLE
Using declared(params) as outlined in docs throws an exception

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1143]
Using Grape -0.13.1, I have this endpoint:
```
get 'test' do
  { "declared_params" => declared(params, include_missing: false) }
end
```
When I request that endpoint I see this error:

```NoMethodError: undefined method `to_sym' for String:Class
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:34:in `block (2 levels) in declared'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:33:in `each_pair'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:33:in `block in declared'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:30:in `each'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:30:in `each_with_object'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/dsl/inside_route.rb:30:in `declared'
	/Users/jamestindall/Documents/soasta/DOC/source/g-speak/Baton/BatonSite/dist/server/api/api.rb:27:in `block in <class:Root>'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:317:in `instance_eval'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:317:in `block (2 levels) in run_filters'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:316:in `each'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:316:in `block in run_filters'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:315:in `run_filters'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:250:in `block in run'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:219:in `run'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:201:in `block in call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:25:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:25:in `call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:19:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:25:in `call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:19:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/error.rb:27:in `block in call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/error.rb:26:in `catch'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/error.rb:26:in `call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/middleware/base.rb:19:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:202:in `call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/endpoint.rb:190:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:152:in `block in call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:96:in `block in recognize'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:68:in `optimized_each'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-mount-0.8.3/lib/rack/mount/code_generation.rb:95:in `recognize'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-mount-0.8.3/lib/rack/mount/route_set.rb:141:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/api.rb:114:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/api.rb:44:in `call!'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/grape-0.13.1/lib/grape/api.rb:39:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/cascade.rb:33:in `block in call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `each'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/cascade.rb:24:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-contrib-1.4.0/lib/rack/contrib/post_body_content_type_parser.rb:36:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-cors-0.4.0/lib/rack/cors.rb:80:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/tempfile_reaper.rb:15:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/sinatra-1.4.6/lib/sinatra/base.rb:218:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/chunked.rb:54:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/connection.rb:86:in `block in pre_process'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/connection.rb:84:in `catch'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/connection.rb:84:in `pre_process'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/sinatra-websocket-0.3.1/lib/sinatra-websocket/ext/thin/connection.rb:26:in `pre_process_with_websocket'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/connection.rb:53:in `process'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/sinatra-websocket-0.3.1/lib/sinatra-websocket/ext/thin/connection.rb:40:in `receive_data_with_websocket'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/sinatra-websocket-0.3.1/lib/sinatra-websocket/ext/thin/connection.rb:65:in `receive_data_with_flash_policy_file'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run_machine'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/handler/thin.rb:19:in `run'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/server.rb:286:in `start'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/lib/rack/server.rb:147:in `start'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/gems/rack-1.6.4/bin/rackup:4:in `<top (required)>'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/bin/rackup:23:in `load'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/bin/rackup:23:in `<main>'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
	/Users/jamestindall/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'```

**Comment by dblock** [comment]
Try to write a spec for this. The actual params matter probably.

**Comment by atomless** [comment]
Okay I've investigated this further and believe I have pinpointed what triggers the error.

I have a helper with this in it:
```
params :optional_prm do |options|
  optional :prm, String, values: ['valid_prm1', 'valid_prm2'], default: options[:default_prm], allow_blank: false
end
```

I also have this before validation method:
```
before_validation do
  @permitted_params = declared(params, include_missing: false)
end
```

The error is only thrown when I use the optional_prm on an endpoint AND define a default value like so:
```
params do
  use :optional_prm, default_prm: 'valid_prm1'
end
namespace 'an' do

  get 'endpoint' do
...
```

**Comment by atomless** [comment]
Any pointers on how I might be able to patch this bug would be much appreciated!

**Comment by dblock** [comment]
Do you have a failing spec for this?

**Comment by rnubel** [comment]
@atomless: the issue is a typo in your code, actually. This line is the problem:

      optional :prm, String, values: ['valid_prm1', 'valid_prm2'], default: options[:default_prm], allow_blank: false

The correct way to set a type for a param in Grape is with the `type:` option, not as the second argument to `optional` or `required`. What Grape is actually thinking you want is one parameter named `prm`, and one parameter named the String class, which wreaks havoc (as you've found). Try this instead:

      optional :prm, type: String, values: ['valid_prm1', 'valid_prm2'], default: options[:default_prm], allow_blank: false

**Comment by atomless** [comment]
Aha! Excellent spot @rnubel. Apologies for wasting people's time here!
