### ISSUE TITLE
Call After block on error!

### ISSUE THREAD

**Issue by ccastan1** [ruby-grape/grape#1147]
Not sure if this was resolved, but I've been trying to log api calls from the middleware and on an error! the after call doesn't get executed. Is there a good way around this issue? Thanks!

**Comment by dblock** [comment]
You can write a separate middleware to handle this. I am not theoretically against to executing `after` blocks on error, but it would be a fairly major functionality change.

**Comment by dblock** [comment]
@ccastan1 It would be good to have a minimal example here or a spec that demonstrates this.

**Comment by frobichaud** [comment]
@ccastan1 @dblock, this is how I'm trying to wrap API calls with a middleware:

```
  require 'grape/middleware/base'

  class MyGrapeMiddleware < Grape::Middleware::Base
    def before
      env[:my_setting] = true
    end

    def after
      env[:my_setting] = false
    end
  end
```

Then in my API:
```
class MyApi < Grape::API
  use MyGrapeMiddleware
  resource :example do
    get do
      {}
    end
  end
end
```

My middleware after block is never called when the API endpoint raises an error...

**Comment by frobichaud** [comment]
Looks like the following middleware would do it:

```
require 'grape/middleware/base'

class MyGrapeMiddleware < Grape::Middleware::Base
  def before
    env[:my_setting] = true
  end

  def after
    env[:my_setting] = false
  end

  def call!(env)
    begin
      @app_response = super(env)
    ensure
      after
    end
  end
end
```

**Comment by dblock** [comment]
Makes sense @frobichaud. If you have time, see if any tests break if `after` is executed on error as well. If nothing breaks, I would take a PR that documents, tests and explains the change in UPGRADING.

**Comment by guizmaii** [comment]
:+1: It could be a great functionality !

**Comment by rajnish4unow** [comment]
Great thanks for sharing this. I was trying to log on Success and Error so below implementation works for me.
```
  def before
    env[:request_json] = { start_time: Time.now }
  end

  def after
    json =  env[:request_json]
    json[:end_time] = Time.now
    puts json
  end

  rescue_from :all do |e|
    json =  env[:request_json]
    json[:end_time] = Time.now
    json[:errorMessage] = e.message
    puts json
  end
```
