### ISSUE TITLE
Wrong params received in Grape actions

### ISSUE THREAD

**Issue by nqtien310** [ruby-grape/grape#1148]
Send
````
{:external_id=>"e3009dea-c835-45e0-84b9-487e1b85b899", :name=>"Compassionate Leave (unpaid)", :unit_type=>"Hours", :leave_loading=>false, :hide_from_payslip=>false}, {:id=>7234, :payroll_disabled=>true}, {:id=>7235, :payroll_disabled=>true}
````
Receive
````
#<Hashie::Mash external_id="e3009dea-c835-45e0-84b9-487e1b85b899" hide_from_payslip="false" id="7234" leave_loading="false" name="Compassionate Leave (unpaid)" payroll_disabled="true" unit_type="Hours">, #<Hashie::Mash id="7235" payroll_disabled="true">
````

Somehow , from 3 elements array of Hash , I received 2 elements array of Hashie in Grape endpoint , with 2 of the them are merged.

I'm not sure this error relates to Hashie or Grape , if anybody has experience with this before , please help me , i'm stuck with it for a while

Best regards

**Comment by dblock** [comment]
See https://github.com/ruby-grape/grape/issues/1149 for an explanation. I am pretty sure it's the same (non)problem.
