### ISSUE TITLE
Grape merging request parameters

### ISSUE THREAD

**Issue by klaustopher** [ruby-grape/grape#1149]
This might be a related to #1148, but I wanted to give some more context, so I'm creating a new issue.

I am creating an API where users can answer some questions in a questionary. Since I don't want to call our API for every single question I'm allowing more than one answer in the API call.

Params look like this:
```ruby
  params do
    requires :answers, type: Array do
      requires :question_id, type: Integer
      requires :answer
    end
  end
```

So, I can receive an array of hashes with the form `{ question_id: 1, answer: { text: 'foo bar' } }`. The answer can actually be in different forms, depending on the question. Might also be something like `{ currency: 'EUR', value: 24.99 }`. This will be validated later. So I'm not specifying a `type` for `answer`, but it also happens if I specify `type: Hash`.

So, while testing I created a test case that something like the following should be rejected:

```json
{
  "answers": [
    { "question_id":1, "answer": { "text": "foo" } },
    { "answer": { "text": "bar" } }
  ]
}
```
I would have expected to get a `400` response, with the message, that `question_id` is missing, but instead I got the following when dumping the params:

```json
{
  "answers": [
    { "question_id": 1, "answer": { "text": "bar" } }
  ]
}
```

So, the params parser has merged both answer objects into one. This is (imho) a pretty serious bug. 

I have created a small test case (sorry, no time right now to integrate this into the grape test suite):

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'grape', '= 0.13.0'
  gem 'rack'
  gem 'rack-test'
  gem 'rspec'
end

require 'grape'
require 'rack/test'
require 'rspec'
require 'rspec/autorun'
require 'json'

class ParamsErrorAPI < Grape::API
  format :json

  desc 'Shows the error'
  params do
    requires :answers, type: Array do
      requires :question_id, type: Integer
      requires :answer
    end
  end

  post '/test' do
    params
  end
end

RSpec.describe ParamsErrorAPI do
  include Rack::Test::Methods

  def app
    ParamsErrorAPI
  end

  it 'works as expected when everything is provided' do
    payload = {
      answers: [
        { question_id: 1, answer: { text: 'foo' } },
        { question_id: nil, answer: { text: 'bar' } }
      ]
    }

    post '/test', payload

    expect(last_response.body).to eq(payload.to_json)
  end

  it 'should return an error if one of the fields is missing' do
    payload = {
      answers: [
        { question_id: 1, answer: { text: 'foo' } },
        { answer: { text: 'bar' } }
      ]
    }

    post '/test', payload

    puts last_response.body

    expect(last_response.body).to eq("{\"error\":\"answers[question_id] is missing\"}")

    # Actual Response is:
    # {
    #    "answers": [
    #      { "question_id":1, "answer": { "text": "bar" } }
    #    ]
    # }
  end
end
```

**Comment by dblock** [comment]
This is actually expected. There's [no standard way](http://stackoverflow.com/questions/6243051/how-to-pass-an-array-within-a-query-string) of passing arrays within a query string.

Rack::Test doesn't support this, so it produces the following value in env['rack.input']: `"answers[][question_id]=1&answers[][answer][text]=foo&answers[][answer][text]=bar"`. It works for a hash, but not for an array of hashes.

The solution is not to POST data in a query string. You should be doing a JSON POST with a content-type of `application/json`. For your example the following fixes the test:

```ruby
    post '/test', payload.to_json, 'CONTENT_TYPE' => 'application/json'
```

**Comment by klaustopher** [comment]
Ah, thanks... I thought I had added the Content-Type as a default, but it isn't... Sorry for the trouble

**Comment by dblock** [comment]
N/p :)
