### ISSUE TITLE
Grape array of hash as parameter

### ISSUE THREAD

**Issue by rizalmuthi** [ruby-grape/grape#1152]
Hi,

Thank you very much for this gem
But seems, i could not find anyway how to set the params so it can check/accept this kind of format:
```
"activities":[  
      {  
         "activity":"sleep",
         "purpose":"rest",
         "day":0,
         "start":"23:00",
         "stop":"06:30"
      },
      {  
         "activity":"sleep",
         "purpose":"rest",
         "day":1,
         "start":"23:00",
         "stop":"06:30"
      }
   ]
```

Its an array with the value of hash. I could not get an idea how to setup this for the params.
is this possible?
Thanks

**Comment by dblock** [comment]
Check out https://github.com/ruby-grape/grape#validation-of-nested-parameters, e-mail the mailing list if you can't get it to work.
