### ISSUE TITLE
Param type Rack::Multipart::UploadedFile does not result in object of that type

### ISSUE THREAD

**Issue by alexandergitter** [ruby-grape/grape#1164]
Declaring a parameter as Rack::Multipart::UploadedFile doesn't seem to actually yield a parameter of the same type. Instead I'm getting instances of Hashie::Mash.

The endpoint i use to test this looks as follows:

```ruby
params do
  requires :avatar, type: Rack::Multipart::UploadedFile
end
post '/' do
  ...
end
```

**Comment by dslh** [comment]
That's correct. This hash is created by `Rack::Request` when processing multipart file data. Grape wraps it with Hashie for convenience.

```ruby
post '/' do
  params.avatar.filename # => 'avatar.png'
  params.avatar.type # => 'image/png'
  params.avatar.tempfile # => #<File>
end
```

Not sure if this is documented anywhere in either library.

**Comment by dblock** [comment]
I'll leave this open, @alexandergitter feel free to suggest a doc improvement?

**Comment by alexandergitter** [comment]
Sure, I'll take a look at it later this week.

**Comment by dslh** [comment]
This is now documented in the readme. Close?

**Comment by dblock** [comment]
Closing.
