### ISSUE TITLE
File and Rack::Multipart::UploadedFile are different in params type.

### ISSUE THREAD

**Issue by long-long-float** [ruby-grape/grape#1171]
I used `File` and `Rack::Multipart::UploadedFile` as type in params block. Then I got `file is invalid` when I use `File`. Using `Rack::Multipart::UploadedFile`, I got valid size of file.

I tested following code:

```rb
desc 'Returns file size'
params do
  requires :file, type: Rack::Multipart::UploadedFile
end
post :file_size1 do
  {
    data: params[:file].tempfile.size # got {"data": size of file}
  }
end

desc 'Returns file size'
params do
  requires :file, type: File
end
post :file_size2 do
  {
    data: params[:file].tempfile.size # got {"error":"file is invalid"}
  }
end
```

Sorry for my broken English.

**Comment by dblock** [comment]
`type: File` hasn't shipped yet, see https://github.com/ruby-grape/grape/blob/master/CHANGELOG.md. Is that it? 

I'll close it, but reopen if this is still a problem on HEAD.
