### ISSUE TITLE
NoMethodError: undefined method `[]' for nil:NilClass w/ Warden

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1174]
Discussed in https://github.com/ruby-grape/grape/issues/1151, see https://github.com/hassox/warden/pull/119 for a fix in Warden. Needs a note in UPGRADING for Grape.

**Comment by dblock** [comment]
@ka8725 Do you think you can check this again (coming from #1151) and maybe PR some UPGRADING note?

**Comment by ka8725** [comment]
I checked it and can confirm that it works now. Created PR - https://github.com/ruby-grape/grape/pull/1557

**Comment by dblock** [comment]
Closing, thanks.
