### ISSUE TITLE
How to see elapsed time in rendering view

### ISSUE THREAD

**Issue by aoyama-val** [ruby-grape/grape#1175]
Normally, Rails writes logs like
```
Completed 200 OK in 40ms (Views: 7.3ms | ActiveRecord: 0.0ms) 
```
in development.log.
However, when using grape, it doesn't. How can I see elapsed time?

**Comment by dblock** [comment]
This is something you can do with a middleware. There're a few in the logging section of http://www.ruby-grape.org/projects, but you'll probably will have to write one to achieve exactly this. Other possibly better long term solutions are things like newrelic.

I'm going to close this, please use the mailing list for questions.
