### ISSUE TITLE
Nested requires method does not work properly 3 levels deep.

### ISSUE THREAD

**Issue by jimboslicethat** [ruby-grape/grape#1180]
If a parameter is optional AND a hash or an array, all required parameters within the optional hash or array should only validate as required if the parent parameter exists in the request. 
However, this seems to break three levels deep. I have a parent param which has a required child array. And inside that child array I have an optional grandchild array. Any requires methods within the grandchild array will throw errors up to the child array, if the child array does not contain the grandchild arrays required fields. This error gets thrown despite the grandchild array being optional.
For example:
```
params do 
    requires :order, :type => Hash do
        requires :order_details, :type => Array do
            requires :order_detail, :type => Hash do
                requires :cost, type: Integer#, desc:
                requires :quantity_ordered, type: Integer#, desc:
                requires :item_id, type: Integer#, desc:
                optional :order_detail_custom_fields, :type => Array do
                    optional :order_detail_custom_field, :type => Hash do
                        requires :field_name, type: String#, desc:
                        optional :field_value, type: String#, desc:
                    end
                end
            end
        end
    end
end
```

In my example above, if an `:order_detail` does not contain an optional `order_detail_custom_field` with a `:field_name`, Grape will throw an error to the request, even though that grandchild array is optional.  However, `:order_detail`s `:cost`, `:quantity`, and `:item_id` required parameters all work exactly as you would expect. The error stops getting thrown as soon as I change `:field_name` to optional. It seems like this error only occurs when at the third level of nesting parameters. In all of my other endpoints I have never experienced this problem, because they only go two levels deep.

**Comment by dslh** [comment]
I've attempted to write a failing spec to duplicate your problem but I can't coax it into failing. Do you think you could take a look and see if there is anything obviously different to your setup, or maybe have a go at getting it working (i.e. failing) yourself? Maybe some of the stuff you've cropped out such as `desc` are significant?

**Comment by dblock** [comment]
Try to build a minimal example maybe on top of https://github.com/ruby-grape/grape-on-rack? I mean either way we just need to isolate this first.

**Comment by jimboslicethat** [comment]
Unfortunately in between the time I posted this and today, there has been a massive push by upper management to move to a C# .NET environment with the current API which is written in Ruby with Grape. I'd like to say that I can justify the time trying to figure this out just in case it is  a bug, but if you aren't able to replicate the problem, my guess is that it has something to do with the version of the gem I am using, or some anomaly somewhere. Thanks for looking into this for me, I am fine to have this dismissed.

**Comment by dblock** [comment]
Closing this. Sorry to hear you're stuck with C# for writing an API @jimboslicethat  :(
