### ISSUE TITLE
per-action before/after hooks?

### ISSUE THREAD

**Issue by suan** [ruby-grape/grape#1183]
Right now it seems that the smallest unit which we can apply a before/after block to is the resource or namespace. It would be really nice to be able to apply these hooks to just specific actions. e.g.:

```ruby
class MyAPI < Grape::API
  get '/' do
    before { # do something }
  end

  post '/' do
    before { # do something else }
  end
end
```

**Comment by codegoblin** [comment]
+1. I would also like scoped before_filter-type functionality

**Comment by dblock** [comment]
Did you try `namespace` without arguments around a single method? 

I think a plain `before` block would make sense just like `params`, but unfortunately that would be ambiguous with one that applies to the entire current scope. Suggestions welcome.

**Comment by thejchap** [comment]
@dblock is this outstanding still? Looking for a way to contribute....wouldn't mind tackling this

Re: scoping perhaps the methods could be called outer -> inner (in the order they're defined) similar to the order of execution of `before` blocks in rspec contexts

**Comment by dblock** [comment]
Yes @thejchap. I am not sure I would like to introduce another variation of `before` called `outer` tbh. Can we first check whether `scope` or `namespace` lets one do a `before` method?

**Comment by jrforrest** [comment]
Ghetto-tested and nesting under a namespace seems to work.

```ruby
 class Api < Grape::API
   before { puts 'hi' }
   get('/foo') {'foo' }

   namespace do
     before { puts 'sup' }
     get('/bar') { 'bar' }
   end
 end
```

Output:
```
hi
127.0.0.1 - - [02/Dec/2015:23:16:43 -0500] "GET /foo HTTP/1.1" 200 3 0.0010
hi
sup
127.0.0.1 - - [02/Dec/2015:23:16:50 -0500] "GET /bar HTTP/1.1" 200 3 0.0015
```

**Comment by dblock** [comment]
I am going to close this for now. If someone can come up with a better syntax than the `namespace` workaround, please speak up and/or try a PR.
