### ISSUE TITLE
Integer Parameter in GET request not coerced properly

### ISSUE THREAD

**Issue by codegoblin** [ruby-grape/grape#1184]
Hi,

given the following:
```
params do
  requires :project_id, desc: 'ID of Project', type: Integer, coerce: Integer
end
get do
  Card.where(project_id: params[:project_id]).order(created_at: :desc)
end
```
when I make the request `/cards.json?project_id=1`, I get 
```
{
  "error": "project_id is invalid"
}
```
If I switch to `type: String`, however, this works. Any idea why the coerce isn't working? Is this intentional?

**Comment by codegoblin** [comment]
Funny enough, using rack test methods this, however, does pass if I do 
```
let(:params) do
        {
          project_id: project.id.to_s
        }
end
get '/cards', params
```
however, `curl -X GET --header "Accept: application/json" "http://api.kancan.localhost/cards.json?project_id=1"` is still returning `{"error":"project_id is invalid"}`

**Comment by codegoblin** [comment]
Ok, I got more information. Given the previous curl request, the project_id param actually will get the String value '1?' instead of just '1' for some reason.

**Comment by codegoblin** [comment]
changing my test from `get '/cards', params` to get `'/cards?project_id=1'` yields the same results. Looks like a problem with parsing query params.

**Comment by dblock** [comment]
@codegoblin You closed this? Care to explain?
