### ISSUE TITLE
grape routes with rake

### ISSUE THREAD

**Issue by MeterSoft** [ruby-grape/grape#1191]
How i can mount one class to different routes
my code

module Inter
  class API < Grape::API
    mount ::API::V1::InterV1 => "/api"
    mount ::API::V2::InterV2 => "/api/v2"
    mount ::API::V2::InterV2 => "/api/software"
  end
end

but it generate /api/v2/api/software

**Comment by rnubel** [comment]
It's not currently possible to mount one API under two different routes. See https://github.com/ruby-grape/grape/issues/570 for more details and a workaround.

**Comment by dblock** [comment]
Closing this as a dup of #570.
