### ISSUE TITLE
Support for first-class JSON types broken for optional arguments

### ISSUE THREAD

**Issue by ivoanjo** [ruby-grape/grape#1197]
As the title says, the support for first-class JSON types is broken when using optional arguments.
Taking the example in the documentation

```ruby
params do
  requires :json, type: JSON do
    requires :int, type: Integer, values: [1, 2, 3]
  end
end
get '/' do
  params[:json].inspect
end
```
and modifying it to
```ruby
params do
  optional :json, type: JSON do
    requires :int, type: Integer, values: [1, 2, 3]
  end
end
get '/' do
  params[:json].inspect
end
```
gets me a 
> ```/home/knuckles/.rvm/gems/ruby-2.2.3/bundler/gems/grape-b3c51df71dca/lib/grape/dsl/parameters.rb:125:in `optional': group type must be Array, Hash, JSON or Array[JSON] (Grape::Exceptions::UnsupportedGroupTypeError)```

It seems to me that the issue is that the check added to https://github.com/ruby-grape/grape/blob/80a46ba086697ddd8326e4b6292ff0b65cde81b5/lib/grape/validations/params_scope.rb#L140 should also be replicated to https://github.com/ruby-grape/grape/blob/80a46ba086697ddd8326e4b6292ff0b65cde81b5/lib/grape/dsl/parameters.rb#L121 , but I'm not confortable enough with the codebase to know if that's enough or the right thing to do (TM) :smile:

**Comment by dblock** [comment]
Looks legit. Try to write a spec for this.

**Comment by dslh** [comment]
:+1: I think you've got it, I didn't see that when I was adding the feature. Probably a good thing to do would be to declare, say, `GROUPS = [Array, Hash, JSON, Array[JSON]]` in [types.rb](https://github.com/ruby-grape/grape/blob/master/lib/grape/validations/types.rb) and use it in both locations.

**Comment by dslh** [comment]
Existing spec: https://github.com/ruby-grape/grape/blob/master/spec/grape/validations/validators/coerce_spec.rb#L335

**Comment by namusyaka** [comment]
@ivoanjo Can you send a pull request?

**Comment by ivoanjo** [comment]
I will try to refresh my branch and submit a PR. I didn't submit at the time as I wasn't sure that my fix was the right approach for the issue.

**Comment by anothermh** [comment]
I can confirm that patching in `fail Grape::Exceptions::UnsupportedGroupTypeError.new unless [Array, Hash, JSON, Array[JSON]].include?(type)` fixed this. I can't work on the spec but just wanted to confirm that @ivoanjo's solution worked for me. 👍

**Comment by dblock** [comment]
Closing via #1290.
