### ISSUE TITLE
Release 0.13.1

### ISSUE THREAD

**Issue by atomless** [ruby-grape/grape#1199]
We're currently using the specific install gem in order to install the latest version of grape. There are various fixes we rely upon but in particular this commit : https://github.com/ruby-grape/grape/commit/99fabb84f489811d8a5b2f3e74b6939164413394

Any idea when we can expect a new gem version release?

**Comment by dblock** [comment]
Renamed to "release 0.13.1", also review whether it should be 0.14.0. No promises, but soon.

**Comment by atomless** [comment]
Great. Thanks!

**Comment by pedelman** [comment]
Thanks! Also looking forward to the next release

**Comment by dblock** [comment]
There're some changes like https://github.com/ruby-grape/grape/pull/1201 that don't change anything at the interface level, but may have tricky consequences. If you have a test suite for a Grape API, run your tests against HEAD and let us know!

**Comment by dblock** [comment]
@marshall-lee is on the hook for this release

**Comment by dblock** [comment]
I was impatient and cut a release.
