### ISSUE TITLE
Custom coerce not working

### ISSUE THREAD

**Issue by FlorinAsavoaie** [ruby-grape/grape#1212]
I am trying to make sure that I unescape a parameter that comes from the URL:

```ruby
requires :name, type: String, coerce_with: ->(p){ URI.decode_www_form_component(p) }
```
...
```ruby
post ':name' do
end
```

However, this raises a `Grape::Exceptions::UnknownValidator` exception.

I don't think I am doing something wrong as it looks exactly like the examples from the documentation. I also tried `corce_with: URI.method(:decode_www_form_component)` and I get the same error.

Is coercion broken in the current release?

**Comment by dm1try** [comment]
> Is coercion broken in the current release?

`coerce_with` is only available on the master branch. See the [stable release note](https://github.com/ruby-grape/grape#stable-release). The latest changes can be found in [CHANGELOG.md](https://github.com/ruby-grape/grape/blob/master/CHANGELOG.md).

**Comment by dblock** [comment]
@marshall-lee Is on the hook to make the next release I believe ;)
