### ISSUE TITLE
How to test a GET request with JSON data via curl command tool 

### ISSUE THREAD

**Issue by rogerluo410** [ruby-grape/grape#1217]
Hi, 

For example , 
if have a GET method in API like this:
```ruby
params do
      requires :pa, type: Hash do
            requires  par1...
            requires  par2...
            requires  par3...
       end
end

get do
     #do something with params[:pa]
end
```
I would like to know how to test the GET request that it has a input parameter which is JSON format.

I saw the example in the repo :8ball: 

```ruby
params do
  requires :json, type: JSON do
    requires :int, type: Integer, values: [1, 2, 3]
  end
end
get '/' do
  params[:json].inspect
end

# ...

client.get('/', json: '{"int":1}') # => "{:int=>1}"
client.get('/', json: '[{"int":"1"}]') # => "[{:int=>1}]"

client.get('/', json: '{"int":4}') # => HTTP 400
client.get('/', json: '[{"int":4}]') # => HTTP 400
```
WHAT the client it is , and  how to test above API via curl ?

I'm blocking on it, hope someone to help me out.

THX in advance!

**Comment by dm1try** [comment]
Please use the mailing list for [questions](http://groups.google.com/group/ruby-grape).
>WHAT the client it is , and how to test above API via curl ?

 - start your application server
 - run `curl http://localhost:9000/?json={"int":1}`

**Comment by chaitanya4b3** [comment]
Run your existing server:

curl http://192.xx.xx.xx:xxxx/upload/?formatjson={\"id\"}:
This will display all the JSON arrays in that string.
