### ISSUE TITLE
Using Cucumber with Grape

### ISSUE THREAD

**Issue by mathieujobin** [ruby-grape/grape#1223]
Anyone ever done Cucumber scenarios to test an API built on Grape?

I see there is a gem for [cucumber-sinatra](https://github.com/bernd/cucumber-sinatra)
so unless there is something already, I might need to fork this one out?

**Comment by dblock** [comment]
Use the [mailing list](http://groups.google.com/group/ruby-grape) for questions, please. Looking forward to seeing a grape-cucumber library or something like that!

**Comment by mathieujobin** [comment]
I forked cucumber-sinatra, which was a fork a cucumber-rails it self.

made few adjustments, already

https://github.com/mathieujobin/cucumber-grape

cheers

**Comment by dblock** [comment]
Make sure to add it to http://www.ruby-grape.org/projects/. And you need ... tests!
