### ISSUE TITLE
Expose all declared params through the DSL

### ISSUE THREAD

**Issue by why-el** [ruby-grape/grape#1230]
Hi,

Say I declared multiple params, p1, p2, p3, and it does not matter if required or optional. I did some digging and couldn't find a *easy* way to grab all of these (useful for when some processing requires you diff what you receive against the canonical list of params). 

Some Ruby metaprogramming can get me there, but I'd rather see if the DSL can take care of this. Perhaps something like `expected_params`?

**Comment by stjhimy** [comment]
maybe `declared(params)`? Look at this spec: 

https://github.com/ruby-grape/grape/blob/master/spec/grape/validations/params_scope_spec.rb#L347

**Comment by why-el** [comment]
Yes, exactly. No idea how I missed that. Thank you! :)
