### ISSUE TITLE
How to validate dependent parameters 

### ISSUE THREAD

**Issue by brahamshakti** [ruby-grape/grape#1231]
In you documentation you said that dependent parameter can be validated using

    params do
        optional :shelf_id, type: Integer
        given :shelf_id do
            requires :bin_id, type: Integer
        end
    end

but how can i perform validation on basis of two fields like

    params do
        optional :first_name, type: String
        optional :last_name, type: String
        given :first_name, :last_name do
            requires :ssn, type: String
        end
    end

Is it possible to do that I tried it but swagger is not validating ssn.

**Comment by dblock** [comment]
A nested `given` _might_ work, but I think this is a feature request, it seems fairly straightforward. Want to try to implement it?

**Comment by ochagata** [comment]
This can be closed

**Comment by dblock** [comment]
Closed via #1237.
