### ISSUE TITLE
How to access outter methods from callback?

### ISSUE THREAD

**Issue by TangMonk** [ruby-grape/grape#1235]
```
after do
   test
end

def test
   1
end
```

It will throw an error with `=> NameError: undefined local variable or method 'test'`

**Comment by namusyaka** [comment]
The test method should be defined in `helpers` block.

```ruby
helpers do
  def test
    1
  end
end

after do
   test
end
```
Or, you can define the method on your module and pass it to the `helpers` method.

```ruby
module CustomizeMethods
  def test
    1
  end
end
helpers CustomizeMethods

after do
   test
end
```

**Comment by namusyaka** [comment]
The test method should be defined in `helpers` block. 
```ruby
helpers do
  def test
    1
  end
end
after do
  test
end
```

Or, you can define the method on your module and pass it to `helpers` method.

```ruby
module CustomizeMethods
  def test
    1
  end
end
helpers CustomizeMethods
after do
  test
end
```

Hope this helps.

**Comment by TangMonk** [comment]
@namusyaka thanks, I will try :D

**Comment by TangMonk** [comment]
@namusyaka 

Have you used this gem for reputation [https://github.com/merit-gem/merit](https://github.com/merit-gem/merit)? It has nice way for define reputation rules. But it only works on rails controller now. I just wanna to transplant to support grape .


It's core code:
```
class Engine < Rails::Engine
    initializer 'merit.controller' do |app|
      ActiveSupport.on_load(:action_controller) do
          # Load app rules on boot up
          include Merit::ControllerExtensions
      end
    end
end
```

I am thinking using grape callback to implement this.

**Comment by dblock** [comment]
Closing this since it works as expected. 

@TangMonk please use the mailing list for questions, thx
