### ISSUE TITLE
A param of type Hash is converted to Array in declared(params)

### ISSUE THREAD

**Issue by arempe93** [ruby-grape/grape#1239]
Spec describing the issue

``` ruby
it 'declared Hash groups should be a Hash' do

    app.params do
        optional :group, type: Hash do
            optional :foo, type: String
        end
    end
    app.get :group do
        declared(params).to_json
    end

    get '/group'
    json = JSON.parse(last_response.body)

    puts json['group'].class.name
    expect(json['group']).to be_kind_of(Hash)
end
```

This produces the following output

```
Array
Failure/Error: expect(json['group']).to be_kind_of(Hash)
       expected [] to be a kind of Hash
```

Setting a default on the param is a workaround

``` ruby
it 'declared Hash groups should be a Hash' do

    app.params do
        optional :group, type: Hash, default: {} do
            optional :foo, type: String
        end
    end
    app.get :group do
        declared(params).to_json
    end

    get '/group'
    json = JSON.parse(last_response.body)

    puts json['group']
    expect(json['group']).to be_kind_of(Hash)
end
```

This spec passes without error with the expected output

```
{ "foo" => nil }
```

Using Grape v0.14.0, running specs on master

**Comment by dblock** [comment]
Looks like a definite bug, I would expect `group` not to be in the response at all without a `default`, right?

**Comment by arempe93** [comment]
That could be an expectation, yes. Personally I like having it still be there and showing the values of the nested parameters because of the way I use / think about them as groups. But in either case, I don't think an Array is an expected value

**Comment by ochagata** [comment]
I believe that this is due to this specific line:

https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/inside_route.rb#L48

**Comment by arempe93** [comment]
Is this an intended behavior, as set forth by [this spec in `specs/grape/endpoint_spec.rb`?](https://github.com/ruby-grape/grape/blob/fbf633dbfec2b4a1586d60340d7517aecb5662fb/spec/grape/endpoint_spec.rb#L343). This tests pretty much the exact opposite of the spec from the issue description

**Comment by dblock** [comment]
I think that spec ignores the fact that there's an explicit `type`.

**Comment by dnesteryuk** [comment]
@kadotami fixed this issue in https://github.com/ruby-grape/grape/pull/2043 :fireworks:
