### ISSUE TITLE
Header versioning allows jibberish

### ISSUE THREAD

**Issue by mariovisic** [ruby-grape/grape#124]
Hi Guys

Currently when header versioning is enabled (even with the strict option) sending a request without a valid vendor string will result in the first version being matched.

On line #37 here the loop will not run if the Accept header doesn't match the string.
https://github.com/intridea/grape/blob/master/lib/grape/middleware/versioner/header.rb#L37

This doesn't seem like the correct behaviour to me. Would it be better to render a 404 instead? If so then i'll see about adding a failing test + patch to solve the problem.

**Comment by paulnicholson** [comment]
I agree with @jpaas, our version header includes a format key and I would like it to return a 406 unless the accept header include the current vendor and format.

**Comment by dentarg** [comment]
> I would like to see strict mean that the header must match one of the mounted versions, otherwise 406.

This is what I expected after implementing versioning according to the README of grape.

**Comment by dblock** [comment]
I am down with the above, PR someone please?

**Comment by dm1try** [comment]
Fixed in #1101
