### ISSUE TITLE
How to make http request to redirect https?

### ISSUE THREAD

**Issue by ved54321** [ruby-grape/grape#1246]
Currently i have implemented my rest api with http://some_url/api ,how will i convert this to use https://some_url/api ? 

Is there any feature of  grape to implement the same?

**Comment by jf** [comment]
Do u have a web server in front of Grape?

**Comment by dm1try** [comment]
@ved54321 you should configure your web server to achieve this.
 If you really need to do HTTPS redirects on an application layer you may try [rack-rewrite](https://github.com/jtrupiano/rack-rewrite) or something similar.
