### ISSUE TITLE
parameter validation with 'type: Float' does not work with path component

### ISSUE THREAD

**Issue by jf** [ruby-grape/grape#1247]
I haven't been able to figure this one out, but right now, if you declare a param as type: Float, and use it as a path component, Grape will always return a 404 unless you give it an *integer*...

e.g.
```
params do
    required :val, type: Float
end
get '/hello/:val' do
    params.val
end
```

"GET /hello/0" => "0"
"GET /hello/0.5" => 404
"GET /hello/239.23" => 404
"GET /hello/239" => "239"

**Comment by dm1try** [comment]
@jf the compiled regexp for the route above has an exclude rule for the `.` char by default:
 ```ruby
:compiled => /\A\/hello\/(?<val>[^\/.?]+)(?:\.(?<format>[^\/.?]+))?\Z/
```
But you can provide own regexp for any param by using `requirements` option
```ruby
get '/hello/:val', requirements: {val: /\d*\.?\d+/ } `
```

**Comment by jf** [comment]
Thanks, @dm1try, for the explanation! this works. Will work with this for now.
