### ISSUE TITLE
How to call one endpoint from another modules?

### ISSUE THREAD

**Issue by micfan** [ruby-grape/grape#1250]
API SDL `interface` feature is required for method calling cross API class. The discuss was posted [Grape Google Group](https://groups.google.com/forum/#!topic/ruby-grape/5ryOy34O2Y8). The result may be:

``` ruby
Class Twitter < Grape::API
  params do
    ...
  end
  interface :my_method do 
    return a+b
  end
end
```

Now the call can by the below, but `env` is not easy constructed :-(

``` ruby
# ret is an Array
ret = Twitter::API.endpoints[0].call(env)
```

**Comment by vanburg** [comment]
+ looking for such feature too, in Rails it's easy as (Warden example):

```ruby
manager.failure_app = lambda { |env| SessionsController.action(:new).call(env) }
```

**Comment by myxoh** [comment]
In the codebase of an app I work on we do:
`APIRoot.call(env)`  where APIRoot is the endpoint in which everything is mounted. However, you can do this on every parent endpoint.

in our case
```
# config/routes.rb
RailsApp::Application.routes.draw do
  mount APIRoot => "/api"
end
```

```
# app/api/api_root.rb
class APIRoot < Grape::API
  mount OtherEndpoint
  ...
end
```

**Comment by micfan** [comment]
the `mount` is a good way the internal call, or we can use a middleware call self
