### ISSUE TITLE
Support present in before

### ISSUE THREAD

**Issue by yoonwaiyan** [ruby-grape/grape#1251]
From what I've understand from Issue #39, I've create a before filter for a block of my API classes, which authenticates user for every API call within that block. The API should return a JSON with status and error message that notifies user about failed API calls. Currently I've overwritten the error block of my API  base file which returns status of 1 and the error message whenever an error occured in the API call. 

There's no documentation on how to call the `present` syntax in before_block and end the request which behaves like Rails `before_filter`. For authentication, I wanted to return another status other than 1, maybe a status of 9, but the only way to end the request is to raise an error which return the default status of 1. I tried use `present` and put `return` to end the API call but it raised up an error. Any workaround on this?

The code below is my API base file.

```ruby
require 'grape-swagger'

module Api  
  class Base < Grape::API
    rescue_from :all do |e|
      Rails.logger.error "#{e.message}\n\n#{e.backtrace.join("\n")}"
      Rollbar.error(e)
      # Call Grape error
      error!(e)
    end

    prefix 'app_name.api'
    version 'v1', using: :param
    format :json
	  error_formatter :json, ->(message, backtrace, options, env) {
      { status: 1, message: "error: #{message}" }.to_json
	  }

    before do
      header['Access-Control-Allow-Origin'] = '*'
      header['Access-Control-Request-Method'] = '*'
    end

    # API that needs authentication
    group do
      before do
        if params[:auth_token]
          unless Customer.where(auth_token: params[:auth_token]).count >= 1
            # how to return an API using present in this before block?
            error!("Authentication failed.")
          end
        end
      end

      params do
        optional :auth_token, type: String, desc: "Authentication Token"
      end
      mount Api::Categories
      mount Api::Coupons
      mount Api::Customers
    end

    # API that does not need authentication
    group do
      mount Api::UnauthenticatedCustomers
    end
    
    add_swagger_documentation api_documentation: { desc: 'Reticulated splines API swagger-compatible documentation.', hidden: true }
  end
end
```

**Comment by dblock** [comment]
In this case, I think what you want is an error handler that returns a certain type of data, and not to use present in the `before` block.

```ruby
rescue_from :all, backtrace: true do |e|
  error = { type: 'other_error', message: e.message }
  error[:backtrace] = e.backtrace unless Rails.env.production?
  rack_response(error.to_json, 400)
end
```

We could support `present` in the `before` and `after` blocks, as we now support things like `header`, so I'll leave this open as a feature request.

**Comment by dblock** [comment]
This was titled "How to return and end the API call using before block?", the answer to that question I believe is by calling `error!`, but I realize that's not documented, at least clearly. Also it's not clear whether the `after` block would be called anyway in this case.

I opened https://github.com/ruby-grape/grape/issues/1253, it would be great if you could see which tests we have for those cases and maybe add some and document any undocumented behavior.

**Comment by yoonwaiyan** [comment]
From my code above, for any error I did a rescue block and format it into a JSON format like this:

      error_formatter :json, ->(message, backtrace, options, env) {
          { status: 1, message: "error: #{message}" }.to_json
      }

The problem with throwing error is I wanted to show another status instead of `status:1`. If `rack_response` will throw the response without going through `error_formatter`, how do I know the error is an authentication error among other application errors?

**Comment by dblock** [comment]
It's too bad that we're not giving access to the actual exception in `error_formatter`. Is that the piece missing?

**Comment by yoonwaiyan** [comment]
I can use the `message` parameter and do a workaround like this:

    error_formatter :json, ->(message, backtrace, options, env) {
      if message == "Authentication failed."
        { status: 2, message: "error: #{message}" }.to_json
      else
        { status: 1, message: "error: #{message}" }.to_json
      end
    }

but it looks more like a trick. Hopefully there's a better way to handle it.

**Comment by dblock** [comment]
@yoonwaiyan So looks like there isn't. We probably want to extend `error_formatter` to return the exception in either `options` or change that interface.

**Comment by yoonwaiyan** [comment]
What if I want to return status code of 401 instead of 500 thrown in `error!`, where should i change? I've tried the `rack_response` but `rescue_from :all` block is not called from the `error!` from the before block. I've tried call `rack_response` directly from the before block:

```ruby
      before do
        if params[:auth_token]
          unless Customer.where(auth_token: params[:auth_token]).count >= 1
            rack_response("Authentication failed", 401)
          end
        end
      end
```

but the server returns error:

```ruby
undefined method `rack_response' for #<Grape::Endpoint:0x007f83762725a8>

/Users/yoonwaiyan/Documents/workspace/sweetspot-rails/app/api/api/v1/root.rb:30:in `block (2 levels) in <class:Root>'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:319:in `instance_eval'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:319:in `block (2 levels) in run_filters'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:318:in `each'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:318:in `block in run_filters'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:317:in `run_filters'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:231:in `block in run'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.3/lib/active_support/notifications.rb:166:in `instrument'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:219:in `run'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/endpoint.rb:201:in `block in call!'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:24:in `call'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:24:in `call!'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:18:in `call'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:24:in `call!'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:18:in `call'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/error.rb:27:in `block in call!'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/error.rb:26:in `catch'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/error.rb:26:in `call!'
/Users/yoonwaiyan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/grape-0.13.0/lib/grape/middleware/base.rb:18:in `call'
```

**Comment by arempe93** [comment]
@yoonwaiyan you should be able to use `error!` in the `before` block with a status param

```
error! 'Authentication failed', 401
```

As an aside, I like to create a helper for this, for readability

```
def unauthenticated!(message, headers = {})
  error! message, 401, headers
end
```

**Comment by yoonwaiyan** [comment]
@arempe93 Thanks for the info, it worked :+1:

**Comment by dblock** [comment]
What do we want to do with this issue @yoonwaiyan ?

**Comment by yoonwaiyan** [comment]
Closing this issue for now.
