### ISSUE TITLE
Recommended 404 handling breaks OPTIONS requests

### ISSUE THREAD

**Issue by arempe93** [ruby-grape/grape#1260]
When using the 404 handling recommended by the README, it breaks all options requests in the API.

Spec

``` ruby
it 'allows options with 404 handling' do

  subject.post :hello do
    'Hello World'
  end

  subject.route :any, '*path' do
    error! :not_found, 404
  end

  options '/hello'

  expect(last_response.status).to eql 204
  expect(last_response.body).to be_blank
end
```

Output

```
Failure/Error: expect(last_response.status).to eql 204

    expected: 204
    got: 404
```

Changing the method to `route [:get, :post, :put, :delete], '*path'` is a workaround. But it was definitely unexpected behavior for me. The README seems to suggest that an OPTIONS route is created along with the declared route, leading one to believe it would also take precedence over the 404 handling route as well.

**Comment by dblock** [comment]
I think this is a bug.

**Comment by arempe93** [comment]
Closing - fixed by #1263

**Comment by dblock** [comment]
@arempe93 I have reverted the fix committed in #1263 via https://github.com/ruby-grape/grape/commit/5aa655406398e547f16e32f3f1327a3f8248c820. See https://github.com/ruby-grape/grape/issues/1307 for details. Now we have specs on master for behavior that was regressed.

**Comment by dblock** [comment]
The solution is probably not to create dynamic routes for other HTTP verbs, but to be able to say "the API has a set of matching routes", "do any match the verb", if yes, execute, otherwise generate a 405. Maybe we can do that part of #1276?

**Comment by dblock** [comment]
This is likely fixed in https://github.com/ruby-grape/grape/pull/1276, care to followup on this @arempe93 ? Thanks.

**Comment by arempe93** [comment]
Yes I can take a look on the edge version soon

**Comment by dblock** [comment]
Bump @arempe93.

**Comment by namusyaka** [comment]
Fixed in https://github.com/ruby-grape/grape/commit/9f4ba67d4aca90f04a65c5ff921b1687942eb99c.  I've just confirmed that.
