### ISSUE TITLE
Param versioning param key isn't set using version options

### ISSUE THREAD

**Issue by wshatch** [ruby-grape/grape#1270]
As stated in the docs, setting parameter for the param strategy like so 
```ruby
version 'v1', using: :param, parameter: 'v'
```
Won't work since the param strategy is looking in ```@options``` instead of ```@options[:version_options]```

**Comment by mneumark** [comment]
Just tried the same thing and had the same issue.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1271.
