### ISSUE TITLE
Code Organization and Entities Code Placements and Versioning

### ISSUE THREAD

**Issue by yoonwaiyan** [ruby-grape/grape#1284]
I'm configuring my Rails app to support multiple API versions. I have my api structure like this for now:
```
├── app/
│   ├── api
│   │   ├── api
│   │   │   ├── v1
│   │   │   │   ├── categories.rb
│   │   │   │   ├── customers.rb
│   │   │   │   ├── root.rb
│   │   │   ├── v2
│   │   │   │   ├── customers.rb
│   │   │   │   ├── root.rb
│   │   │   ├── root.rb
...
```

```ruby
# api/api/root.rb
require 'grape-swagger'
require 'v1/root.rb'
require 'v2/root.rb'

module Api  
  class Root < Grape::API
    mount Api::V2::Root
    mount Api::V1::Root
  end
end
```

```ruby
# api/api/v1/root.rb
require 'grape-swagger'

module Api  
  module V1
  class Root < Grape::API
    prefix 'blabla/api'
    version ['v2', 'v1'], using: :param
    format :json

    mount Api::V1::Categories
    mount Api::V1::Coupons

    add_swagger_documentation api_documentation: { desc: 'Reticulated splines API swagger-compatible documentation.', hidden: true }
  end
end
end
```

```ruby
# api/api/v2/root.rb
require 'grape-swagger'

module Api 
  module V2 
    class Root < Grape::API
      prefix 'blabla/api'
      version 'v2', using: :param
      format :json

      mount Api::V2::Customers
    end
  end
end
```

I didn't use [grape-transformations gem](https://github.com/codescrum/grape-transformations) to structure my code, but I don't know what's the best way to put my Entities classes without scattering them above each API class. For example: 
```ruby
# api/api/v1/categories.rb
require 'grape-entity'

module Api::V1
  module Entities
    class Category < Grape::Entity
      expose :description
      expose :id
      expose :name
      expose :thumbnail
    end
  end

  class Categories < Grape::API
    resource :categories do
      desc "List all Categories"

      get do
        categories = Category.all
        present data: Api::V1::Entities::Category.represent(categories)
      end

    end
  end
end
```

Few months ago, I've tried different types of way to locate my entities by separating it into files, created one `/entities` directory, which all of them don't work(method/class not found error etc, because my Category entity were not defined in other classes before mounting Api::V1::Categories, etc). Now the codebase is building up fast so I'll have to re-organize my entities to different files within a directory, perhaps under `api/api` so that other versions of API can use the same entities as well. How to organize the Entities in such way?

By the way, for `swagger_doc` how do I configure such that one Swagger API displays both v1 and v2 documentation in one Swagger UI, or can different versions of API documentation displays in different routes? I tried put `swagger_doc` in both root files of v1 and v2, but only v2 documentation loaded up.

**Comment by yoonwaiyan** [comment]
I'm still doing the versioning configurations. I've been following your [blog](http://code.dblock.org/2013/07/19/evolving-apis-using-grape-api-versioning.html) and I made it work when params are passed, but how do I configure it such that the default API version is still v1? Because this API is used for mobile application development, so the API have to be backward compatible with the previous versions of mobile app, which they don't provide extra parameter while sending request.

**Comment by dblock** [comment]
You should bring separate questions up on the mailing list, please. I'll close this.

* Swagger doesn't support the same UI over different APIs, versions are very much different APIs. I am sure you can build a custom UI that points to two different swagger doc endpoints with a bit of work if you want to let users switch.

* You want v1 to be the default and explicitly select v2? I wonder whether the easiest way is to inject a default Accept header in a middleware, not sure.
