### ISSUE TITLE
Array of Hash with optional fields gets squashed 

### ISSUE THREAD

**Issue by reynardmh** [ruby-grape/grape#1293]
```ruby
  params do
    optional :fields, type: Array do
      optional :field1, type: Integer
      optional :field2, type: Integer
      optional :field3, type: Integer
    end
  end
  get '/' do
    params.to_json
  end
```

running rspec test  with the following input
```ruby
it 'does not work' do
  get '/', fields: [ { field1: 1 }, { field2: 2 }, { field3: 3 } ]
  ap JSON.parse(last_response.body)
end
```

produces this result
```
{
    "fields" => [
        [0] {
            "field1" => 1,
            "field2" => 2,
            "field3" => 3
        }
    ]
}
```

Basically it squashes the array into just one element when the previous element is missing the optional field from the next element. 

I'd like to contribute a fix if someone can point me to where in the codebase I should start looking.

**Comment by reynardmh** [comment]
I've created a sample app demonstrating this bug

https://github.com/reynardmh/grape-bug-demo

**Comment by dblock** [comment]
Interesting. Assuming this is happening on HEAD too?

**Comment by reynardmh** [comment]
This was on 0.14. I will test this on HEAD.

**Comment by reynardmh** [comment]
Yes this is happening on HEAD (at master@df3e4ae)

**Comment by dblock** [comment]
I am not sure this is a real problem, how do you pass this GET data with, say, `curl`? If you're POSTing JSON data that's a whole different story.

**Comment by reynardmh** [comment]
by not a real problem, you mean it's not possible to create such HTTP request? 
btw, this is happening for post request as well.

**Comment by reynardmh** [comment]
I think I see what you mean, so if we are just using post data, the array has to be passed like this:
```
curl http://localhost:9292/post -d "fields[][field1]=1&fields[][field1]=2"
```
It makes sense that it creates an array with single element containing field1 and field2. I'm guessing this happens outside of Grape (like in Rack request parser?).

So we need to do something like this, its better to just send JSON data as the params?

**Comment by dblock** [comment]
Right, you can't actually pass an array of hashes via a GET request and in a `POST` that defaults to a single hash of fields (it's ambiguous to humans, but should be very clear per HTTP RFC, although I haven't checked).

So if you need to do something like this you actually don't have a choice I believe, since the only way this is supported is by using a different data format (eg. JSON).

If you agree I think this should be closed, there's nothing we can do about this in Grape.

**Comment by reynardmh** [comment]
Thanks, that makes sense. I agree that we should close this.
