### ISSUE TITLE
What should rescue_from block return ?

### ISSUE THREAD

**Issue by guizmaii** [ruby-grape/grape#1300]
The documentation says that:
`The rescue_from block must return a Rack::Response object, call error! or re-raise an exception.`

but if we use the `rescue_from` method only to log things and we want to keep the original HTTP answer what should we return ?

If I rethrow the catched exception, it does not keep the original behavior. 
For example, some of my tests generate `400` responses but with: 
```ruby
  rescue_from :all do |e|
    Rails.logger.error(e)
    raise e
  end
```

They catch `500` responses.

The better solution I found to reproduce the original behavior is this code:

```ruby
  rescue_from :all do |e|
    Rails.logger.error(e)
    if e.respond_to?(:status)
      error!(e.to_json, e.status, e.headers, e.backtrace)
    else
      error! "Internal Server Error"
    end
  end
```

I should check if the catched exception responds to `status` because it could be a RuntimeError for example, and RuntimeError does not answer to `status`.

Am I doing this right ? Or there is a better solution to do that ?

**Comment by guizmaii** [comment]
I also posted the question here : http://stackoverflow.com/questions/35718873/what-should-return-the-grape-rescue-from-all-block

**Comment by railsmith** [comment]
Check out this conversation [#939](https://github.com/ruby-grape/grape/pull/939#issuecomment-75948772)

**Comment by dblock** [comment]
Just for reference, the solution in #939 that @railsmith points is right, catch only things you want to catch, ie.`Grape::Exceptions::Validation` and `Grape::Exceptions::ValidationErrors`. But generally for a logger I suggest using a middleware instead. 

I'm going to close this, lmk if it needs any other action.
