### ISSUE TITLE
Path version ignored

### ISSUE THREAD

**Issue by przbadu** [ruby-grape/grape#1305]
related with https://github.com/ruby-grape/grape/issues/133

`grape v 0.13.0 and v 0.14.0`

Hi, I guess it is still reproducing. I am using https://github.com/ruby-grape/grape#path versioning with prefix 'api'

```ruby
# api.rb

prefix          'api'
version         ['v2', 'v1']
format          :json
default_format  :json

mount V2::Domain::API
mount V1::Domain::API
```

`/api/v1/passwordless/request_validation?`

The requests above always returns "v2" regardless of the`path` being set, and all V2 test cases passes, but v1 test cases broken.

I tried with grape version `0.13.0` and `0.14.0`

Thanks

**Comment by przbadu** [comment]
well!

deleting:

`version         ['v2', 'v1']` from `api.rb` and moving them into:

```ruby
class V1::Domain::API < Grape::API
  version  'v1'

  .....
end
```

```ruby
class V2::Domain::API < Grape::API
  version   'v2'

  .....
end
```

Fixed my problem :smile:

**Comment by dblock** [comment]
Right, the first syntax is not something that actually exists, it cannot guess that v1 is actually the `V1` namespace by convention.

If you think the documentation is confusing, please do contribute an update.

**Comment by przbadu** [comment]
@dblock : right, I think we can update documentation for this.
