### ISSUE TITLE
Custom Validation  not working with an optional parameter

### ISSUE THREAD

**Issue by brahamshakti** [ruby-grape/grape#1310]
Hi, My custom validation is not executing if my parameter is optional. e.g

    class AlphaNumeric < Grape::Validations::Base
        def validate_param!(attr_name, params)
            unless params[attr_name] =~ /\A[[:alnum:]]+\z/
                fail Grape::Exceptions::Validation, params: [@scope.full_name(attr_name)], message: 'must consist of alpha-numeric characters'
            end
        end
    end

This does not work if i write this

    params do
        optional :text, alpha_numeric: true
    end

Any suggestion?

**Comment by dblock** [comment]
Are you passing a value for `:text`? I believe this is by design not to call the validator if you don't supply an optional parameter. Otherwise make the parameter required.

Reopen if I am missing something.

**Comment by hguerrerojaime** [comment]
How about making the value required depending on the value of other parameter?
