### ISSUE TITLE
optional :str_time, type: String, default: Time.now.to_s

### ISSUE THREAD

**Issue by guoyoujin** [ruby-grape/grape#1319]
When I use the following syntax when I found time default setting has been my successful deployment of that time , since he has been a constant  

`
optional :str_time, type: String, default: Time.now.to_s`

**Comment by dblock** [comment]
This code is evaluated at load time of the .rb file, use a proc:

```ruby
optional :str_time, type: String, default: -> { Time.now.to_s }
```
