### ISSUE TITLE
params only grabs the last hash of array in request body

### ISSUE THREAD

**Issue by StevenJL** [ruby-grape/grape#1322]
When I make a put request to a grape endpoint with the following params block

```ruby
params do
  requires :products, type: array do
    requires :product
    requires :variant
  end
end
```

and then make a put request with the following body

```ruby
products: [ 
  { product: {id: 1}, variant: {id: 80, quantity: 1}},
  {product: {id: 2}, variant: {id: 4, quantity: 2}}, 
  {product: {id: 3}, variant: {id: 4, quantity: 1}} 
]
```

The params only grabs the last hash

```ruby
params => {"products"=>[{"product"=>{"id"=>"3"}, "variant"=>{"id"=>"4", "quantity"=>"1"}}]}
```

Anyone seen this before?

**Comment by StevenJL** [comment]
typo, so closing and creating new.

**Comment by dblock** [comment]
What content-type? Try to write this in a spec maybe?

**Comment by StevenJL** [comment]
Looking at the project, I see its on grape 0.7.0.  I can't verify this is broken for the latest version of grape so closing.  Thanks for the quick response though!
