### ISSUE TITLE
Header version ignored

### ISSUE THREAD

**Issue by pduersteler** [ruby-grape/grape#133]
This may be similiar to #124 and #74

According to several slides and docs and wiki pages, I tried this:

``` ruby
version 'v2', :using => :header, :strict => true, :vendor => 'test'

resource :test do
    get :first do
        "v2"
    end
end


version 'v1', :using => :header, :strict => true, :vendor => 'test'

resource :test do
    get :first do
        "v1"
    end
end
```

```
curl -H Accept=application/vnd.test-v1+json http://test.localhost.example:3000/api/test/first
curl -H Accept=application/vnd.test-v2+json http://test.localhost.example:3000/api/test/first
```

The requests above always returns "v2" regardless of the header being set. I also tested those without using the `strict` param, but got the same results.

**Comment by przbadu** [comment]
Hi, it is still reproducing for me. I am using default(path) versioning with prefix 'api'

```ruby
prefix          'api'
version         ['v2', 'v1']
format          :json
default_format  :json

mount V2::Domain::API
mount V1::Domain::API
```

`/api/v1/passwordless/request_validation?`

The requests above always returns "v2" regardless of the`path` being set, and all V2 test cases passes, but v1 test cases broken.

I tried with grape version `0.13.0` and `0.14.0`

Thanks
