### ISSUE TITLE
Writing Tests with Rails, RSpec and specific Headers

### ISSUE THREAD

**Issue by guizmaii** [ruby-grape/grape#1340]
Hi,

I have a app written with "Grape (0.15.0) on Rails (3.2.22.1)".
The documentation say I can write tests like that:
```ruby
describe Twitter::API do
  context 'GET /api/statuses/public_timeline' do
    it 'returns an empty array of statuses' do
      get '/api/statuses/public_timeline'
      expect(response.status).to eq(200)
      expect(JSON.parse(response.body)).to eq []
    end
  end
  context 'GET /api/statuses/:id' do
    it 'returns a status by id' do
      status = Status.create!
      get "/api/statuses/#{status.id}"
      expect(response.body).to eq status.to_json
    end
  end
end
```

It works well. I use this kind of tests since months.
But now, my API should take a specific header, for exemple `HTTP_TOKEN`
So, I change my tests like this:

```ruby
describe Twitter::API do
  context 'GET /api/statuses/public_timeline' do
    it 'returns an empty array of statuses' do
      get '/api/statuses/public_timeline', nil, { 'HTTP_TOKEN' => "a_token" }
      expect(response.status).to eq(200)
      expect(JSON.parse(response.body)).to eq []
    end
  end
  ...
end
```

Because the `get` method come from `ActionDispatch::Integration::RequestHelpers` and its signature is : `get(path, parameters = nil, headers_or_env = nil)`. (More infos: http://api.rubyonrails.org/classes/ActionDispatch/Integration/RequestHelpers.html#method-i-get)

But in my endpoint code, the `headers` hash does not contain my `HTTP_TOKEN` header. 
My header is in the `env` hash instead.

On the other hand, if I manually test my endpoint with any HTTP client, my `HTTP_TOKEN` header is correctly in the `headers` hash and not in the `env` hash.

Any idea on how to fix this ?

**Comment by dblock** [comment]
Are you sure that you're not getting a `token` header inside `headers`? There was something about `ENV` needing to prefix HTTP headers with `HTTP_`, but I could be totally wrong. 

Next step is to write a failing spec in Grape for this.

**Comment by guizmaii** [comment]
Ok.

I found the problem and the solution.

I my real app my header is not `HTTP_TOKEN`. My key does not begin with `HTTP`. It was only for example.

I don't know why, but headers in Grape (and Rails ?, because of Rake ?) are prefixed with `HTTP_` in the `env` hash.
To get the headers, it loops over the `env` hash, if the key begin with `HTTP_`, it removes the prefix and adds the key/value pair to the `headers` hash, see the code:

```ruby
# Come from Grape::Request

def build_headers
   headers = {}
   env.each_pair do |k, v|
     next unless k.to_s.start_with? HTTP_PREFIX

     k = k[5..-1].split('_').each(&:capitalize!).join('-')
     headers[k] = v
   end
   headers
end
```

So, the solution is, for a header named for example `Api-Key`, to write your tests like this :

```ruby
describe Twitter::API do
  context 'GET /api/statuses/public_timeline' do
    it 'returns an empty array of statuses' do
      get '/api/statuses/public_timeline', nil, { 'HTTP_API_KEY' => "a_token" }
      expect(response.status).to eq(200)
      expect(JSON.parse(response.body)).to eq []
    end
  end
  ...
end
```

Because you prefixed your header name with `HTTP_` Grape will effectively consider it as a header, and you will be able to consult the value in the normal way: `headers['Api-Key']` or via the `env`: `env['HTTP_APi_KEY']`

Thanks for the fast answer @dblock !

**Comment by dblock** [comment]
It's part of the Rack spec, documented in http://rack.rubyforge.org/doc/SPEC.html.
