### ISSUE TITLE
Release 0.15.1 (or 0.16.0)

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1341]
I think we should be releasing 0.15.1 (or 0.16.0?) soon, there's no need to have the new router just sit here. Want to give it a shot @namusyaka? We have a [well documented process](https://github.com/ruby-grape/grape/blob/master/RELEASING.md).

**Comment by namusyaka** [comment]
@dblock Yeah, I agree that releasing 0.15.1.  Should I check out 0.15.1 branch to skip commits of new router?

**Comment by dblock** [comment]
I would rather just see a 0.16.0 release with all the new stuff.

**Comment by namusyaka** [comment]
:+1:

**Comment by namusyaka** [comment]
@dblock I've released 0.16.0. Thanks for giving me the chance.
Could you tweet this news as a grapeframework account?

**Comment by mrueg** [comment]
@namusyaka  can you push a tag for it please?

**Comment by namusyaka** [comment]
@mrueg Done. Thanks.
