### ISSUE TITLE
Extract router to a gem?

### ISSUE THREAD

**Issue by maclover7** [ruby-grape/grape#1342]
It's awesome that Grape was able to switch off of `Rack::Mount` to a in-tree router solution! However, many other Ruby web frameworks (ex: Hanami/Lotus) are also still using fairly unmaintained libraries like `http_router` among others. Does it make sense to extract Grape's router to a gem that can be used and shared by all? Does it make sense to refactor Grape's router further to use Rails' router, Journey?

cc @dblock

**Comment by dblock** [comment]
That's basically https://github.com/namusyaka/pendragon, isn't it? /cc: @namusyaka. 

Journey has been merged into Rails. The last thing we want is to add a Rails dependency, that'd be awkward :)

**Comment by namusyaka** [comment]
Yes, The concept of pendragon is same with new router, but new router is optimized for Grape.
If you wish to use grape router in other projects, I'm going to update and refactor pendragon.
Thanks!

**Comment by dblock** [comment]
I'm going to close this, it's beyond Grape's scope.
