### ISSUE TITLE
0.16.0 fail to install on ruby 2.2.4 on windows x64

### ISSUE THREAD

**Issue by net1957** [ruby-grape/grape#1343]
on windows 8.1 x64:

gem -v
2.6.2
ruby 2.2.4p230 (2015-12-16 revision 53155) [x64-mingw32]
````
gem update

Updating installed gems
Updating grape
Fetching: enumerable-lazy-0.0.1.gem (100%)
Successfully installed enumerable-lazy-0.0.1
Fetching: mustermann19-0.4.3.gem (100%)
Successfully installed mustermann19-0.4.3
Fetching: grape-0.16.0.gem (100%)
ERROR:  While executing gem ... (Errno::EINVAL)
    Invalid argument @ rb_sysopen - D:/program/dvlt/ruby/ruby22-x64/lib/ruby/gems/2.2.0/gems/grape-0.16.0/:wq
````

remark: mustermann19 exist for ruby 1.9 compatibility. but here we are on ruby 2.2.4

any idea ?

**Comment by namusyaka** [comment]
Gosh... The problem is my bad. It is including unnecessary files.
So I've yanked the releasing. Please waiting for me.

**Comment by namusyaka** [comment]
I've released 0.16.1. Please use it instead of 0.16.0.
Sorry for the inconvinience.

**Comment by net1957** [comment]
install fine but not tested. Thanks

**Comment by namusyaka** [comment]
Thanks.
Please let us know if you still have a problem.
