### ISSUE TITLE
Deprecated route_xxx methods for route_params and route_? declared.

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1344]
I've PRed https://github.com/ruby-grape/grape-swagger/pull/368, but it has two problems, access to `route_params` and `route_hidden` in a dummy API declared as `GET '/foobar', hidden: true`. 

The `route_xxx` deprecated code reaches into `@options`, which isn't `@settings`, and that is no longer exposed. So `.params` is not the same thing as the old `route_params`. What should we do about this one?

**Comment by dblock** [comment]
cc: @namusyaka, maybe you have a suggestion?

**Comment by namusyaka** [comment]
@dblock Hmm, I think the `route_xxx` can explore the `@options` and `@settings` in a cascading style.
I'm going to investigate the problem in a few days.

**Comment by dblock** [comment]
If you have time @namusyaka, the simplest thing to look at is https://github.com/dblock/grape-swagger/tree/fix-deprecations, try to fix the remaining deprecations. I think the simplest would be to just expose `options`, but maybe the specs are wrong and it's not the right thing to do.

**Comment by dblock** [comment]
For now I am monkey-patching the deprecation to avoid too many warnings being spewed.

```ruby
module Grape
  class Router
    class Route
      private

      # TODO: remove when https://github.com/ruby-grape/grape-swagger/pull/368 and https://github.com/newrelic/rpm/pull/235 are finished
      def warn_route_methods(name, location, expected = nil)
      end
    end
  end
end
```

**Comment by dblock** [comment]
Closing via #1357.

**Comment by dblock** [comment]
https://github.com/newrelic/rpm/pull/282
