### ISSUE TITLE
grape-entity 0.5.1 breaks http_codes spec

### ISSUE THREAD

**Issue by niedhui** [ruby-grape/grape#1354]
With [this commit](https://github.com/ruby-grape/grape-entity/commit/ae279de45227800170acc52c2456ab466a074df5), which introduce `Grape::Entity::Exposure::NestingExposure::OutputBuilder`, it break `spec/grape/api_spec.rb:2034`, the [txt error formatter](https://github.com/ruby-grape/grape/blob/master/lib/grape/error_formatter/txt.rb#L10) using `is_a?(Hash)` to test whether the response body need to cast to JSON, which here becomes `OutputBuilder`, a SimpleDelelator for Hash.

**Comment by dblock** [comment]
This is a dup of https://github.com/ruby-grape/grape/issues/1350, right? Would love a fix in the right place.

**Comment by niedhui** [comment]
right, dup of #1350
