### ISSUE TITLE
Scoping nested resources

### ISSUE THREAD

**Issue by Morred** [ruby-grape/grape#1367]
I'm trying to scope a resource within another resource, like this:

```
class API
  module Resources
    class OperatingSystems < Grape::API

      resource :operating_systems do

        route_param :id do

          resource :operating_system_versions do

            # LIST
            desc 'List Operating Systems'
            get do
              operating_system_versions = OperatingSystemVersion.where(operating_system_id: params[:id])
              present(operating_system_versions, with: API::Entities::OperatingSystemVersion)
            end

            route_param :id do

              # SHOW
              desc('Get an Operating System Version')
              get do
                # How do I scope an operating system version under the operating system?
                present(operating_system_version, with: API::Entities::OperatingSystemVersion)
              end
            end
          end
        end
      end

    end
  end
end
``` 

The LIST option for operating system versions works without problems because I can just refer to params[:id] and get the operating system ID. However, once I'm within the second route_param :id which refers to the id of the operating system version, I can no longer access the previous one, i.e. the one that refers to the operating system. My goal is to make sure that the operating system version is only returned if it actually belongs to this operating system.

Is there a way to properly scope the operating system version under the operating system, automatically (built into Grape) or manually (by somehow accessing the operating system id param and scoping within the show action)?

**Comment by dblock** [comment]
It sounds like you just want to call these `:id` params differently, no?

**Comment by dblock** [comment]
I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by Morred** [comment]
Well that was easy 😁 For some reason I was under the impression that the route params *have* to be called :id, I'm not even sure why. Thanks!
