### ISSUE TITLE
Camel case params

### ISSUE THREAD

**Issue by danieldraper** [ruby-grape/grape#1368]
Hi - Curious on recommendations for using lower camel case for request params but map them to snake case for the model? I am using Roar for representing the response so no issues here just the incoming. Could not find this documented anywhere. 

```ruby
desc "Create an user"
params do
  requires :first_name, as: :firstName, type: String
end
```

**Comment by dblock** [comment]
Do you mean how to do it? I'll close this though. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
