### ISSUE TITLE
How to allow empty array for params?

### ISSUE THREAD

**Issue by qsona** [ruby-grape/grape#1370]
I wrote the following code.
```
params do
  requires :items, type: Array[JSON] do
    requires :id, type: Integer
    requires :enabled, type: Boolean
  end
end
post '/' do
# ...
```
A request with following params succeeds
`{ items: [{ id: 1, enabled: true }, { id: 2, enabled: false }] }`

But fails with following.
`{ items: [] }`

I changed the code to
```
params do
  optional :items, type: Array[JSON] do
```

But, all requests failed then.

I want to allow `{ items: [] }` params. Is there any way to do it?

Thanks.

**Comment by dblock** [comment]
If you're POSTing JSON, I believe this just works. Care to share the code that does the POSTing?

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by liquid1982** [comment]
I have the same problem, and can't figure out what a possible solution could be. It just seems a buggy behaviour. I need to allow the user to publish an article, and optionally specify a section. I also need to accept an empty array, that will result in unpublishing the article from the specified domain.

The non-working code is the following:

```rb
desc 'Publish an article'
params do
  optional :published_in, type: Hash do
    optional :'foo.com', type: Array[String], values: ALLOWED_SECTIONS['foo'], allow_blank: true
    optional :'bar.com', type: Array[String], values: ALLOWED_SECTIONS['bar'], allow_blank: true
  end
end
post 'articles/123/actions/publish' do
  # ...
end
```

But if I omit the `values` param, things work as expected:


```rb
desc 'Publish an article'
params do
  optional :published_in, type: Hash do
    optional :'foo.com', type: Array[String], allow_blank: true
    optional :'bar.com', type: Array[String], allow_blank: true
  end
end
post 'articles/123/actions/publish' do
  # ...
end
```

I'd like to specify the allowed values in the params block. Any suggestion?

**Comment by dblock** [comment]
What is the posting code? What content-type is it POSting @liquid1982 ?

**Comment by liquid1982** [comment]
@dblock It is something like:

```js
    $.ajax({
      url: url,
      method: 'POST',
      contentType: 'application/json',
      data: JSON.stringify(options.data)
    }).then(() => {})
```

**Comment by dblock** [comment]
You should turn it into a spec @liquid1982 in this project.
