### ISSUE TITLE
Nested params mixing

### ISSUE THREAD

**Issue by mkou** [ruby-grape/grape#1388]
I have a strange error, whenever I POST the parameters 
````
{ a: [ {  b: 'foo', c: 'bar' }, { d: 'foo2', c: 'bar' }]
```
I get the wrong params value in my api
```
{ "a"=>[{"b"=>"foo", "c"=>"bar", "d"=>"foo2"}, {"c"=>"bar"}]}
```

**Comment by dblock** [comment]
Are you POSTing content-type JSON or doing this in a spec? This is not something you can post as a query string with curl for example.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by mkou** [comment]
I created a test https://github.com/ruby-grape/grape/pull/1389 to show what my issue is
