### ISSUE TITLE
Ability to stream entities

### ISSUE THREAD

**Issue by raulpopadineti** [ruby-grape/grape#1392]
Hi,

We'd like to build an API that is able to paginate entities and send them in chunks. 

A really raw way of sending data in chunks would be:

```
require 'grape'

module Stream
  class API < Grape::API
    prefix 'api'
    format :txt
    default_format :txt

    class Streamer
      def initialize(pages:, page_size:, latency:)
        @pages = pages
        @page_size = page_size
        @latency = latency
      end

      def each
        (1..@pages).lazy.each do |p|
          yield "#{p}\n" * @page_size
          sleep(@latency)
        end
      end
    end

    resources :users do
      params do
        optional :pages, type: Integer, default: 10
        optional :page_size, type: Integer, default: 10
        optional :latency, type: Float, default: 1.0
      end

      get do
        status 200
        p = declared(params)
        stream Streamer.new(pages: p.pages, page_size: p.page_size, latency: p.latency)
      end
    end
  end
end
```

With this approach I get the deprecation warning:

`[DEPRECATION] Argument as FileStreamer-like object is deprecated. Use path to file instead.`

because Grape assumes the response is a file.

Will you support streaming of a `Grape::Entity` or any other non-file objects in the future?

**Comment by dblock** [comment]
I think the deprecation is just for files. It's still supporting a pure streaming interface. You should look at the code a bit more in depth and see what's missing? Generally I don't see why we wouldn't want this, so I'll leave this open.

**Comment by lfidnl** [comment]
Hello. I guess, now `stream` method can stream only files. Maybe we should to do:
1. Add option `stream: true` to `file` method. This option will replace current `stream` method.
2. Rewrite `stream` method in such a way that it can receive object which respond to `each` method and streams it.

**Comment by raulpopadineti** [comment]
I've managed to stream JSON by polishing a bit on the `Streamer` class I added:

```
```

**Comment by lfidnl** [comment]
@raulpopadineti one question: is it works now with deprecation warning, or not?

**Comment by raulpopadineti** [comment]
@lfidnl it works with deprecation warning.

**Comment by lfidnl** [comment]
@raulpopadineti good, I think, @dblock should approve my suggestion and someone can create PR for fix this issue :)

**Comment by dblock** [comment]
I think what you suggest is sensible, would like to see a PR.

**Comment by raulpopadineti** [comment]
@dblock to which solution are you referring?

**Comment by dblock** [comment]
I meant what @lfidnl says. But you're all looking at code, I suggest trying something and PRing it.

**Comment by Cabbit** [comment]
For those interested that may use JSON API, i have took the ideas here and built a basic gem https://github.com/Cabbit/grape_json_api_streamer for grape that i'll expand upon as my projects get more complex.

**Comment by dblock** [comment]
@Cabbit contribute that to http://www.ruby-grape.org/projects/ pls.

**Comment by dm1try** [comment]
fixed in the referenced PR
