### ISSUE TITLE
Ability to fail fast on params validation

### ISSUE THREAD

**Issue by akozhemiakin** [ruby-grape/grape#1423]
Correct me if I'm wrong, but currently all validators will be executed even if some of them fails during the validation process. I believe this is the corresponding code chunk, showing the nature of this behavior:
```ruby
def run_validators(validators, request)
  validation_errors = []

  validators.each do |validator|
    begin
      validator.validate(request)
    rescue Grape::Exceptions::Validation => e
      validation_errors << e
    end
  end

  validation_errors.any? && raise(Grape::Exceptions::ValidationErrors, errors: validation_errors, headers: header)
end
```

I believe that it should be possible to instruct Grape to fail fast during the validation process.

One possible case: We need to validate that some string matches some pattern (for example it is an email) and than we need to validate if this email is in the white list. For now even if this email is malformed, it will be checked against the white list (which has no sense cause it is malformed anyway).

The DSL may look like this:
```ruby
params do
  requires :email, allow_blank: false, regexp: /@/, fail_fast: true
end
```

**Comment by dblock** [comment]
I like this idea as long as we ensure the validation order.

**Comment by connorshea** [comment]
Is this resolved now?

**Comment by dgasper** [comment]
Yes, should probably be closed.

**Comment by dblock** [comment]
Closing via #1499.
