### ISSUE TITLE
OPTIONS method for namespaced GET does not call inner before filter

### ISSUE THREAD

**Issue by jlfaber** [ruby-grape/grape#1428]
When I use a namespace to define a GET method, and I add a before filter within the namespace block, that filter is called when GET executes, but is not called when OPTIONS executes.  This differs from the behavior when the GET and before filter are not within a namespace.  In that case, the before filter is called both for GET and OPTIONS.

I'll add a PR with a failing test spec to demonstrate the issue.

**Comment by dblock** [comment]
Yep, looks like a bug.

**Comment by namusyaka** [comment]
I'm going to fix it in a few days. Thanks for the report.
