### ISSUE TITLE
How to handle exception in grape, if database connection is null or access denied.

### ISSUE THREAD

**Issue by navnathkarche-tudip** [ruby-grape/grape#1432]

**Comment by dblock** [comment]
You can let the error bubble up and it will be returned with details in the format your API is. Or use `rescue_from` for something more specific.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by navnathkarche-tudip** [comment]
ok
