### ISSUE TITLE
Files becomes a String

### ISSUE THREAD

**Issue by Extazystas** [ruby-grape/grape#1435]
Hello. I'm sending file to Grape API with this code:
```
Faraday.new(endpoint) do |conn|
        conn.response :logger unless Rails.env.test?
        conn.response :json, content_type: /\bjson$/ unless response_type != :json
        conn.request :multipart
        conn.request :url_encoded
        conn.adapter :net_http
end
```
I'm setting file for connection this way:
```
...
Faraday::UploadIO.new(
          file.tempfile.path,
          file.content_type,
          file.original_filename
        )
...
```
And it works because I can see this object in params before sending a request:
```
#<UploadIO:0x007f87ac578d58 @content_type="image/jpeg", @original_filename="sQF5wS0qaV8.jpg", @local_path="/tmp/RackMultipart20160705-8019-18ryl1x.jpg", @io=#<File:/tmp/RackMultipart20160705-8019-18ryl1x.jpg>, @opts={}>
```
But on a client incoming params does not contain a File, its a plain string like that:
`"#<UploadIO:0x007f87ac578d58>"`

I tried to debug grape from `Endpoint#run` method but `@params` already has a String instead of File here. I can successfully upload file with Swagger, but not with Faraday. 
Any ideas why its happening?

**Comment by dblock** [comment]
You might want to try the mailing list.

**Comment by dblock** [comment]
Since this has everything to do with Faraday and is unlikely a bug, closing.
