### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by krazedkrish** [ruby-grape/grape#1437]
Hi! Guys,

People are saying Grape is Great. I have been wanting to use grape for myself as well. I am just wondering if the latest version of grape is compatible with rails 5.

thanks,

PS: thanks for the wonderful gem. :+1:

**Comment by dblock** [comment]
I'm turning this into a feature request to add Rails 5 into https://github.com/ruby-grape/grape/blob/master/Appraisals and make sure everything works. I don't see why it wouldn't, but you never know. Please feel free to contribute!

**Comment by krazedkrish** [comment]
:+1: 

Thanks I am starting to grape with rails-5, I will try my best contributing to this community.

:smiley:

**Comment by connorshea** [comment]
Also interested in this ^_^

rack-mount would be the only blocker I know of, but since it's removed that won't be a problem.

**Comment by dblock** [comment]
It's like @namusyaka read the future :)

**Comment by connorshea** [comment]
@dblock This might be the only change that I can find that would effect grape: https://github.com/rails/rails/commit/adfab2dcf4003ca564d78d4425566dd2d9cd8b4f

Based on [the research I've done for upgrading GitLab](https://gitlab.com/gitlab-org/gitlab-ce/issues/14286#note_12833875).

**Comment by krazedkrish** [comment]
@connorshea your research has been a great help for me.

:smile_cat:

**Comment by connorshea** [comment]
@krazedkrish that was the hope :) Glad to hear it's useful to others!

**Comment by dblock** [comment]
So where's my PR?! ;)

**Comment by glaucocustodio** [comment]
I've opened a PR for Rails 5 compatibility (https://github.com/ruby-grape/grape/pull/1456). We have 2 tests failing. Does anybody have a clue?

**Comment by glaucocustodio** [comment]
All tests are passing with Rails 5 now (https://travis-ci.org/ruby-grape/grape). I think we can close this issue now /cc @dblock @krazedkrish.

**Comment by dblock** [comment]
Yes, closing via https://github.com/ruby-grape/grape/pull/1464
