### ISSUE TITLE
activesupport 5.0.0 breaks CI tests

### ISSUE THREAD

**Issue by jlfaber** [ruby-grape/grape#1440]
Seeing these errors on ruby versions below 2.2.2:

> Gem::InstallError: activesupport requires Ruby version >= 2.2.2.
> An error occurred while installing activesupport (5.0.0), and Bundler cannot continue.
> Make sure that `gem install activesupport -v '5.0.0'` succeeds before bundling.

Looks like grape was picking up 4.2.6 prior to June 30 when 5.0.0 came out.

There's no version currently listed for activesupport in grape.gemspec.  Perhaps it should be changed to this?

`  s.add_runtime_dependency 'activesupport', '~> 4.2'`

**Comment by jlfaber** [comment]
Using ~> 4.2 didn't work since rails actually uses older versions of activesupport.  Trying again with < 5.0.0.

**Comment by jlfaber** [comment]
That seems to have fixed it.  I'll force-push a revision to add a CHANGELOG line and correct the commit message, then I think this is good to go.  (Assuming everyone is ok with holding off on taking activesupport 5.0.0 for now.)

**Comment by dblock** [comment]
Just bringing my comment from #1441, lets not restrict grape to AS 4.x, but fix the build by removing incompatible rubies.

**Comment by jlfaber** [comment]
Updated #1441 to remove pre-2.2.2 rubies and add explicit checks for 2.2.2 - 2.3.1
