### ISSUE TITLE
env and @headers not available in before block when Method not allowed

### ISSUE THREAD

**Issue by leifg** [ruby-grape/grape#1444]
Suppose you do this:

```ruby
before do
  env['Something']
end
```

In general this is possible.

However if you run into a method not allowed, not only will this block executed, it also sets `env` (and `@headers`) to `nil` and throws an error that is never caught and will expose the stacktrace to the caller.

I created an example project [here](https://github.com/leifg/grape-method-not-allowed).

**Comment by leifg** [comment]
Note: [this](https://github.com/ruby-grape/grape/blob/8d6503dd85b500792a58f14314e1d004cef9144e/lib/grape/router.rb#L141) runs the before filters in the Method not allowed context. I guess at this point `env` and `@headers` also should be initialized like it is done [in the endpoint](https://github.com/ruby-grape/grape/blob/8d6503dd85b500792a58f14314e1d004cef9144e/lib/grape/endpoint.rb#L221)

**Comment by dblock** [comment]
This looks legit, I would turn your demo into a spec and PR a fix. Thanks.

**Comment by leifg** [comment]
opened the PR: https://github.com/ruby-grape/grape/pull/1446
