### ISSUE TITLE
Replace mustermann19 with mustermann-grape

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1469]
See https://github.com/sinatra/mustermann/issues/52.

/cc: @namusyaka

**Comment by namusyaka** [comment]
If we're going to drop the support for ruby-1.9, we can use `mustermann-grape`.

**Comment by dblock** [comment]
We haven't built with 1.9 for a long time, so definitely yes.

**Comment by namusyaka** [comment]
Okay, I'll test `mustermann-grape` in my environment and send a PR.

**Comment by namusyaka** [comment]
Closed via #1470
