### ISSUE TITLE
When use given dsl, if follow block include requires :relate, type: String, values: %w(xxx yyy zzz) Will be reported to the wrong

### ISSUE THREAD

**Issue by godfox2012** [ruby-grape/grape#1476]
When use given dsl, if follow block include requires :relate, type: String, values: %w(xxx yyy zzz) Will be reported to the wrong

```ruby
params do
  requires :id, type: Integer
  optional :base_id
  given :base_id do
    requires :relate, type: String, values: %w(xxx yyy zzz)
    optional :asso, type: String
    requires :parent_type, type: String
  end
end
```
when base_id is null or blank or false, follow code will run validate and reported error: "relate does not have a valid value"
```ruby
requires :relate, type: String, values: %w(xxx yyy zzz)
```
but if that no contain values attribute:

```ruby
requires :relate, type: String
```
don't run validate and pass
why?

**Comment by godfox2012** [comment]
I'm sorry, it's my fault. when relate is null will don't run validator, ralate is '' blank will run validator

**Comment by dblock** [comment]
Right, glad you were able to sort it out!
