### ISSUE TITLE
Make allow_blank false when the type is defined

### ISSUE THREAD

**Issue by azbshiri** [ruby-grape/grape#1482]
Hey, we're working on a project and we have a lot of required parameters with their type defined but allow_blank is true by default so we should make allow_blank false for each one and that's bad (DRY). is there any option we can set to make it false when at least the type is defined or just for the requires method?

**Comment by intuxicated** [comment]
+1

**Comment by dblock** [comment]
I would take a pull request that configures global defaults for various validators.

**Comment by namusyaka** [comment]
@azbshiri @intuxicated Could you confirm [this pull request](https://github.com/ruby-grape/grape/pull/1507)?

**Comment by azbshiri** [comment]
I really appreciate your great work. I think it does the job 💯

**Comment by namusyaka** [comment]
Thanks for confirming the issue. Closed.
