### ISSUE TITLE
Values NOT allowed Validator?

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#1485]
the ```values``` validator is great for defining values for the parameter that you are allowed to have. I would like to define values that are NOT allowed for the parameter and to return an error if the value passed matches a value on the list. Is there any way to this currently? If not, I don't mind submitting a PR for this.

```values_not_allowed:```, ```exclusions```, or ```disallowed_values``` or something of that sort?

**Comment by dblock** [comment]
Maybe `except: [ ... ]` as an extension to the current values would be cleaner? Please do PR!

**Comment by dblock** [comment]
Related, I would want to support regular expressions in `values` as opposed to `regexp: ` that we do today.
