### ISSUE TITLE
Changelog is Off With Latest Merge

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#1489]
I don't think 1470 got into the last release, but it was merged as such because it was an older PR:

* [#1470](https://github.com/ruby-grape/grape/pull/1470): Drop support for ruby-2.0 - [@namusyaka](https://github.com/namusyaka).

**Comment by namusyaka** [comment]
Yep, this wrong place will be fixed by [this pull request](https://github.com/ruby-grape/grape/pull/1488)
Sorry for the inconvenience :(
