### ISSUE TITLE
Type Coercion With Lambda In Values?

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#1492]
I'm trying to combine type coercion with lambda in values validation such as: 

```
requires :type, type: Integer, values: { except: -> { [ 3, 4, 5 ] } } # real implementation would be dynamic call
```

I get however this error:
```
/Users/jonathan/code/libs/grape/lib/grape/validations/params_scope.rb:358:in `validate_value_coercion': type: Integer is incompatible with values: {:except=>#<Proc:0x007fa873aabbf8@/Users/jonathan/code/libs/grape/spec/grape/validations/validators/values_spec.rb:150 (lambda)>} (Grape::Exceptions::IncompatibleOptionValues)
```

Is there a way to use lambda for validation with type coercion? I know we can't validate beforehand that the lambda expression is going to be proper values... but I would still like the parameter passed to be casted into an Integer.

**Comment by dblock** [comment]
I think you should be able to. I say write a spec that reproduces what you want.

**Comment by jonmchan** [comment]
Here is your failing tests:

```

  context 'exclusive excepts with lambda and coercion' do
    it 'allows any other value outside excepts' do
      get '/except/exclusive/lambda/coercion', type: 'value'
      expect(last_response.status).to eq 200
      expect(last_response.body).to eq({ type: 'value' }.to_json)
    end

    it 'rejects values that matches except' do
      get '/except/exclusive/lambda/coercion', type: 'invalid-type1'
      expect(last_response.status).to eq 400
      expect(last_response.body).to eq({ error: 'type has a value not allowed' }.to_json)
    end
end
```

https://github.com/jonmchan/grape/blob/lambda_values_and_coercion/spec/grape/validations/validators/values_spec.rb#L437

**Comment by dblock** [comment]
Thanks. Marked as confirmed bug. Now that you have a test you should try to fix it!

**Comment by jonmchan** [comment]
Opensource projects.... how you so quickly suck me into contributing... ;-) 

Anyways, it looks simple enough to fix. I'm going to make it so that if ```except``` or ```value``` is a proc, the api definition validation will be skipped.

**Comment by dblock** [comment]
We love you @jonmchan. Really.

**Comment by jonmchan** [comment]
#1493 fixes this.
