### ISSUE TITLE
Please tag 0.18.0 for release

### ISSUE THREAD

**Issue by jlfaber** [ruby-grape/grape#1502]
Last tag was late July, and there have been a couple of fixes and improvements since then that I'm waiting on.
Thanks!

**Comment by dblock** [comment]
I plan to do this soon unless one of the other maintainers wants to beat me to this, please.

**Comment by dblock** [comment]
Maybe @namusyaka ? Also should we bump the version to major because we dropped old rubies support?

**Comment by connorshea** [comment]
@dblock you mean minor? Surely you wouldn't bump to 1.0.0 just for that?

**Comment by namusyaka** [comment]
@dblock @connorshea  I'm going to plan to bump version to `0.18.0`. Thoughts?

**Comment by connorshea** [comment]
Works for me :)

**Comment by dblock** [comment]
Yep I meant that, thanks @namusyaka!

**Comment by namusyaka** [comment]
@dblock I can release the version.  Let me know if you are busy.

**Comment by dblock** [comment]
@namusyaka That'd be great!

**Comment by namusyaka** [comment]
[Just released 0.18.0](https://groups.google.com/forum/?hl=ja#!topic/ruby-grape/10gG3aiPp_A).
@jlfaber Thanks for opening the issue.

**Comment by jlfaber** [comment]
@namusyaka Thanks for the tag!
