### ISSUE TITLE
Upgrade mustermann dependency ?

### ISSUE THREAD

**Issue by jarthod** [ruby-grape/grape#1511]
I'm currently having trouble updating an app to Rails 5 because of this dependency, here's why:
- `rails 5` depends on `rack 2`
- `rack 2` requires `sinatra 2+`
- `sinatra 2` requires `mustermann 1`
- `grape 0.18` depends on `mustermann-grape 0.4` which depends on `mustermann 0.4`

So this is a deadlock and I can't bundle this. I tried to find `mustermann-grape` to see if we could upgrade the dependency but I can't find it, It seems with a github search that the Grape extension is now in [mustermann-contrib](https://github.com/sinatra/mustermann/blob/master/mustermann-contrib/lib/mustermann/grape.rb).

So I guess grape is now supposed to depend on `mustermann-contrib` ?

**Comment by namusyaka** [comment]
@jarthod Thanks for yourt report! I'm going to investigate the problem in a few days.

**Comment by dblock** [comment]
I heard from @zzak that the conttrib stuff was a result of merging many gems? Maybe he can help shed some light on what's going on?

**Comment by dblock** [comment]
I think we should use whatever is maintained.

**Comment by namusyaka** [comment]
Yes,  both `mustermann-contrib` and `mustermann-grape` can be maintained.
Btw I think `mustermann-grape` is hosted by me, so we can feel free to cut a release of the gem.

**Comment by dblock** [comment]
Sounds good. Maybe you want to move it into the Grape organization @namusyaka?

**Comment by namusyaka** [comment]
Exactly. Mustermann will be continued to be used by us.
In other words, the gem is considered to be the most desirable that we can handle.

**Comment by dblock** [comment]
If you don't have org permissions move it to me and I'll move it to the org @namusyaka.

**Comment by namusyaka** [comment]
I extracted [mustermann-grape gem](https://github.com/ruby-grape/mustermann-grape), and [dropped the code base from Mustermann repository](https://github.com/sinatra/mustermann/pull/54).

**Comment by zzak** [comment]
Sounds good to me, let me know if you need anything from me.

Thanks

**Comment by shaneog** [comment]
Also stuck due to the same upgrade. Would be great to use the new gem and release. Is there anything I can do to help?

**Comment by namusyaka** [comment]
Sorry fory the late reply. I've just released [v1.0.0.beta2](https://rubygems.org/gems/mustermann-grape/versions/1.0.0.beta2).

I'm going to close this issue, but if you still have the problem, please let me know.
Thanks!

**Comment by russellsilva** [comment]
Thanks @namusyaka for the `mustermann-grape` update. Does that update alone fix this issue though? Grape itself [still depends on mustermann-grape 0.4.0|https://github.com/ruby-grape/grape/blob/master/grape.gemspec#L16]. Does that need to be changed to resolve the original dependency deadlock described by @jarthod?

**Comment by namusyaka** [comment]
@russellsilva I'm going to cut new release mustermann-grape-1.0.0 after releasing official mustermann-1.0.0, and then we will release new grape.

To avoid dependency dead lock, you can use [this branch](https://github.com/ruby-grape/grape/tree/upgrade-mustermann) by adding following line to your Gemfile.

```ruby
gem 'grape', branch: 'upgrade-mustermann', github: 'ruby-grape/grape'
```
