### ISSUE TITLE
Array => Hash => Empty array is lost when parsing params

### ISSUE THREAD

**Issue by nykma** [ruby-grape/grape#1522]
Given an API:
```ruby
params do
  requires :data, type: Array, allow_blank: true
end
post '/test' do
  return params.data.as_json
end
```
And a test:
```ruby
describe 'Test' do
  it do
    post_body = {
      data: [{ test: '123', children: [] }]     
    }
    post '/test', post_body
    puts last_response.body 
  end
end
```
The result is `[{ "test" => "123" }]`.

If I describe this param in detail:
```ruby
params do 
  requires :data, type: Array, allow_blank: true do
    requires :test, type: String          
    requires :children, type: Array, allow_blank: true
  end 
end
```
It will raise a exception of `data[0][children] not found`.
When I change `requires :children` into `optional :children`, no exception is raised, but `children` still disappear.

Both of them behaviors as expected when `children` is not empty. And both of them behaviors the same with or without `allow_blank`.
But when `data` becomes a `JSON` type, it becomes normally:
```ruby
# API
params do
  requires :data, type: JSON
end

# Test
post_body = {
  data: [{ test: '123', children: [] }].to_json
}

# Result is correct: [{ "test":"123","children":[]}]
```

Is this legit?
Tested in grape 0.18.0

**Comment by dblock** [comment]
Empty arrays with a non-JSON type are tricky. There's no such thing, it nulls out the value I believe.

The JSON type posting as you provide is a red herring. You should declare `data` as `Array`, but POST with a JSON content-type, then it will work as you expect. 

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for more questions.

**Comment by nykma** [comment]
Thank you! `post_body.to_json` and `header 'CONTENT_TYPE', 'application/json'` resolved this problem. Seems like it only affects test environment.
