### ISSUE TITLE
requires :travellers, type: Array[String] - message": "travellers is invalid

### ISSUE THREAD

**Issue by Taoshi** [ruby-grape/grape#1524]
I have 
`params do 
                requires :travellers, type: Array[String], desc: 'Your travellers keys.'
end 
`
and get from url such params ` :travellers=>{"ADT"=>"1", "CHD"=>"2"}`

Why i have got `message": "travellers is invalid`?

**Comment by dblock** [comment]
Because travellers is not an array in your example, it's a hash?

**Comment by dblock** [comment]
I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
