### ISSUE TITLE
grape 'array' type  not compatible with swagger ?

### ISSUE THREAD

**Issue by pigghost** [ruby-grape/grape#1529]
here is my code:  
```
params do
      requires :logs, type: Array, documentation: {param_type: 'body'}
end
```
below is the result using 'grape-swagger' and swagger-ui:

```
[
  {
    "logs": "string"
  }
]
```

obviously, it's not correct. Seems a bug?

**Comment by dblock** [comment]
This belongs in grape-swagger, you can open an issue there.
