### ISSUE TITLE
Param from Escaped Unicode in application/json Request Body Not Properly Parsed

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#1530]
Grape ruby has inconsistent behavior when using the ```params``` tag to parse JSON escaped unicode data.

https://github.com/jonmchan/grape-test/blob/master/app/controllers/api/v1/test.rb
```ruby
module API::V1
  class Test < Grape::API
    version 'v1'
    format :json
    prefix :api


    resource :tests do
      params do
        optional :tags,               type: String
      end
      post '/' do
        present :tag, params[:tags]
        present :status, "ok"
      end
    end
  end
end
```

When I write a test, it properly escapes the unicode character from ```\u000a``` to a ```\n``` character. 

```ruby
describe API::V1::Test, :type => :request  do
  let(:json_data) { '{ "tags" : "This is a test.\\u000aThis should be on a new line." }' }
  let(:headers) { { 'CONTENT_TYPE' => 'application/json' } }
  it 'should parse unicode escape characters correctly' do
    post "/api/v1/tests", params: json_data, headers: headers
    expect(response.status).to eq(201)
    expect(response.body).to eql("{\"tag\":\"This is a test.\\nThis should be on a new line.\",\"status\":\"ok\"}")
  end
end
```

However, when I try to actually hit the server using rails server, I get the following:

```bash
$ curl -X POST --header 'Content-Type: application/json' -H 'Accept: application/json' -H 'Authorization: Token token="genU8mgazPyAuCoQoj2c"' -d '{"tags" : "this is a test\\u000aThis should be on a newline."}' http://localhost:3000/api/v1/tests
{"tag":"this is a test\\u000aThis should be on a newline.","status":"ok"}
```

When I parse the json string using the standard json parser, it also converts the escaped unicode character.

```ruby
irb(main):001:0> require "json"
=> false
irb(main):002:0> puts JSON.parse('{"tags" : "this is a test\\u000aThis should be on a newline."}')
{"tags"=>"this is a test\nThis should be on a newline."}
```

I believe the consistent behavior is that it should convert the escaped unicode characters to proper unicode characters. 

I made a test application to demonstrate all this: https://github.com/jonmchan/grape-test

**Comment by dblock** [comment]
I didn't dig through this, but is this because the charset ends up being different? See https://github.com/ruby-grape/grape/issues/467 this could be related.

**Comment by jonmchan** [comment]
User error. \ is interpreted as an escape character even in single quote ruby text. The behavior is consistent. Please close this issue, github won't let me.
