### ISSUE TITLE
the use of methode .zero? in lib/grape/middleware/*.rb generate errors

### ISSUE THREAD

**Issue by thomas-peyric** [ruby-grape/grape#1537]
This morning I update the grape gem (0.18.0 to 0.19.0) and after that all my API don't work.

After some test I found that error comes from last commit on `lib/grape/middleware/versioner/path.rb` file

https://github.com/ruby-grape/grape/commit/1f8809fad26af4382a9ceb2250b9b07b6f58f6a6#diff-22ee51f406faebc9ea629d8f8ef111e3

if i change line 
`if prefix && path.index(prefix).zero?`  
by 
`if prefix && path.index(prefix) == 0` 
all works fine ...

For information i use Rails 4.0.9 with ruby 2.1.0p0

**Comment by dblock** [comment]
Sorry about that. Can you please dig up where we're getting the definition of `.zero?` from? Would like a PR that fixes that of course.

**Comment by thomas-peyric** [comment]
presence of `.zero?` is in 2 files who had been commited 15 days ago.
the commit hash is `1f8809fad26af4382a9ceb2250b9b07b6f58f6a6`

**Comment by dblock** [comment]
I mean where we get it from when it works, ie. ActiveSupport or something like that. 

What I really want is a spec that reproduces this problem in Grape, then a fix and full understanding of why we cannot use `.zero?` here.

**Comment by dblock** [comment]
Write a spec in grape that reproduces this next.

**Comment by dblock** [comment]
Fixed via https://github.com/ruby-grape/grape/pull/1548.
