### ISSUE TITLE
Ruby 2.4 compatibility

### ISSUE THREAD

**Issue by connorshea** [ruby-grape/grape#1542]
The codebase/test suite can't be updated trivially to convert all uses of Fixnum to Integer because in some cases it breaks on older versions and in other cases breaks on 2.4.

See #1541 for what I mean.

**Comment by namusyaka** [comment]
Yeah, I'm going to do this. Thanks for the reporting!

**Comment by namusyaka** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1543
