### ISSUE TITLE
Rack::Test::Methods insanely slow after 0.17 (StackableValues related)

### ISSUE THREAD

**Issue by brucehsu** [ruby-grape/grape#1560]
We're using `Rack::Test::Methods` in our test suite. Recently an update to Grape 0.19.1 from 0.15 dramatically slows down our test suite.

An example which took **_1.8_** seconds to run now requires **_73.72_** seconds to finish.

After tracing commits, we narrowed down this performance issue to a single commit in Grape v0.17 `44bcd5490a1935cc0f74557afe2351e0e085343`:

```ruby
       def [](name)
          return @froozen_values[name] if @froozen_values.key? name
 -        value = [@inherited_values[name], @new_values[name]]
 -        value.compact!
 -        value.flatten!(1)
 +
 +        value = []
 +        value.concat(@inherited_values[name]) if @inherited_values[name]
 +        value.concat(@new_values[name]) if @new_values[name]
          value
        end
```

After reverting this change, the performance returns to how it was before.

I've also used `stackprof` to profile the example:

- Before 0.17

```
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
       627  (33.7%)          98   (5.3%)     Grape::Util::StackableValues#[]
```

- After 0.17

```
     TOTAL    (pct)     SAMPLES    (pct)     FRAME
     84460 (131.5%)        5726   (8.9%)     Grape::Util::StackableValues#[]
```

My speculation would be, in the latter `@inherited_values[name]` and `@new_values[name]` would often be called twice  if the conditional is true introducing overheads when these values are nested.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1561.
