### ISSUE TITLE
Reusable named params

### ISSUE THREAD

**Issue by vypah** [ruby-grape/grape#1563]
The documentation states the following

```ruby
class API < Grape::API
  helpers do
    params :pagination do
      optional :page, type: Integer
      optional :per_page, type: Integer
    end
  end

  desc "Get collection"
  params do
    use :pagination
  end
  get do
    Collection.page(params[:page]).per(params[:per_page])
  end
end
```

which you can find here as well https://github.com/ruby-grape/grape#helpers

But the issue is `params` method does not accept any argument. I get an error at `params :pagination` which states `Found 1 extra argument(s). Requires 0`.

I am using version `0.17.0`

**Comment by dblock** [comment]
Are you sure your shared `params` is inside `helpers`?

**Comment by vypah** [comment]
@dblock unfortunately yes. Here is what my code looks like

```ruby
helpers do
    params :address_params do
       optional :first_name, type: String, desc: 'First name'
       optional :last_name, type: String, desc: 'Last name'
       optional :street, type: String, desc: 'Street'
       optional :city, type: String, desc: 'City'
       ... and other long list of params
    end
end
```

I encounter the error at `params :address_params`. Seems like params is not allowed to accept an argument.

**Comment by dblock** [comment]
We have a ton of tests for this, like [here](https://github.com/ruby-grape/grape/blob/220c345dff9602e431ac780abcb98dbb24293395/spec/grape/api/shared_helpers_spec.rb#L8). Maybe you're using an older version of Grape? Put up a project or try to write a spec in grape with that?

**Comment by dblock** [comment]
@vypah You closed this? What was the issue?

**Comment by vypah** [comment]
@dblock The problem has nothing to do with grape itself but it was rather a rubymine interpreter problem which is still complaining but the code works totally fine. Thanks for your time anyways.
