### ISSUE TITLE
should i see nil values for nested declared params?

### ISSUE THREAD

**Issue by thogg4** [ruby-grape/grape#1574]
I have an endpoint that needs either a nested address or an address line:

```
params do
  optional :address_line

  optional :address do
    optional :street
    optional :city
    optional :state
  end

end
```

If no params are passed in, i get this in `declared`:

```
{
  address_line: null,
  address: []
}
```

I would expect this (with `include_missing` set to true):

```
{
  address_line: null,
  address: {
    street: null,
    city: null,
    state: null
  }
}
```

Am I doing something wrong, or is this how it should work?

**Comment by dblock** [comment]
I think the default here is to treat `address` as an array (for historical and backward compatibility reasons), does adding `optional :address, type: Hash do ...` change this?

**Comment by thogg4** [comment]
@dblock im sorry i forgot to add the `type`
I have been using `type: Hash`, but getting the same result.

**Comment by thogg4** [comment]
@dblock it would break backward compatibility, but would you have any interest in another option (similar to `include_missing`), that would add this?

**Comment by dblock** [comment]
It seems to me that with `type: Hash` this is a bug. But I didn't investigate. Maybe start by writing a test for this - and see if there's already a test in this vein.

**Comment by thogg4** [comment]
It looks like this may be intended based on this commit:
https://github.com/ruby-grape/grape/commit/f60e58eec0d9cf56ddab5bd078f7a0436a71650d

**Comment by thogg4** [comment]
From what I can tell `declared` doesn't take the `type` that is set in the `params` block into account at all.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1575.
