### ISSUE TITLE
Boolean validation ignores values

### ISSUE THREAD

**Issue by sureshprasanna70** [ruby-grape/grape#1577]
```
params do
  requires model_name do
      requires :params1, type: Boolean,allow_blank: false, desc: "params1",values: [true]
  end
end
```
When this API is called with params1 value as false should return an exception. But grape doesn't returns exception and the API  is successfully executed.

**Comment by LeFnord** [comment]
@sureshprasanna70 … what for exception did you expect?

**Comment by sureshprasanna70** [comment]
@LeFnord The exception I had expected was "params1 has invalid value"

**Comment by LeFnord** [comment]
Hi @sureshprasanna70 … you are submitting a value for the param `params1`, with value `false`, so no exception is raised as expected, for this data type, it should only be raised, if the parameter is missing.

**Comment by LeFnord** [comment]
@dblock suggest to close it

**Comment by sureshprasanna70** [comment]
@LeFnord This doesn't address the issue. Let me explain the exception I was expecting. If the value passed for the said params doesn't matches anyone of the values in the `values` option array then grape is expected to throw an error. In this case, when ` params1 `  of the type `Boolean` is passed with `false` as value, grape should be throwing ` params1 is invalid, params1 does not have a valid value `. This is what I was expecting. Yeah as you said allow_blank doesn't make sense here. But the above said behavior is expected.

**Comment by dblock** [comment]
Oh I missed the `values` part. That does look like a bug, @sureshprasanna70 maybe try to write a spec. I'll reopen.

**Comment by LeFnord** [comment]
ah yeah, that makes sense, sorry overlooked the `values` part

**Comment by ktimothy** [comment]
It currenly throws an exception, if you try to define values for `Boolean` type:

```
Grape::Exceptions::IncompatibleOptionValues: type: Virtus::Attribute::Boolean is incompatible with values: [false]
  grape-0.19.2/lib/grape/validations/params_scope.rb:384:in `validate_value_coercion'
  grape-0.19.2/lib/grape/validations/params_scope.rb:244:in `validates'
  grape-0.19.2/lib/grape/validations/params_scope.rb:147:in `validate_attributes'
  grape-0.19.2/lib/grape/dsl/parameters.rb:107:in `requires'
```

**Comment by dblock** [comment]
@ktimothy try to contribute a spec, maybe even a fix?

**Comment by ktimothy** [comment]
@dblock I found a bug in virtus, even suggested a fix, but it doesn't look like they will ever merge it and release new version of gem: last virtus release was over 2 years ago.

**Comment by dblock** [comment]
It looks like there're recent commits, so I wouldn't be so sure.

**Comment by sureshprasanna70** [comment]
@dblock

**Comment by sureshprasanna70** [comment]
@dblock Are we open to fixing this issue?. I could contribute a spec if so..

**Comment by dblock** [comment]
Yes, we are open to fixing this issue.

**Comment by dblock** [comment]
Do note https://github.com/solnic/virtus/commit/a6f8969841247462bb05c456458baa66fce29ed8. I think this means Grape should move on to a new library. I hope someone in the community picks it up! Thanks @solnic for providing a valuable project to us for all the years.

**Comment by ktimothy** [comment]
> Do note [solnic/virtus@a6f8969](https://github.com/solnic/virtus/commit/a6f8969841247462bb05c456458baa66fce29ed8). I think this means Grape should move on to a new library. I hope someone in the community picks it up! Thanks @solnic for providing a valuable project to us for all the years.

Dry-rb maybe?

**Comment by dblock** [comment]
> Dry-rb maybe?

Looking for PRs!
