### ISSUE TITLE
Making Hashie class configurable

### ISSUE THREAD

**Issue by milgner** [ruby-grape/grape#1580]
Grape currently hard-codes the use of `Hashie::Mash`. However this can lead to problems with certain parameter names. Sometimes though this is the preferred behaviour. To make use of Hashies built-in `disable_warnings` functionality, it would be great if the base class would be configurable.

One could even think about making Hashie completely optional and returning a regular `Hash`, seeing as how one also needs the `hashie-forbidden_attributes` gem when in a fairly up-to-date Rails environment. A lot of overhead just for the simple syntactical advantage of being able to write `params.foo` instead of `params[:foo]`, imho.

**Comment by dblock** [comment]
This has been discussed in https://github.com/ruby-grape/grape/pull/1514 and https://github.com/ruby-grape/grape/pull/1448. I think you summarize the work well, so I'll leave this open as a top level issue.

Would definitely take a PR in those lines!

**Comment by dblock** [comment]
You might want to read http://code.dblock.org/2017/02/24/the-demonic-possession-of-hashie-mash.html.

**Comment by dblock** [comment]
Closing via #1610. Please give HEAD a try.
