### ISSUE TITLE
Not able to update record using strong paramters.

### ISSUE THREAD

**Issue by MohdAnas** [ruby-grape/grape#1586]
I am trying to update the record. Please find below the code 

`

	  def subscription_params
        ActionController::Parameters.new(declared(params, include_missing: false)).permit(:resource_id,
                                      :status, :expiry_date, :purchase_date, :plan_id, :number_of_seats,
                                      :max_number_of_seats, :is_in_trial, :trial_end_time, :dealcode, :billing_method)
 	  end

`
This is the method which I am using to permit the parameters 

`Subscriptions.new(subscription_params)`

and its working for creating new records.

But when I do something like this 
`Subscription.update_attributes!(subscription_params)`

Its not working. 

Could you guys please tell what is this all about?

**Comment by dblock** [comment]
The strong parameters section in https://github.com/ruby-grape/grape#rails should answer all the questions.
