### ISSUE TITLE
no implicit conversion of true into String error in Delete end ponits

### ISSUE THREAD

**Issue by tamilrahman** [ruby-grape/grape#1591]
I just created the method for `delete` end point and it expects a response in string.. Other than string it show 500 internal error no implicit conversion of true into String.
>delete ':id' do
>return true
>end

it shows error

>Internal Server Error
>no implicit conversion of true into String

**Comment by tamilrahman** [comment]
Just I checked the update log and found solution from this link [https://github.com/ruby-grape/grape/blob/master/UPGRADING.md](https://github.com/ruby-grape/grape/blob/master/UPGRADING.md)

**Comment by dblock** [comment]
@tamilrahman What did you have to do specifically (for the next person with this problem)?
