### ISSUE TITLE
I want to pass params to route and handle them in custom Formatter

### ISSUE THREAD

**Issue by fr33z3** [ruby-grape/grape#1595]
Hello guys, Is that possible to pass params to route like.
```
get '/', param1: 'param1' do
end
```

and handle them in formatter call
```
class Formatter
  def self.call(object, env, options={})
  end
end
```

Can you please help me with that? How can I archive that stuff?

**Comment by dblock** [comment]
The formatters have access to env, so I think `env[Grape::Env::GRAPE_REQUEST]` may have the actual request which has `params`.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
