### ISSUE TITLE
Returns array for hash parameter when not present

### ISSUE THREAD

**Issue by nicooga** [ruby-grape/grape#1596]
Using grape 0.19.1, also hapening in 0.19.0.

## Whats happening
Given I declared a parameter key with type `Hash` and the parameter was not included when calling the controller, I't returns an empty array for that key.

## Expected behavior
It should return an empty hash, or `nil`, or perhaps not include the key in the parsed output.

## Extended Explanation
Given this parameters:

~~~ruby
params do
  with coerce: String do
    optional :avatar
    optional :first_name
    optional :last_name
    optional :school_year
    optional :phone_number
    optional :age
    optional :description
  end

  optional :location_attributes, type: Hash, default: {} do
    optional :city
    optional :district
    optional :street
    optional :street_number
    optional :notes
  end
end
~~~

... when I hit the controller with this params:

~~~ruby
{"user"=>
  {"id"=>288,
   "avatar"=>
    "http://localhost:3000/system/users/avatars/000/000/288/original/profile_pic.jpg?1489450290",
   "first_name"=>"Numbers",
   "last_name"=>"Terry",
   "age"=>nil,
   "description"=>nil,
   "school_year"=>nil,
   "phone_number"=>nil,
   "email"=>"teacher@gmail.com",
   "teaches_online"=>false,
   "teaches_at_own_place"=>false,
   "teaches_at_public_place"=>true,
   "teaches_at_students_place"=>false,
   "is_teacher"=>true,
   "is_student"=>false},
 "id"=>"288",
 "location_attributes"=>{}}
~~~

... and I extract the declared params like this:

~~~ruby
attributes = declared params[:user]
~~~
the result is this:

~~~ruby
attributes #=>
{"avatar"=>
  "http://localhost:3000/system/users/avatars/000/000/288/original/profile_pic.jpg?1489450290",
 "first_name"=>"Numbers",
 "last_name"=>"Terry",
 "school_year"=>nil,
 "phone_number"=>nil,
 "age"=>nil,
 "description"=>nil,
 "location_attributes"=>[]}
~~~

Note that `location_attributes` gets parsed into an empty array. I do not know exactly what is the expected behavior, but an empty array is not what I've expected. I'd either have `nil` or an empty hash. It breaks with activerecord's `accepts_nested_attributes_for :location` with:

~~~ruby
NoMethodError (undefined method `with_indifferent_access' for #<Hashie::Array []>)
~~~

I am missing something obvious here?

**Comment by namusyaka** [comment]
You should pass raw `params` into the `#declared` helper, and your `params` declaration should be surrounded by `group :user, type: Hash`.

**Comment by nicooga** [comment]
Thanks for the quick response @namusyaka, using `group` solves the issue. As a result I get the `location_attributes` key with a value of `"location_attributes"=>{"city"=>nil, "district"=>nil, "street"=>nil, "street_number"=>nil, "notes"=>nil}`. I still need that `default: {}` to make this work, otherwise I get an empty array.

By the way, I was using `required :user, type: Hash do ...`  before, with the same results.

~~~ruby
params do
  group :user, type: Hash do
    # ...

    optional :location_attributes, type: Hash, default: {} do
      # ...
    end
  end
end

put do
  User.find(params.fetch(:id)).tap do |u|
    u.update! declared(params).fetch(:user)
  end
end
~~~

However, It's not clear why the change from using `required` to `group` changes the behavior of the `default` option in the DSL. You may want to take a look at this.

**Comment by arempe93** [comment]
I encountered this issue today also on grape v0.17.0. If I hit the following api only supplying `body`:

```ruby
params do
  requires :body, type: String
  optional :metadata, type: Hash do
    optional :media_type, type: Integer
  end
end
put do
  changed_attrs = declared(params).compact

  changed_attrs[:metadata] # => []
end
```

I would expect `metadata` to be `nil` so it would be filtered out of the changed attributes using `Hash#compact`. It being an `Array` is extra weird

**Comment by arempe93** [comment]
Just encountered another strange thing testing it, if I pass metadata as explicitly `null`, ie to clear it, such as this in rspec:

```
put "/api/notes/#{id}", body: 'foo', metadata: nil
```

Then the value in `declared(params)` is `{ :metadata => nil }`, which is also very weird and unexpected.

So key not present = `[]` and present but explicitly `nil` = a hash of declared subparams all set to `nil`.

**Comment by dnesteryuk** [comment]
@kadotami fixed this issue in https://github.com/ruby-grape/grape/pull/2043 :slightly_smiling_face:
