### ISSUE TITLE
Grape 1.0.0

### ISSUE THREAD

**Issue by namusyaka** [ruby-grape/grape#1598]
@dblock I'd like to start moving toward 1.0.0.

**Comment by dblock** [comment]
As much as I enjoy 0.x, I'm with you!

**Comment by dblock** [comment]
Things like https://github.com/ruby-grape/grape/pull/1594 could definitely justify a major version bump.

**Comment by namusyaka** [comment]
Yes, the Hashie replacement is big feature. I think that it could justify the major version, too.
However, 1.0.0 must be released as our first stable version. Therefore, I would like to release the version several times (e.g. rc1, rc2).

**Comment by dblock** [comment]
I like your suggestion @namusyaka, go for it.

**Comment by namusyaka** [comment]
I have just created [the 1.0.0 milestore](https://github.com/ruby-grape/grape/milestone/1).

**Comment by dblock** [comment]
How do we feel about actually cutting a 1.0?

**Comment by namusyaka** [comment]
@dblock I'd like to merge other pull requests waiting for review if possible.
I'm going to confirm the PRs in a few days.

**Comment by namusyaka** [comment]
I really sorry, I'm unlikely to be able to work for a while because I have lost my physical condition.
I would like to entrust you release v1.0.0.

**Comment by dblock** [comment]
Feel better @namusyaka!

**Comment by dblock** [comment]
I've released 1.0.

**Comment by namusyaka** [comment]
Thank you!
