### ISSUE TITLE
allow_blank for values

### ISSUE THREAD

**Issue by brlo** [ruby-grape/grape#1604]
Hello.
Option `allow_blank` ignores when using option `values` like this:

```ruby
optional :test_param_name, type: String, values: ['A', 'B'], allow_blank: true
```

This request:
`GET /test_method_name?test_param_name=`

returning error:
`{"error":"invalid_params","message":"test_param_name does not have a valid value"}, status: 400`

grape (0.17.0)

workaround: `values: ['A', 'B', '']`

**Comment by dblock** [comment]
First, you should try with the latest Grape, there have been a lot of fixes around `allow_blank`. Then write a spec that reproduces this here, please? Maybe even a fix?

**Comment by brlo** [comment]
ok. i'll do.
