### ISSUE TITLE
Body yielded non-string value

### ISSUE THREAD

**Issue by fangzhu19880123** [ruby-grape/grape#1611]
<pre>
delete ':id' do
  @pop.destroy
end
</pre>
when i use delete method and is not set the body, the default status is 204, the body is empty, but response_object is true. then it will return
<pre>
response_object = file || [body || response_object]
</pre>
then the method after of Middleware::Formatter will return response_object
<pre>
if Rack::Utils::STATUS_WITH_NO_ENTITY_BODY.include?(status)
  @app_response
else
  build_formatted_response(status, headers, bodies)
end
</pre>
Rack will check the body must string, throw this error

**Comment by dblock** [comment]
Is this any different on HEAD? See https://github.com/ruby-grape/grape/pull/1579.

**Comment by jlfaber** [comment]
If that `destroy` call is being made on a `Sequel::Model` object then it's going to return the object itself. Since that's the last statement in the block, that's what being used as the response object.  Adding a `body false` should give you the 204/empty body you're looking for.

**Comment by fangzhu19880123** [comment]
I know, but i think it should be
<pre>
        # When the body is empty, response_object is present, set response_object to body
        @body ||= response_object

        # The Body commonly is an Array of Strings, the application instance itself, or a File-like object.
        response_object = file || body
</pre>

**Comment by fangzhu19880123** [comment]
Maybe it's my version has a problem, I have a look

**Comment by fangzhu19880123** [comment]
When will release the new tag

**Comment by dblock** [comment]
@fangzhu19880123 Sounds like this solved your problem? I'm going to close this.

See #1612 for release date/discussion.
