### ISSUE TITLE
Release 0.19.2

### ISSUE THREAD

**Issue by eproulx-petalmd** [ruby-grape/grape#1612]
Hello,

When are you planning to release the 0.19.2 version ?

Thanks

**Comment by dblock** [comment]
@namusyaka is the mustermann upgrade preventing us from cutting a 0.19.2, ie. is it a breaking change?

**Comment by namusyaka** [comment]
I think it has no problem.
So we can cut the 0.19.2 release before releasing 1.0.0, but big features should be included in the 1.0.0.

**Comment by dblock** [comment]
@namusyaka Got a moment to do it? I can take care of it today if you're swamped otherwise.

**Comment by eproulx-petalmd** [comment]
Thanks!

**Comment by namusyaka** [comment]
@dblock I'm planning to release current master branch as 0.19.2. 
Any other changes that you would like to add?

**Comment by dblock** [comment]
No go for it!

**Comment by namusyaka** [comment]
Just released [0.19.2](https://rubygems.org/gems/grape/versions/0.19.2), posted an [announcement](https://groups.google.com/forum/#!topic/ruby-grape/HPJriXVWT2I).
Thank you for all of your contributions.
