### ISSUE TITLE
Custom formatters, multiple actions

### ISSUE THREAD

**Issue by subvertallchris** [ruby-grape/grape#1624]
I am caching the JSON representation of a Grape::Entity. It looks like this:

```
    formatter :json, ->(object, _env) { object }

    get do
      Rails.cache.fetch(key: 'mykey', expires_in: 1.minutes) do
        data = MyModel.lookup_query
        API::V1::Entities::MyEntity.represent(data, serializable: true).to_json
      end
    end
```

If I remove the custom formatter, it will `to_json` my already-formatted string, which is obviously no good. I don't mind doing this but other actions in this controller are trying to use my custom formatter, which keeps them from being returned correctly.

Is there a way to cache/return the JSON without using a custom formatter? If not, is there a way to associate the formatter with _only_ this one GET action so the other actions in this controller use the default?

**Comment by dblock** [comment]
Maybe cache the `as_json` output? Or roll out a slightly different formatter, ours is:

```
# The original Grape formatter is more strict and doesn't allow String or nil.
module Grape
  module Formatter
    module Json
      class << self
        def call(object, _env)
          return object if !object || object.is_a?(String)
          return MultiJson.dump(object) if object.respond_to?(:to_json) # to_json will use ActiveSupport::JSON.encode, which double-encodes UTF-8 strings
          fail Grape::Exceptions::InvalidFormatter.new(object.class, 'json')
        end
      end
    end
  end
end
```

**Comment by dblock** [comment]
I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
