### ISSUE TITLE
present multiple entities at once

### ISSUE THREAD

**Issue by chiwenchen** [ruby-grape/grape#1626]
Hi, I am trying to present two different type of entities in one API response, something like this
```
present {
          :user => User.all, with: V1::Entities::User,
          :devices => Device.all, with: V1::Entities::Device
        }
# this syntax won't work
```
and I am expecting this will generate the following structure
```
{
    users: [ Collection of User Entities ],
    devices: [ Collection of Device Entities ]
}
```
is there any way to achieve this approach?

**Comment by dblock** [comment]
This is more of an entity question than a grape question, you can do this by creating a parent entity and using `expose ... with: ...`. 

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by elhowm** [comment]
@dblock so, we should create an parent entity for each uniq endpoint. awesome(

**Comment by dblock** [comment]
Your example is not even a valid hash (you have the `with` key twice), so that threw me off and I gave the wrong answer.

Grape actually supports presenting multiple things like you want. From the doc:

<img width="917" alt="Screen Shot 2019-11-15 at 9 38 33 AM" src="https://user-images.githubusercontent.com/542335/68951287-b82c9700-078b-11ea-8823-488a44ce3798.png">

**Comment by elhowm** [comment]
After around 20 min of experiments
```ruby
present(
  users: present(User.all, with: V1::Entities::User),
  devices: present(Device.all, with: V1::Entities::Device)
)
```

**Comment by dblock** [comment]
This didn't work?

```ruby
present :users, User.all, with: V1::Entities::User
present :devices, Device.all, with: V1::Entities::Device
```

**Comment by elhowm** [comment]
The deal is that when you need deeper scoping or smth around
In this case the form that I gave works better because it avoids duplication of the path and concentrate your vision on the single response "block"
but it's IMHO
so, I just propose to do like that but it's not wrong or must-to-do

**Comment by dblock** [comment]
Ok, I understand. 

I am surprised this worked. I haven't tried but I wonder whether

```
present(
  x: present(User.all, with: V1::Entities::User),
  y: present(Device.all, with: V1::Entities::Device)
)
```

produces the same output? This is because the inner present are registering output and the outer doesn't produce anything presentable.

Also try just

```ruby
{
  users: present(User.all, with: V1::Entities::User),
  devices: present(Device.all, with: V1::Entities::Device)
}
```

Does this have the same output?
