### ISSUE TITLE
uninitialized constant Grape::Extensions

### ISSUE THREAD

**Issue by CikeyPlanet** [ruby-grape/grape#1637]
I got  `NameError "uninitialized constant Grape::Extensions"`
when I add the line below in `params` block
`build_with Grape::Extensions::Hash::ParamBuilder`.

I check the Grape version and it's the lastest one.

**Comment by dblock** [comment]
For the next person, what was your problem @CikeyPlanet?

**Comment by CikeyPlanet** [comment]
I want to use the feature `build_with Grape::Extensions::Hash::ParamBuilder` and get an error.
Then I realized that the feature will be released in v1.0.0 not v0.19.2.
