### ISSUE TITLE
Possible bug with validation of JSON parameters

### ISSUE THREAD

**Issue by ktimothy** [ruby-grape/grape#1640]
I have an API with 2 endpoints: one works with single json object and second can receive a batch of json objects of the same structure. I did not want to describe all of the parameters of endpoints twice, so I ended up with using shared params.

The minimal API code is:
```ruby
class API < Grape::API
  helpers do
    params :test_json do
      requires :obj, type: JSON do    # changing JSON to Hash makes /test_batch work, but breakes /test_single
        requires :foo, type: String, values: %w(bar)
      end
    end
  end

  params do
    use :test_json
  end
  get :test_single do
    'OK'
  end

  params do
    requires :batch, type: Array[JSON] do
      use :test_json
    end
  end
  get :test_batch do
    'OK'
  end
end
```

And here either one of /test or /test_batch works. I request with `curl`:
```bash
curl -X GET '127.0.0.1:7777/v1/test_single' -d 'obj={"foo":"bar"}'
curl -X GET '127.0.0.1:7777/v1/test_batch' -d 'batch=[{"obj":{"foo":"bar"}}]'
```
`/test_single` returns `"OK"` while `/test_batch` fails with `{"error":"batch[obj] is invalid"}`

Changing `:obj` type to Hash, as mentioned in code above, makes `/test_batch` return `"OK"`, but `/test_single` fails with `{"error":"obj is invalid, ... blah-blah`.

It looks like a bug to me =(

**UPD**: I have managed to fix it by adding custom coercion to `:obj`:
```ruby
coerce_with: ->(raw) { raw.is_a?(String) ? JSON.load(raw) : raw }
```
, but it looks like an ugly hack.

**Comment by dblock** [comment]
Aren't you forgetting to tell it what content type it is? Otherwise it sends the data as `application/x-www-form-urlencoded`, does adding `-H "Content-Type: application/json` to the command line fix it?

**Comment by ktimothy** [comment]
If I add the header, I get an error `{"error":"internal error"}`. Log says `ERROR Grape::Exceptions::InvalidMessageBody `, and I do even understand why: it expected me to send parameters as json `{"obj":{"foo":"bar"}}`, while I send (`obj={"foo":"bar"}`).

Well, now it is pretty clear to me that I am doing things wrong. Thanks for your help =)
