### ISSUE TITLE
regression: parameters bound by `given` always applied/checked when nested

### ISSUE THREAD

**Issue by jnardone** [ruby-grape/grape#1659]
This is a regression from 0.19.2 -> 1.0.0

Consider a declaration like:

```
     subject.params do
        requires :a, type: String, allow_blank: false, values: %w(x y)
        given a: ->(val) { val == 'x' } do
          requires :inner1, type: Hash, allow_blank: false do
            requires :foo, type: Integer, allow_blank: false
          end
        end
        given a: ->(val) { val == 'y' } do
          requires :inner2, type: Hash, allow_blank: false do
            requires :bar, type: Integer, allow_blank: false
          end
        end
      end
```

The parameters for "inner1" / "inner2" should only be applied when the `given` block matches, but in the nested case (like above) the parameter validations are always applied even if they do not match the `given` criteria.  

For example, doing a request where `a` is `x`, you will get a 400 with `inner2[bar] is missing, inner2[bar] is empty`

Seems like this must have broken with #1625 @rnubel  @avellable ?

**Comment by rnubel** [comment]
Thanks for the great write-up! #1661 should resolve this, and has some explanation as to why it regressed.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1661
