### ISSUE TITLE
"Raw" responses still contain quotes

### ISSUE THREAD

**Issue by adamjgrant** [ruby-grape/grape#1668]
According to [this](https://github.com/ruby-grape/grape#sending-raw-or-no-data), you should be able to return a raw response, without "s with

~~~
class API < Grape::API
  get '/' do
    content_type 'text/plain'
    body 'Hello World'
    # return value ignored
  end
end
~~~

However, in practice, this still returns

~~~
"Hello World"
~~~

Notice the quotes.

Other users experiencing this problem [here](https://stackoverflow.com/a/30092671/393243)

**Comment by dblock** [comment]
You just need to make sure you have a formatter for `:txt`. There's an example [here](https://github.com/ruby-grape/grape-on-rack/blob/master/api/content_type.rb) and a [spec](https://github.com/ruby-grape/grape-on-rack/blob/master/spec/api/content_type_spec.rb#L10).

**Comment by adamjgrant** [comment]
That worked. Thank you @dblock
