### ISSUE TITLE
Can't use a Proc with values

### ISSUE THREAD

**Issue by gtournie** [ruby-grape/grape#1670]
On my project, this code:
```
requires :number, type: Integer, values: ->(v) { v > 0 }
```
throws an `ArgumentError (wrong number of arguments (0 for 1))`
If I remove the `values` option, everything is ok.
Seems like the proc doesn't like the arg.

I use grape 1.0.0

**Comment by dblock** [comment]
This should work, can you turn it into a spec in the grape repo, please?

**Comment by dblock** [comment]
Looks related to @jlfaber's https://github.com/ruby-grape/grape/issues/1616

**Comment by jlfaber** [comment]
This should work. It was both implemented and spec'd. I tried adding your exact param spec in the UT code under both 1.0.0 and HEAD (Ruby 2.4.1) and it works fine for me.  Can you pass on which ruby version you're using, and at least a portion of the stack trace you're seeing?

I do notice that the validator does not rescue RuntimeErrors raised within the lambda literal.  So, in your example, sending in a request that's missing the number param will raise NoMethodError: undefined method `>' for nil:NilClass.  We could probably put a rescue around the call in the validator code.  But you can also avoid that by carefully defining the lambda.

**Comment by nicholasserra** [comment]
Had the same issue. Bumped from grape 0.19.2 to 1.0.0 and now it works. I was using the example in the README:

```
requires :page, type: Integer, values: ->(v) { v.even? && v < 25 }
```

**Comment by dblock** [comment]
I'm going to close this.

**Comment by nicholasserra** [comment]
This resurfaced for me somehow. Tried bumping to ruby 2.4.1 and still seeing it.
