### ISSUE TITLE
Param alias

### ISSUE THREAD

**Issue by glaucocustodio** [ruby-grape/grape#1673]
Hi folks, given the following api:

```ruby
resource :users do
  params do
    requires :email_address, allow_blank: false
    requires :password, allow_blank: false
  end
  post do
    User.create!(email: params[:email_address], password: params[:password])
  end
end
```

Do you think the following api would be nice? (alias `as:`)

```ruby
resource :users do
  params do
    requires :email, allow_blank: false, as: :email_address
    requires :password, allow_blank: false
  end
  post do
    User.create!(params)
  end
end
```

**Comment by dblock** [comment]
I think that would be valuable.

**Comment by glaucocustodio** [comment]
Do you think the first suggestion is better than the below one @dblock?

```ruby
resource :users do
  params do
    requires :email_address, allow_blank: false, as: :email
    requires :password, allow_blank: false
  end
  post do
    User.create!(params)
  end
end
```
I just implemented this one `requires :email_address, allow_blank: false, as: :email` but I'm not sure which is better.

**Comment by dblock** [comment]
I think that if the model takes `:email` and the API takes `:email_address` you're trying to rename the API's `:email_address` into `:email`, so I think `as:` means "rename what's required into the value of `:as`, aka the second suggestion. Otherwise it feels backwards.

**Comment by glaucocustodio** [comment]
Do you think `requires :email_address, as: :email` would lead to mistakes given that in Grape Entity we would do `expose :email, as: email_address` to expose the key as email_address.

**Comment by dblock** [comment]
I mean it's what renaming is about ;)

**Comment by tlabeeuw** [comment]
PS: this currently doesn't seem to work for nested params:
```ruby
group :foo, alias: :bar do
  requires :a
end
requires :baz, alias: :cat do
  requires :b
end
```
These above both fail.

**Comment by dblock** [comment]
@tlabeeuw Can you please see if this is still broken on HEAD? Maybe PR a spec?
