### ISSUE TITLE
How to rescue params error

### ISSUE THREAD

**Issue by jonhue** [ruby-grape/grape#1677]
I have customized error messages for a bunch of errors:

```ruby
        rescue_from :all do |e|
            error!({
                type: 'api_error',
                message: "Something went wrong on our end. We're sorry for the inconvenience. Please check back later."
            }, 500)
        end
        rescue_from ActiveRecord::RecordNotFound, ActionController::RoutingError, AbstractController::ActionNotFound do |e|
            error!({
                type: 'invalid_request_error',
                message: e.message
            }, 404)
        end
        rescue_from ParamValidationFailed do |e|
            error!({
                type: 'invalid_request_error',
                message: e.message
            }, 400)
        end

        params do
            requires :api_key, type: String
        end
```

How can I customize the error if param validations failed?

**Comment by dblock** [comment]
```ruby
rescue_from Grape::Exceptions::ValidationErrors
```

There's an example [here](https://github.com/ruby-grape/grape/blob/220c345dff9602e431ac780abcb98dbb24293395/spec/grape/exceptions/validation_errors_spec.rb#L55).

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by jonhue** [comment]
@dblock GGroups is somehow not picking up my post, so please excuse this follow-up question.

In my API I am using ActionController::HttpAuthentication::Basic for authentication.
How do I include that module. I've tried a bunch of ways, on of which was:

```ruby
helpers ActionController::HttpAuthentication::Basic do
    # ....
end
```

**Comment by dblock** [comment]
@jonhue Your post was sitting in moderation queue, it gets approved in time.

Grape is not designed to work with ActionController extensions, but with standard Rack middleware. Also, Grape has built-in support for basic auth, see https://github.com/ruby-grape/grape#basic-and-digest-auth or https://mikecoutermarsh.com/grape-http-basic-authentication/.
