### ISSUE TITLE
`default` value gets used when `given` block evaluates to `false`

### ISSUE THREAD

**Issue by astorije** [ruby-grape/grape#1681]
So, given this hypothetical scenario (using `grape` v1.0.1):

```rb
params do
  requires :foo, type: Symbol, values: [:a, :b]
  given foo: ->(val) { val == :a } do
    optional :bar, type: Symbol, default: :my_default
  end
end
put do
  binding.pry # Setting a breakpoint to highlight the following examples
end
```

I get the following when `foo` is `:a`, as expected:

```rb
> request.url
=> "http://example.com/api?foo=a"
> params
=> {"foo"=>:a, "bar"=>:my_default}
```

However, when `foo` is `:b`, this seems unexpected:

```rb
> request.url
=> "http://example.com/api?foo=b"
> params
=> {"foo"=>:b, "bar"=>:my_default}
```

Reason why I was surprised by this is that the parameters contract says that the default value of `:my_default` is only relevant when `foo` is `a`. Instead, I should be getting the following:

```rb
> params
=> {"foo"=>:b}
```

Is this a known case, or a bug?

**Comment by rnubel** [comment]
Looks like a bug to me. Default-value population is probably not looking at the `given` constraints.

**Comment by dblock** [comment]
@darren987469 another one? :)

**Comment by darren987469** [comment]
No problem, I will try it. 😄

**Comment by darren987469** [comment]
@dblock close this?
