### ISSUE TITLE
inherit  HTTP Codes definitions in sub resources

### ISSUE THREAD

**Issue by lal-s** [ruby-grape/grape#1684]
Is it possible to inherit definitions of the  HTTP Codes declared through `failure` in sub resources?

Example:

```
resource '/thing' do
  mount SubThing
  desc 'get thing'
  get failure: [
     { code: 400, message: 'Invalid parameter entry' },
     { code: 404, message: 'Not authorized' },
  ] do
   # render
   end
end
```

Is it possible to inherit the definitions 400 and 404 provided in `Thing` into `SubThing` in any way?

Thank you

**Comment by dblock** [comment]
Not automatically I believe, that would be a side effect that's really hard to discover from within `SubThing` by just looking at its code. You can always declare that array elsewhere and reuse it?

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
