### ISSUE TITLE
ActionDispatch::Callbacks.to_prepare was removed

### ISSUE THREAD

**Issue by bdube** [ruby-grape/grape#1687]
README.md mentions using ActionDispatch::Callbacks.to_prepare to deal with reloading in Rails. It looks like it was removed here: [3f2b7d60](https://github.com/rails/rails/commit/3f2b7d60a52ffb2ad2d4fcf889c06b631db1946b#diff-1c13a97300266bc1689b138c5d3bb95f)

Looks like ActionDispatch::Reloader or ActiveSupport::Reloader might be the replacement?

**Comment by dblock** [comment]
Makes sense, would appreciate a PR fixing the docs.

**Comment by bdube** [comment]
Done #1690

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1690
