### ISSUE TITLE
Mounting the same api multiple times doesn't work properly

### ISSUE THREAD

**Issue by vinceve** [ruby-grape/grape#1699]
When you're in the case that you want a nested resource in your API and the same resource also as a separate resource, the mounting only executes the last configuration in line.

example: (root: /)

```
mount StuffApi
# should be /posts
mount PostApi
```

and in StuffApi: (/stuff/)

```
# should be /stuff/:stuff_id/posts
route_param :stuff_id do
  mount PostApi
end
```

In this example the post API will only be mounted on /posts and not on /stuff/:stuff_id/posts . If I comment out the mount in the root, it works in the nested resource.

**Comment by dblock** [comment]
I believe this is a dup of https://github.com/ruby-grape/grape/issues/570, would love a fix.
