### ISSUE TITLE
CORS Support

### ISSUE THREAD

**Issue by MrDys** [ruby-grape/grape#170]
I'm working with Grape in a situation where I need some cross-site scripting. I've forgone JSONP for now and just went with implementing CORS on the Grape end of things.

Currently, I am setting the Access-Control-Allow-Origin header for each request block:

``` ruby
get 'databases' do
  header "Access-Control-Allow-Origin", "*"
  ...
end
```

Is there an easier way to set this header globally? I tried sticking it in the namespace block, but it's undefined at that point.

**Comment by dmitry** [comment]
Headers in the `before` block is not set while an exception or an error.
