### ISSUE TITLE
Block multipart/form-data like other content-types

### ISSUE THREAD

**Issue by ardias** [ruby-grape/grape#1703]
Hi,
Before explaining my issue, please take into account I'm fairly new to Ruby and Grape.

So, I'm trying to modify an ' legacy'  api that is using Grape, and our security team mentioned that accepting 'multipart/form-data' is a potential security risk due to CSRF. I've been reading about this and I've seen thar Ruby supposedly already prevents those kinds of attacks, but nevertheless it seems that there is still some potential way to overcome the protection: http://weblog.rubyonrails.org/2011/2/8/csrf-protection-bypass-in-ruby-on-rails/. Problem is I don't think I can upgrade or patch, and even then I don't know if it addresses the issue.

Now I've also seen that there was a fix for Grape 0.9.2 that addressed an issue that is similar to this, #726  regarding content-types. I've tested and it works with some, like for example 'application/xml', if I set 'format : json' in the API, but it doesn't for 'multipart/form-data'.
I've traced to the **formatter.rb**, method **read_body_input** that returns if the request is 'form_data'.

My question is if it's possible to block multipart/form-data content In some way, and only accept the format I specified in the API (:json in this case) ?

Thanks in advance.

**Comment by ardias** [comment]
Hi @dblock ,
i'm really new to ruby/grape. I can try, but can't promise you any timeframe. 

The PR you mention has some conflicts, so  the idea would be to basically copy that PR and add some more specs?

**Comment by dblock** [comment]
Yes, but we also need to understand what's going on in the underlying infrastructure in terms of parsing.

**Comment by ardias** [comment]
Right, that's going to be a bit harder. Anyway, I'll see what i can do.
