### ISSUE TITLE
Create endpoint dynamically

### ISSUE THREAD

**Issue by pinkynrg** [ruby-grape/grape#1709]
I have the very basic CRUD endpoints that are repeated over and over across my resources.

Currently I do have a Rails generator that helps me generating my API endpoints more quickly. 

The obvious downside is that whenever I make a change to the template I need to update a bunch of files. 

Since there is a very clear pattern for some of my endpoints, I was wondering if there was a way to generate them dynamically.

something like calling a static method that calls desc, params etc...:
```
def self.delete_resource(target)
  klass = target.camelize.constantize
  entity = V1::Entities.const_defined?(target.camelize) ? V1::Entities.get_const(target.camelize) : nil
  desc "Delete a #{target}", {
   http_codes: [
    { code: 204, message: "#{target} deleted successfully", model: entity},
    { code: 401, message: 'Unauthorized', model: Entities::ApiError },
    { code: 403, message: 'Forbidden', model: Entities::ApiError },
    { code: 404, message: 'Not Found', model: Entities::ApiError },
   ]
  }
  params do
   requires :id, type: Integer, documentation: entity.documentation[:id]
  end
  route_param :id do
   delete do 
    resource = klass.find_by(id: params[:id])
    must_have_record!(resource)
    authenticate! and authorize!("#{target.upcase}_DELETE".to_sym, resource)
    if resource.destroy
     present resource, with: entity
    else 
     destroy_error!
    end
   end
  end
 end
```

I know the above doesn't work and doesn't make sense. It was only an example to give the idea of what I have in mind.

Thanks

**Comment by pinkynrg** [comment]
I dont think it can be done now. Maybe with something like shared Params it could be done? http://geoff.evason.name/2015/01/18/postgres-ssl-connection-has-been-closed-unexpectedly

**Comment by dblock** [comment]
Why doesn't this work? Did you try defining this method in your base API class and then using it everywhere else?

I like https://github.com/artsy/gris too, maybe something to inspire from?

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by pinkynrg** [comment]
I was able to create dynamically an endpoint as follows (make sure not to call the static method like post/delete/get - those are method already used by Grape::Api):
```ruby
################################################################
### AUTOMAGICALLY GENERATES AN API TO RETURN RESOURCE BY ITS ID
################################################################
def self.show(model)
 model_entity = model::Entity
 label = "#{model.to_s.underscore.humanize.downcase}"
 resource model.to_s.underscore.pluralize do
  desc "Return a specific #{label}", {
   http_codes: [
    { code: 200, message: "#{label} returned successfully", model: model_entity },
    { code: 401, message: "Unauthorized", model: Entities::ApiError  },
    { code: 403, message: "Forbidden", model: Entities::ApiError },
    { code: 404, message: "Not Found", model: Entities::ApiError },
   ]
  }
  params do
   requires :id, type: Integer, documentation: model_entity && model_entity.documentation[:id] ? model_entity.documentation[:id] : { type: "Intenger",  desc: "" }
  end 
  route_param :id do
   get do
    resource = model.find_by(id: params[:id])
    must_have_record!(resource)
    authenticate! and authorize!(:"#{model.to_s.upcase}_RETRIEVE", resource)
    present resource, with: model_entity
   end
  end
 end
end
```
