### ISSUE TITLE
Alias breaks subsequent validations that refer to the pre-aliased params

### ISSUE THREAD

**Issue by b-boogaard** [ruby-grape/grape#1718]
I wrote a test in the `param alias` context within `params_scope_spec.rb`  to demonstrate.

```ruby
it do
  subject.params do
    optional :fooBar, as: :foo_bar
    optional :bar
    at_least_one_of :fooBar, :bar
  end
  subject.get('/alias-breaks-future-validations')
  get '/alias-breaks-future-validations', fooBar: 'foos4life'

  expect(last_response.status).to eq(200)
end
```

When running `bundle exec rake`

```ruby
Failures:

  1) Grape::Validations::ParamsScope param alias should eq 200
     Failure/Error: expect(last_response.status).to eq(200)

       expected: 200
            got: 400

       (compared using ==)
     # ./spec/grape/validations/params_scope_spec.rb:168:in `block (3 levels) in <top (required)>'

Finished in 3.47 seconds (files took 1.48 seconds to load)
1766 examples, 1 failure

Failed examples:

rspec ./spec/grape/validations/params_scope_spec.rb:159 # Grape::Validations::ParamsScope param alias should eq 200
```

Where the aliased param is defined in regards to the validator referencing it also seems to matter. It looks like this is because the [AsValidator](https://github.com/ruby-grape/grape/blob/master/lib/grape/validations/validators/as.rb#L10-L11) is doing the mutation, so after that validator executes any subsequent validator that is referencing the aliased parameter is broken.

**Comment by dblock** [comment]
Seems legit, turn the spec into a PR?

**Comment by b-boogaard** [comment]
Sure, I'll put something together.

**Comment by hosseintoussi** [comment]
This doesn't seem to break against head 🤔

**Comment by b-boogaard** [comment]
It is very possible that this issue could have been resolved in a commit since I opened this issue at the end of 2017. If we don't think there is a problem I am happy to close this, seeing as how I never got around to opening the spec that was asked for.

**Comment by dblock** [comment]
> This doesn't seem to break against head 🤔

I think you should bisect it to a fix and commit the spec unless there's actually a dup spec that does the same thing.

**Comment by hosseintoussi** [comment]
Hey @dblock, sure. This is the commit that implements the fix: https://github.com/ruby-grape/grape/commit/b645fb48940e5f60e2581013108e329702e2182b

There's already a spec for aliased params, but I'm happy to commit this spec too if you think it's good.

**Comment by dblock** [comment]
Thanks for hunting this down, @hosseintoussi. The committed spec seems to be a subset of yours, so closing this.
