### ISSUE TITLE
declaring a json array as a param on post

### ISSUE THREAD

**Issue by nawarm** [ruby-grape/grape#1731]
I am new to grape and trying to post a json array of objects like:

`[
 {
  "name": "name1",
  "source": "source",
  "description": "description1"
 },
 {
  "name": "name2",
  "source": "source",
  "description": "description2"
 }
]`
Since I need to declare all needed params in grape, I am having an issue declaring this array since it does not have a name I can reference it by. Is there a way to declare this array?

**Comment by dblock** [comment]
Looks like a dup of #1730, it has a pretty thorough explanation of your options and was turned in a feature request. I'll close this one. Hope that helps.

**Comment by nawarm** [comment]
It does. Thanks a lot
