### ISSUE TITLE
Does Grape care about fast_jsonapi?

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1738]
People want to know what they need to do to enable https://github.com/Netflix/fast_jsonapi on their Grape projects. Or do they at all? Grape uses whatever JSON provider is available and maybe all the gains are in the object serialization part and not in pure json generation. Potentially this issue belongs in other presenter libraries.   

https://medium.com/netflix-techblog/fast-json-api-serialization-with-ruby-on-rails-7c06578ad17f

**Comment by EmCousin** [comment]
I'm using Grape for many projects of mine. To answer this issue, I personally ended up enriching the [SerializableHash formatter](https://github.com/ruby-grape/grape/blob/master/lib/grape/formatter/serializable_hash.rb) by creating a custom formatter, available in [this gist](https://gist.github.com/EmCousin/9a648c0effc669c7e6d9a41b3f42b98e).

For a given object, if this object is a model instance or a model collection, it basically seeks for the corresponding serializer according to the Rails ActiveModel::Serializer conventions.

Hope this helps. Although it certainly can be improved a lot, but for now, it does the trick for me :)

**Comment by dblock** [comment]
Very interesting @EmCousin. Do you think there's something here that can be turned into a generally useful PR into Grape?

**Comment by EmCousin** [comment]
@dblock I see three options.

- A PR is definitely possible if we want Grape to actively support `fast_jsonapi`. I guess it would be mostly a matter of managing dependencies afterwards
- If not a PR, a dedicated gem making the bridge between Grape and fast_jsonapi could be another interesiting option, like the gem [grape-jsonapi-resources](https://github.com/cdunn/grape-jsonapi-resources/). The dependencies management matter remains the same though.
- We can also think of enriching the `SerializableHash` formatter by making it looking for serializers, whether the serializers use fast_jsonapi or not. It would assume that a serializer instance always responds to `serializable_hash`.

What's the Grape project's spirit on that matter?

**Comment by EmCousin** [comment]
@dblock I ended up creating a dedicated gem, available [here](https://github.com/EmCousin/grape_fast_jsonapi), At least dependencies management will be done in one place only!

This is my first gem, so I'm open to suggestions for improving it!

**Comment by dblock** [comment]
Good work. At the very least I would add it to https://github.com/ruby-grape/ruby-grape.github.io (with the other one you mention), please. I'll open issues in the gem itself.

**Comment by rromanchuk** [comment]
@EmCousin struggling to figure out how to tell grape to use a different serializer than the object type passed to render, is there way to specify the serializer to use? 

`render @user, serializer: :custom_compact_user_serializer`

**Comment by rromanchuk** [comment]
Doesn't seem like there is any obvious way short of subclassing my object

looking here 
https://github.com/EmCousin/grape_fast_jsonapi/blob/master/lib/grape_fast_jsonapi/formatter.rb#L40

**Comment by rromanchuk** [comment]
@EmCousin 👌 thanks, seems embarrassingly obvious now.

**Comment by EmCousin** [comment]
@dblock Is this issue still worth being opened?

**Comment by dblock** [comment]
Let's close
