### ISSUE TITLE
declared params include_missing: false sets keys to nil

### ISSUE THREAD

**Issue by jessicamann** [ruby-grape/grape#1739]
We have an endpoint with these specified params: 

```
requires :name, type: String
optional :text, type: String
optional :hash, type: Hash do
  optional :field1, type: Integer
  optional :field2, type: String
end
```

When I post to the endpoint with params: `{name: 'person'}`
`declared param includes_missing: false`, I get this: 

```
{
name: 'person',
text: nil,
hash: {
    field1: nil,
    field2: nil
  }
}
```

But I expected this: 

```
{
name: 'person'
}
```

This is using grape 1.0.2

**Comment by dblock** [comment]
I think you wanted `include_missing`, not `includeS_missing` ;) Hope this helps.

**Comment by jessicamann** [comment]
Ah, thanks!
