### ISSUE TITLE
UPLOAD FILE: MISSING ATTRIBUTE PHOTO ON REQUEST

### ISSUE THREAD

**Issue by kenzo2013** [ruby-grape/grape#1743]
Hello, my method to upload is:
https://puu.sh/zspVX/6eac6c8939.png
In the documentation of grape i am worry because instead of attribute 'photo' i see 'body' https://puu.sh/zsq1d/d3fb3b19ac.png
and response is  "error": "photo is missing" every time.

Please help...:(

**Comment by dblock** [comment]
If you attach a file as body, it won't be called "photo". Generally turning a body into a named property isn't something Grape can do, so you can just read the body content in the API implementation and use it as the photo.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
