### ISSUE TITLE
Problem with GET request with encoded query params

### ISSUE THREAD

**Issue by amrrbakry** [ruby-grape/grape#1777]
I'm having a problem with making a **_GET_** request with encoded query params. This is how my endpoint is set up to receive the params:
```ruby
        params do
          requires :event_id, type: String, desc: 'Event id'
          requires :tickets, type: Array, desc: 'Array of each ticket data ex:  [ {id: "", count: 1 , coupon_code: ""} ]', allow_blank: false do
            requires :id, type: String, desc: 'Ticket id'
            requires :count, type: Integer, desc: 'Number of tickets to get'
            optional :coupon_code, type: String, desc: 'Promocode to apply if any'
          end
        end
```
As you can see I'm expecting an _event_id_ param and another array of objects param _tickets_, and this is how the request URL looks like: 

`http://localhost:3000/api/service_fees/calculate?eventId=2xy6rft69azlu2mtppnzb1xe6olzd3f0&tickets[]=%7B%22id%22:%22vohd3y3n25cdgbvi3uzmqhcyie3zi53a%22,%22count%22:2%7D`

however, grape doesn't seem to understand these encoded query params and I get this exception:
```ruby
 [Exception: event_id is missing, tickets[0][id] is missing, tickets[0][id] is invalid, tickets[0][count] is missing, tickets[0][count] is invalid]
```
is there a way i can tell grape to decode and parse the query params properly? am i missing something here?

**Comment by dblock** [comment]
I found https://github.com/ruby-grape/grape/issues/1028 which is very similar. Arrays of hashes is not something you can express in a query string AFAIK per HTTP spec. I'll close this as a dup of that, you should either way just POST JSON.
