### ISSUE TITLE
is_array is not supported if we pass options as a block to `desc`

### ISSUE THREAD

**Issue by ysv** [ruby-grape/grape#1789]
Old style desc works well for me
```ruby
desc 'Get list of user accounts',
  is_array: true,
  success: Entities::Account
```

But since passing it via hash is [deprecated](https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/desc.rb#L50) I've tried to pass it via block and it didn't work for me

```ruby
desc 'Get list of user accounts' do
  success Entities::Account
  is_array true
end
```
same for this
```ruby
desc 'Get list of user accounts', is_array: true do
  success Entities::Account
end
```
How array response should be described in documentation using block ?

**Comment by ysv** [comment]
related to https://github.com/ruby-grape/grape-swagger/issues/705

**Comment by darren987469** [comment]
@ysv Do you mind I try it?

**Comment by ysv** [comment]
@darren987469 you are welcome
