### ISSUE TITLE
:as is skipped for nested params description

### ISSUE THREAD

**Issue by prettyGoo** [ruby-grape/grape#1814]
```ruby
optional :questions, type: Array, as: :questions_attributes do
    optional :title, type: String
    optional :answers, type: Array, as: :answers_attributes do
      optional :text, type: String
    end
end
```

When I try to specify params names using :as I get in my params object the "questions" key replaced with "questions_attributes" (which is expected behaviour), but the "answers" key remains "answers"

Not sure which version of grape I am using, but I guess it should be 1.1.0

**Comment by dblock** [comment]
Looks like a bug to me, write a test against HEAD?

**Comment by prognt** [comment]
Hello. How are things with this bug?
On version 1.2.2 it is missing, starting with 1.2.3 - there is.

**Comment by dblock** [comment]
We're waiting for you @prognt to write a test and a fix.

**Comment by hosseintoussi** [comment]
This issue seems to be fixed with this https://github.com/ruby-grape/grape/commit/c57d97c792ed5b013757c4d5219434f0f20681f0

**Comment by dblock** [comment]
Thanks @hosseintoussi, closing.
