### ISSUE TITLE
Define complex parameters

### ISSUE THREAD

**Issue by mcmegavolt** [ruby-grape/grape#1819]
Hi, folks!

Can somebody explain how to define complex parameters like this?

```ruby
{
  name: 'users_properties',
  parent_entity: {
    user_id: 1
  },
  linking_entities: [
    {
      action: 'create',
      data: {
        property_id: 2,
        relation_types: [
          {user_relation: 'one', property_relation: 'two'},
          {user_relation: 'three', property_relation: 'four'}
        ]
      }
    }
  ]
}
```

Note, that the **user_id**, **property_id**, **user_relation**, **property_relation** keys are dynamic here, so theese key names can be one of predefined in array constant.

Also, need to properly display it in swagger-ui.
Please, help!

**Comment by dblock** [comment]
```ruby
requires 'name', type: String
requires :parent_entity, type: Hash do
  requires :user_id, type: Integer
end

# etc. 
```

I'll close this. Ask [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) if you're still having issues.
