### ISSUE TITLE
Should we use the ISO 8601 date format on the changelog?

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape#1827]
I've realized on the prior release I've made a mistake as I use the British date format (DD/MM/YYYY) rather than the American one. 
Should we use the ISO 8601 YYYY/MM/DD which is less prone to confusion? 

(Really minor point here)

**Comment by dblock** [comment]
Yep, lets do ISO, it's clear every time :)

**Comment by dblock** [comment]
Also, if you feel really ambitious @myxoh, https://github.com/dblock/danger-changelog/issues/4
