### ISSUE TITLE
Release of 1.2.2

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape#1838]
This issue is for the release of 1.2.2.
I'd very much to get this over the line: https://github.com/ruby-grape/grape/pull/1833 before that. 
(I can't find any other PRs ready for merging for the release)

**Comment by dblock** [comment]
Since we're fixing a memory leak lets leave #1833 alone for now and cut a release to minimize any kind of risk for users.

**Comment by myxoh** [comment]
@dblock sure. Happy about that. I'll create the release as soon as I have some spare time

**Comment by dblock** [comment]
I'll cut one now, thank you.

**Comment by dblock** [comment]
And done.

**Comment by myxoh** [comment]
Oh Ok. Thanks!
