### ISSUE TITLE
Bundling failure on rails_edge.gemfile

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape#1839]
The CI is currently red on `rails_edge.gemfile` trying to resolve incompatibilities. 

My current thoughts is that this is only due to coveralls. Need some more investigating to confirm

**Comment by myxoh** [comment]
NVM. Confirmed. it was coveralls, however I cannot find a maintained version of the gem. I'll leave this issue open for someone else to take over as I haven't worked with coveralls before.

**Comment by dblock** [comment]
Closed via #1840
