### ISSUE TITLE
Performance degradation after upgrading from v1.1.0 to v1.2.2

### ISSUE THREAD

**Issue by leoarnold** [ruby-grape/grape#1855]
After upgrading from grape v1.1.0 to v1.2.2 our app's performance decreased. Using New Relic, I was able to identify that the newer grape makes extensive use of `Proc#call`, thereby slowing down response times.

![screenshot_20190110_164752](https://user-images.githubusercontent.com/4201235/50980747-b9e95680-14f9-11e9-8550-28d5b81e79b4.png)

**Comment by dblock** [comment]
Do you have some actual duration numbers please?

**Comment by myxoh** [comment]
I think the issue may very well sit with NewRelic, we were facing a similar issue:
https://discuss.newrelic.com/t/not-enough-detail-only-proc-call-and-formatter-call/36946
They seem to have fixed it at some point (It stop measuring `proc#calls`), and it broke again (It started measuring `proc#calls` again)
In terms of actual numbers:
While testing this: https://github.com/ruby-grape/grape/issues/1835 I've also did a benchmark measure, and both the memory usage and time to respond seem mostly unimpacted after the change in version.

If you have some numbers, I'd be more than happy to be proven wrong!

**Comment by leoarnold** [comment]
@myxoh Did not know that. Thank you for pointing that out.

@dblock Here are the numbers:

![screenshot_20190111_123134](https://user-images.githubusercontent.com/4201235/51031524-16518200-159d-11e9-8c39-9d87b0fce0f4.png)

I guess Grape belongs partially to purple "Middleware" and cyan "Ruby". I was running grape v1.2.2 between 4h and 6h PM-ish. Given the big spikes after 6PM, when we were back to v1.1.0, I guess this issue can be closed as invalid.

**Comment by dblock** [comment]
Thanks @leoarnold for bringing it up either way, I'll close this.
