### ISSUE TITLE
Validator fails if number is passed instead of object

### ISSUE THREAD

**Issue by marvinthepa** [ruby-grape/grape#1860]
```
undefined method `empty?' for 1:Fixnum: grape-1.0.2/lib/grape/validations/validators/base.rb:41:in `block in validate!'
```

This happens for something like this:

```
        params do
          optional :foos, :type => Array do
            optional :bar, :type => String
          end
        end
```

and then POSTing something like this:

```
{ "foos": [1] }
```

Setting `requires :bar`  (instead of optional) fixes this.

While it is arguable that allowing empty objects does not make too much sense, who knows what users might want?

The problem is here:

https://github.com/ruby-grape/grape/blob/2dcef9af4dd483a1a3d56cbfd660056ed8e9fe42/lib/grape/validations/validators/base.rb#L41

It probably makes sense to check if resource_params is actually a hash in this case.

**Comment by dblock** [comment]
Looks like a legit bug, please PR a fix.

**Comment by marvinthepa** [comment]
I will try. Might take me some time to get around it, though.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1947#issuecomment-568492399
