### ISSUE TITLE
How to get an instance inside Grape::API class

### ISSUE THREAD

**Issue by ec** [ruby-grape/grape#1866]
Since #1803 Grape:API instance stopped presenting the data inside.
Previously we used `parent_name` in order to rewrite standard errors classes to change errors  format.

With grape 1.1.0
`api = @scope.instance_variable_get(:@api)`
`module_name = api.parent.name.humanize.demodulize`

So, since i've update grape to 1.2.0+ it stopped to work
How can i get the data now?

I will appreciate any help, thanks :)

**Comment by myxoh** [comment]
Hi, as explained in the Upgrading guide: https://github.com/ruby-grape/grape/blob/master/UPGRADING.md

We've deprecated `name` and you should now be using `.to_s` or `base.name` - doesn't this work for you?

**Comment by myxoh** [comment]
I'm not sure what do you have in @scope
I think you should try us

**Comment by ec** [comment]
Yes, i missed that. Well, it works pretty well.

I was looking for smth like this in specs, while looking for solution.
@myxoh Is there any spec describing getting access to the named class from the instance?

P.S. with the answer feel free to close issue, it solved, thanks

**Comment by dblock** [comment]
I'll close this.

I there's no spec that shows this, appreciate a PR!
