### ISSUE TITLE
`Module#parent` deprecation warning with Rails 6

### ISSUE THREAD

**Issue by shlima** [ruby-grape/grape#1871]
Got deprecations warnings with Rails 6.0.0.beta3:

```bash
DEPRECATION WARNING: `Module#parent` has 
been renamed to `module_parent`. 
`parent` is deprecated and will be removed in Rails 6.1. 
```

The warnings refers to the `desc` block

**Comment by rromanchuk** [comment]
looks like this is probably the offender https://github.com/ruby-grape/grape/blob/2dcef9af4dd483a1a3d56cbfd660056ed8e9fe42/lib/grape/dsl/settings.rb#L144

**Comment by dm1try** [comment]
@rromanchuk this method is from `InheritableSetting`
https://github.com/ruby-grape/grape/blob/51217ea2b2d39ff7268feef93838bec880c6fd35/lib/grape/util/inheritable_setting.rb#L8

it should not be a cause of deprecation warning(if the method is not overloaded somehow)

**Comment by dm1try** [comment]
`Module#parent` is a part of [`active_support/core_ext/module/introspection`](
https://github.com/rails/rails/blob/d8d6bd5e63a9a4a6c06a4dde3c7137ee2be105fd/activesupport/lib/active_support/core_ext/module/introspection.rb#L46-L52) but it does not look like grape uses this patch:
```
ruby -Ilib -rgrape -e 'p Module.method_defined?(:parent)'
false
```
at least on load

Could someone provide a traceback for the warning?

**Comment by myxoh** [comment]
I think this was sorted on: https://github.com/ruby-grape/grape/pull/1876 
If I am mistaken, please feel free to re-open the issue
