### ISSUE TITLE
:as not working as expected

### ISSUE THREAD

**Issue by sos4nt** [ruby-grape/grape#1874]
I'm trying to map `{ foo: { bar: '...' } }` to `{ baz: { qux: '...' } }` using aliased parameters:
```ruby
params do
  requires :foo, as: :baz, type: Hash do
    requires :bar, as: :qux
  end
end
```

But when I call the endpoint with `foo: { bar: 'any' }`, it gives me both variants in `params` and only the inner alias in `declared(params)`:
```ruby
params
#=> {"foo"=>{"bar"=>"any", "qux"=>"any"}, "baz"=>{"bar"=>"any", "qux"=>"any"}}

declared(params)
#=> {"foo"=>{"qux"=>"any"}}
```

This looks like a bug. The expected result was: (for both)
```ruby
#=> {"baz"=>{"qux"=>"any"}}
```

**Comment by sos4nt** [comment]
Here's a failing spec:
https://github.com/sos4nt/grape/commit/e5edc24f805bd216e59ddcf0eb5f1284b4709447

**Comment by dblock** [comment]
@sos4nt Thanks, looks legit. You're _this_ close to a fix with a failing spec :)

**Comment by sos4nt** [comment]
I tried but then gave up because I couldn't figure out how the params are being built / validated 😄

**Comment by ckorhonen** [comment]
I'm noticing the same behavior when using `as:` with anything of type `Array` or `Hash`.

When inspecting `params` I see both variants, and when I call `declared(params)` then the `as:` is being ignored.

**Comment by dosuken123** [comment]
It seems this issue has already resolved by https://github.com/dosuken123/grape/commit/c57d97c792ed5b013757c4d5219434f0f20681f0 and it's included in v.1.2.5. Can we close this issue?

**Comment by dblock** [comment]
Closing via #1903
