### ISSUE TITLE
[docs] "alias" is misleading

### ISSUE THREAD

**Issue by sos4nt** [ruby-grape/grape#1875]
Grape can rename parameters via `as:`, so for example:
```ruby
params do
  requires :email_address, as: :email
end
```
will map the input paramter `email_address` to the key `:email` in `params` and`declared(params)`.

I like this feature very much and it does exactly the right thing. But the feature has a quite misleading name:

> ### Alias
>
> You can set an alias for parameters using `as`, which can be useful when [ ...]
 
The term "alias" implies that both parameters co-exist, that they can be used interchangeably. This is clearly not the case here, there's no `params[:email_address]`. Maybe there's some actual aliasing going on within grape, but not on the outside.

I therefore kindly ask you to change the term "alias". Something like "parameter mapping" or "renaming" seems much more appropriate.

**Comment by dblock** [comment]
This makes total sense @sos4nt. Could you PR a change for this please? Appreciate it.

Maybe we can also introduce true aliases as a separate feature request. Curious to hear thoughts from various people of what that could look like syntax-wise.
