### ISSUE TITLE
String is incompatible with values

### ISSUE THREAD

**Issue by Hazlank** [ruby-grape/grape#1877]
```
Grape::Exceptions::IncompatibleOptionValues: type: String is incompatible with values: [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil]
```
I don't know what's happend on it,I can't found this error information on google

**Comment by dblock** [comment]
See https://github.com/ruby-grape/grape#project-resources for if you still need help!

**Comment by Hazlank** [comment]
It's not of grape business.I am not ruby developer.i see the error infomation prefix is grape,so i thought is grape fault,thanks for reply!
