### ISSUE TITLE
Mounting instructions not working in Rails 6 beta

### ISSUE THREAD

**Issue by wentaoliu** [ruby-grape/grape#1878]
The upcoming Rails 6.0 has some breaking changes in autoloading.
See https://github.com/rails/rails/issues/35567#issuecomment-473460592
I followed those steps in Rails 6.0.0.beta3 and it works fine.
Should we document this in the Readme file, or wait and see whether it still holds in the final release of Rails 6.0?

**Comment by dblock** [comment]
It would be helpful to document it for Rails 6 Betas sooner than later. We can remove the "beta" part when Rails 6 ships. Appreciate a PR!

**Comment by myxoh** [comment]
I think this issue is now addressed. Thanks for the contribution!
