### ISSUE TITLE
Access mount configuration inside a resource

### ISSUE THREAD

**Issue by cberkom** [ruby-grape/grape#1883]
Is there any way to access the mount configuration inside a route resolver? I need to customize the response, and this does not work:

```ruby
        # configuration works here:
        route_param :pipeline_id, type: (configuration[:integer_ids] ? Integer : String) do
          get "/" do
            # This throws a NoMethodError saying `configuration` does not exist on class
            present :data, current_pipeline, with: API::Entities::Pipeline, integer_ids: configuration[:integer_ids]
          end
```

**Comment by cberkom** [comment]
The below appears to work, by setting an instance variable that's available inside the `get "/" do` block. Is this the best approach?

```ruby
    # Strangely, configuration is only set inside the `resource` block
    resource :reports do
      if configuration[:integer_ids]
        before do
          @integer_ids = true
        end
      else
        before do
          @integer_ids = false
        end
      end
```

**Comment by myxoh** [comment]
Hi. At the moment it is not possible. It's actually something on my TODO list. 
The `configuration` was a very simple implementation meant for basic usage, but it's proven more popular than I expected so probably worth having a longer look at it in the near future.

Let's keep this issue open. I'm more than happy if you want to get a PR for this issue. Things to consider: - We probably do NOT want to call it `configuration` inside of the resolver, (as it is very likely that this name is already taken by an existing helper inside the classis)
- We probably want the configuration to be resolvable on the `params` (for example for validations or coercer)
- We probably want it accessible in the `before`/ `after`/ scope

Let me know if you want to have a stub at it

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1888, please give HEAD a try?
