### ISSUE TITLE
allow params values to be set dynamically

### ISSUE THREAD

**Issue by sinscary** [ruby-grape/grape#1886]
Hi,
We have been using grape for a long time and thanks for such a great framework.

Below is how we set values for a param.

```
params do
        optional :my_column1, type: Integer, desc: 'some description', values: MyModel1.all.pluck(:id)
        optional :my_column2, type: Integer, desc: 'some description', values: MyModel2.all.pluck(:id)
end
```

Our database is shared between two services. The above two columns(my_column1 and my_column2) get updated by other microservice. And when someone makes a request using API, it fails with the error message "my_column1 does not have a valid value.". same goes for my_column2.

While debugging I realized that during booting of rails application these values are being set and it only gets updated when we restart the server next time.

What we want are these values to be updated dynamically. Which means every time we make a request, it should make a query to the database and set those values. I am having a very hard time figuring out how to do this, or even if it's possible with Grape.

Any help will be appreciated.

**Comment by dm1try** [comment]
>What we want are these values to be updated dynamically. Which means every time we make a request, it should make a query to the database and set those values.

according to the [docs](https://github.com/ruby-grape/grape#values)
> The :values option can also be supplied with a Proc, evaluated lazily with each request.

**Comment by sinscary** [comment]
@dm1try Thanks. It worked.
