### ISSUE TITLE
Grape extension not being inherited

### ISSUE THREAD

**Issue by CodingAnarchy** [ruby-grape/grape#1891]
My application uses the `grape-cancan` extension, but upon upgrading Grape from 1.1.0 to 1.2.4, the `authorize_routes!` methods were only present in `Grape::API` and not in the subclass controllers that are inheriting from it.

These methods are loaded in via:

```ruby
Grape::API.extend Grape::CanCan::API
Grape::Endpoint.send :include, Grape::CanCan::Endpoint
```

**Comment by dblock** [comment]
I think it needs to extend `Grape::API::Instance` now, see https://github.com/ruby-grape/grape/blob/master/UPGRADING.md#changes-in-the-grapeapi-class. Does that work?

**Comment by myxoh** [comment]
I agree with you @dblock by extending the CanCan on `Grape::API::Instance` the behaviour should be restored.
@CodingAnarchy could you confirm?

**Comment by CodingAnarchy** [comment]
I can confirm that this does indeed resolve the issue with the missing methods.  Thanks for the help finding it.  I will submit a pull request to the `grape-cancan` repository.

**Comment by dblock** [comment]
Thanks, let's close this once that has been released? @CodingAnarchy appreciate if you could please link the PR/followup here.

**Comment by CodingAnarchy** [comment]
My apologies on the followup here, but it was resolved by merging this PR in the extension: https://github.com/rzane/grape-cancan/pull/3

This has been merged and released as of now, so I am going ahead and closing this issue as well. Thanks for your help on it!
