### ISSUE TITLE
Inherit from Grape::API::Instance breaks Boolean type

### ISSUE THREAD

**Issue by sondnm** [ruby-grape/grape#1892]
Recently I followed the UPGRADING.md guide to upgrade Grape from 1.0.3 to 1.2.4 and an error occurs due to the use of `type: Boolean` in `params` block.
This happens only when inheriting from `Grape::API::Instance`. I wrote a small rack app to test and the behaviour is the same.

```ruby
# config.ru
require 'grape'

module App
  class API < Grape::API::Instance
    resource :system do
      params do
        optional :hit, type: Boolean
      end
      get :ping do
        "pong"
      end
    end
  end
end

run App::API
```

Error:
```ruby
NameError: uninitialized constant App::API::Boolean
```

I could easily change the `Boolean` to `Virtus::Attribute::Boolean` to fix this issue on my app but since you already supported this Boolean type feature, I think it should be supported in the next releases too.

Thank you.

**Comment by dblock** [comment]
Feel free to PR a fix to this effect. I would also try to track where this got removed. There's probably a good reason since `Boolean` is not a native type in Ruby.

**Comment by myxoh** [comment]
Note: if you are just creating an API you should not be inheriting from `::Instance` rather just from `Grape::API`

In the `Upgrading.md` guide the reference to when you should use `Grape::API::Instance` it is only when you are monkeypatching the class (which is not what you are doing here)

i.e. on this example you should be doing:

```
# config.ru
require 'grape'

module App
  class API < Grape::API
    resource :system do
      params do
        optional :hit, type: Boolean
      end
      get :ping do
        "pong"
      end
    end
  end
end

run App::API
```

**Comment by sondnm** [comment]
Thank you @myxoh for pointing that out. As I can see, the inheritance from `Grape::API` works great for a rack app.

However, on my app where I integrate `grape` with `rails` and using `rspec` together with `rack-test`,  when I run the api specs, it returns 404 if it inherits from `Grape::API`. Notice that the APIs still works normally when running on a real server. Since I want to make sure the tests pass before deployment, I just let them inherit from `Grape::API::Instance` 😄 . That's where I encounter the `Boolean` problem.

FYI, my app's APIs structure would look similar to this.

```ruby
Rails.application.routes.draw do
  mount API::Base, at: "/"
end
```

```ruby
# app/controllers/api/base.rb

class API::Base < Grape::API
  mount API::V1::Base
end
```

```ruby
# app/controllers/api/v1/base.rb

class API::V1::Base < Grape::API
  version 'v1', using: :path
  format :json

  mount API::V1::Ping
end
```

```ruby
# app/controllers/api/v1/ping.rb

class API::V1::Ping < Grape::API
  resource :system do
    params do
      optional :hit, type: Boolean
    end
    get :ping do
      "pong"
    end
  end
end
```

**Comment by myxoh** [comment]
Interesting as this is a similar setup to the one I've got. Could you please attach the failing spec too?  I'll look into this!

Thanks !

**Comment by sondnm** [comment]
Oops! I should have attached it in the first place. I edited the above comment and added the failing spec.

Thanks!

**Comment by myxoh** [comment]
This is interesting, and sounds like a bug. 
Just as a colour point, if you replace the
```ruby
def app
   API::V1::Ping
 end
```
With 
```ruby
def app
  Rails.application
end
```
The spec will go green again.

**Comment by myxoh** [comment]
The problem stems from the fact that an undocumented breaking change from the upgrade is that `Class.new(Grape::API)` is no longer a proper Rack application, rather `Class.new(Grape::API::Instance)` is, this has very few real life implications but I'll see whether I can make it so that `Class.new(Grape::API)` is also a Rack app 
Else, I'll add this to the breaking changes. Thanks for bringing this up :+1:

**Comment by dblock** [comment]
I think we could use a rails integration test in Grape. 

I upgraded https://github.com/ruby-grape/grape-on-rails/pull/8 and it "just worked". What am I missing?

**Comment by dblock** [comment]
I think we could use an integration test in Grape. 

I upgraded https://github.com/ruby-grape/grape-on-rails/pull/8 and it "just worked". This is because I don't have `def app`, that is not required for Rails, only to declare a Rack app in tests if you're using Rack::Test?

**Comment by myxoh** [comment]
OK, I've actually managed to replicate the issue on a spec in the rack integration, and also find a solution ( I believe)
I'll create a PR

**Comment by myxoh** [comment]
I think this issue can now be closed, could you confirm @sondnm whether you can now get your spec to work by inheriting from `Grape::API` ?

**Comment by sondnm** [comment]
It is working great now! Thanks a lot @myxoh.

Since the Boolean type for `Grape::API::Instance` is not relevant anymore, I will close this issue.
