### ISSUE TITLE
YAML support?

### ISSUE THREAD

**Issue by dieuit07** [ruby-grape/grape#1899]
Hi guys, is it possible to support YAML format in Grape?
I try to parse result to YAML before responding to the client-side. The only thing I have to deal with is error response. The error response still returns the JSON message. I could found the document to customize the error.

Do you have any idea about this situation?

**Comment by dblock** [comment]
You should follow https://github.com/ruby-grape/grape#api-data-formats. I suggest doing this in a small project to begin with, maybe https://github.com/ruby-grape/grape-on-rack and we can help you sort it out if you can't make it work.

**Comment by dieuit07** [comment]
I try exactly the same with the sample code and it returns error: 


```
module API
  module V1
    class Populations < Grape::API
      content_type :json, 'application/json'
      content_type :txt, 'text/plain'
      content_type :custom, 'text/custom'
      parser :json, nil
      parser :txt, nil
      parser :custom, YamlParser
      put 'value' do
        content_type 'text/custom'
        "abc"
      end
    end
  end
end
```

```
module YamlParser
  def self.call(object, env)
    binding.pry 
    { value: object.to_s }
  end
end
```

It seems like "YamlParser" not working. The process doesn't go to that method

**Comment by dblock** [comment]
Please make a PR into the project I am suggesting with tests and I will help make it work.
