### ISSUE TITLE
OAuth Support ...

### ISSUE THREAD

**Issue by ghost** [ruby-grape/grape#19]
Is there any timescale for when the OAuth authentication will be added?

I have taken a look on the roadmap as it is listed quite high up on there, but it was last updated on 15th Nov 2010?

**Comment by nbulaj** [comment]
Also you could look at the [`grape_oauth2` gem](https://github.com/nbulaj/grape_oauth2). The main goals of this project are ORM independence (but there are predefined mixins for `ActiveRecord` and `Sequel` and API documentation for any other ORM or PORO objects) and maximum customization. The gem is currently under development (and everybody could help with it), but it's already implements the next features:

- Resource Owner Password Credentials Flow
- Client Credentials Flow
- Refresh token Flow
- Token revocation
- Access Token Scopes

**Comment by dblock** [comment]
@nbulaj You should add it to http://www.ruby-grape.org/projects/ please
