### ISSUE TITLE
Configuration hash inside desc block is empty

### ISSUE THREAD

**Issue by shlima** [ruby-grape/grape#1908]
```ruby
mount Endpoint, with: { test: 'ola' }
```

```ruby
class Endpoint < Grape::API
  mounted do 
    # if I call `configuration` here it will return `{ test: 'ola' }`

    desc 'Sample endpoint' do
      # if I call `configuration` here it will return en empty hash `{}`
    end
  end
end
```

**Comment by shlima** [comment]
It seems that `configuration` methods inside `desc` block refers to the desc configuration, not to the grape's mountable configuration.

How can I access mountable configuration inside the `desc` block?

I wish to use this feature to set up global headers for the swagger:

```ruby
desc 'Endpoint configuration' do
  headers configuration[:headers_documentation]
end
```

**Comment by myxoh** [comment]
This sounds like a probable oversight on my part, as it seems like description had a pre-existing method called configuratoin (which is probably overwriting the configuration bit)

**Comment by shlima** [comment]
@myxoh it defined here https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/desc.rb#L109-L111

**Comment by myxoh** [comment]
I've found that the issue was that I was not handling properly the configuration within `mounted` and `given` blocks (i.e. when the configuration was already evaluated)
