### ISSUE TITLE
Param Type: Dynamic Hashes

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape#1910]
I was wondering whether we could / should introduce a feature for documenting dynamic hashes.

A specific example I'm working on involves an API for a dynamic form that looks something like:

"questions": { "some_question": "Some Answer", "some_other_question": "Some other answer" }

I would love to document this on Grape (so this can be pulled on swagger for instance):

```ruby
params do
  requires :questions, type: DynamicHash do
    key :question, type: String, values -> { Database.questions }, desc: "the reference to the question"
    value :answer, type: String, desc: "The answer to the question"
  end
end
```

In a sense this is similar to `Array[Integer,String]` but with a little more details, and stronger validation

Not sure if someone else wants / cares about this

**Comment by myxoh** [comment]
Closing this due to lack of interest

**Comment by dblock** [comment]
I do like this idea, but why wouldn't it be a regular `Hash`?
