### ISSUE TITLE
`declared` will reject attributes when the param is renamed with `as:`

### ISSUE THREAD

**Issue by dosuken123** [ruby-grape/grape#1919]
It seems `declared` methods filter out renamed attributes with `as:`. I think it should be included.

**Comment by dblock** [comment]
Care to write a spec to demonstrate?

**Comment by anton-yordanov** [comment]
I'm noticing the same behavior when using `as:`
I think that this is a same as https://github.com/ruby-grape/grape/issues/1874

**Comment by dblock** [comment]
Right, I'll close as a dup.
