### ISSUE TITLE
Given that we are officially dropping old rails, make the next release `1.3.0`

### ISSUE THREAD

**Issue by myxoh** [ruby-grape/grape#1921]
On this version we've dropped the appraisals covering rails 3.2 and rails 4.0
https://github.com/ruby-grape/grape/pull/1916

- While it is true they hadn't been part of the standard suite, I'd rather we have a formal stance on supporting rails 3.2, rails 4.0. 

- As of the last commit in which I've run the appraisals, grape still was green on rails 3.2 and rails4.0

If we are dropping support then, I'd suggest we also update the readme to reflect this, and release a major version.

While I understand that rails3.2 hasn't been a supported version of rails in general for a while, I've come across a fair share of businesses using it still, and also in combination with Grape. So I think we should have an official: `Grape won't work with Rails 3.2 anymore without some tweaking after this version` release.

**Comment by dblock** [comment]
👍

**Comment by dblock** [comment]
1.3.0 was released a while some
