### ISSUE TITLE
Simultaneous support for multiple versioning strategies

### ISSUE THREAD

**Issue by tleish** [ruby-grape/grape#1928]
I'm using Grape with Goliath.  Is there an easy way to enable multiple versioning strategies for the same route (e.g. path and header)?

**Comment by dblock** [comment]
That should be possible by mounting the same API into two differently versioned API parents. 

Want to try to add an example to https://github.com/ruby-grape/grape-on-rack?

**Comment by tleish** [comment]
@dblock - thanks for the tip.  I was able to get this working using something like the following:

```ruby
class Twitter::API < Grape::API
  version 'v1', using: :path, strict: true do
    mount Twitter::APIv1
  end
  version 'v1', using: :accept_version_header, strict: true do
    mount Twitter::APIv1
  end

  version 'v2', using: :path, strict: true do
    mount Twitter::APIv2
  end
  version 'v2', using: :accept_version_header, strict: true do
    mount Twitter::APIv2
  end
end
```
