### ISSUE TITLE
Unit Test Parameter Validation and Coercion without Rack

### ISSUE THREAD

**Issue by tleish** [ruby-grape/grape#1934]
Parameter Validation and Coercion definitions can be large.  The only method for testing these definitions that I am familiar with is thought using a test RACK.  If I created definitions in a separate module (or class) and included the definitions in a Grape::API class, could I test the definitions isolated without using using RACK?

**Comment by dblock** [comment]
I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
