### ISSUE TITLE
Add @dnesteryuk to co-maintainers

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#1952]
I'd like to volunteer @dnesteryuk to the co-maintainers of Grape.

@dnesteryuk Are you interested? Your [contributions](https://github.com/ruby-grape/grape/pulls?q=is%3Apr+author%3Adnesteryuk+is%3Aclosed), especially the dry-types work, speak for themselves.

Leaving this open to hear any objection or +1s from other maintainers.

**Comment by dnesteryuk** [comment]
@dblock yes, I am interested :slightly_smiling_face:

**Comment by nicolashopin** [comment]
👍 by me

**Comment by myxoh** [comment]
👍 from my book

**Comment by dblock** [comment]
I'll wait for one more +1, maybe @dm1try @namusyaka?

**Comment by dblock** [comment]
Invited @dnesteryuk to the maintainers group. What's your rubygems username/email? Drop me a note to dblock at dblock dot org pls.

**Comment by namusyaka** [comment]
👍

**Comment by dblock** [comment]
Welcome @dnesteryuk !
