### ISSUE TITLE
Ruby 2.5 issue with private method full_message 

### ISSUE THREAD

**Issue by danillos** [ruby-grape/grape#1954]
[Ruby 2.5.0](https://blog.bigbinary.com/2018/03/13/ruby-2-5-adds-exception-full_message-method.html) adds the public method `full_message` and Grape is overriding this method as private here:

https://github.com/ruby-grape/grape/blob/d58dc0ab7a0b51625217deedd8110d1030be7cf7/lib/grape/exceptions/validation_errors.rb#L51

**Comment by dblock** [comment]
Sounds like we should at least refactor our way out of this. PRs welcome.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/1988
