### ISSUE TITLE
Support Rack 2.1.x

### ISSUE THREAD

**Issue by dnesteryuk** [ruby-grape/grape#1955]
It hasn't been released yet, however, [that PR](https://github.com/rack/rack/pull/1453) changes internals and [breaks the integration](https://travis-ci.org/ruby-grape/grape/jobs/633793046).

Do you think it will be fine to not test against Rack edge? Otherwise, all open PRs will fail :disappointed:

**Comment by dblock** [comment]
We should be calling out that this will affect Grape. I'll add a comment.

**Comment by dblock** [comment]
@dnesteryuk Let's make sure we have a plan forward. Can you help form an educated opinion about what should happen? a) change grape, if so how, and can it be backward compatible b) push back on the change in Rack _before_ it gets released.

**Comment by ioquatix** [comment]
Can you explain why this breaks grape?

**Comment by dnesteryuk** [comment]
Unfortunately, I don't know Grape internals very well. What I see Grape middlewares get "broken" response.

```
[#<Rack::Response:0x00005609074ab198 @status=200, @header={"Content-Type"=>"application/json"}, @writer=#<Method: Rack::Response(Rack::Response::Helpers)#append>, @block=nil, @length=0, @body=["null"], @buffered=false>, nil, nil]
```

for example, [there](https://github.com/ruby-grape/grape/blob/master/lib/grape/endpoint.rb#L229). 

The expected response is:

```ruby
[200, {"Content-Type"=>"application/json"}, ["null"]]
```

Maybe some Grape middleware does something weird, so Grape gets broken because of the change in Rack. I don't know yet... :disappointed:

**Comment by dblock** [comment]
> Can you explain why this breaks grape?

Haven't debugged. It breaks specs. Unclear whether it breaks Grape.

**Comment by dblock** [comment]
Closed by https://github.com/ruby-grape/grape/pull/1956 I believe, thanks @ioquatix
