### ISSUE TITLE
Coercing to BigDecimal and Numeric broken in v1.30.0

### ISSUE THREAD

**Issue by FlickStuart** [ruby-grape/grape#1969]
When creating attempting to coerce a param to `BigDecimal`, Grape `1.3.0` will return an HTTP 400. This is still possible in versions prior to `1.3.0`.

I am able to replicate this by adding the following test to `spec/grape/validations/validators/coerce_spec.rb` just after `context 'coerces' do` at line 157:
```
      it 'BigDecimal' do
        subject.params do
          requires :bigdecimal, coerce: BigDecimal
        end
        subject.get '/bigdecimal' do
          params[:bigdecimal].class
        end

        get '/bigdecimal', bigdecimal: '45'
        expect(last_response.status).to eq(200)
        expect(last_response.body).to eq("BigDecimal")
      end
```
Which fails with
```
Grape::Validations::CoerceValidator coerce coerces BigDecimal
     Failure/Error: expect(last_response.status).to eq(200)
     
       expected: 200
            got: 400
     
       (compared using ==)
     # ./spec/grape/validations/validators/coerce_spec.rb:168:in `block (4 levels) in <top (required)>
```

Stepping into the test, `last_response` is:
```
last_response
=> #<Rack::MockResponse:0x00007fe123fd0758
 @block=nil,
 @body=["bigdecimal is invalid"],
 @buffered=true,
 @cookies={},
 @errors="",
 @header={"Content-Type"=>"text/plain"},
 @length=0,
 @original_headers={"Content-Type"=>"text/plain"},
 @status=400,
 @writer=#<Method: Rack::MockResponse(Rack::Response::Helpers)#append>>
```

Stepping into `DryTypeCoercer.call ` in `lib/grape/validations/types/dry_type_coercer.rb`, `@coercer` is `BigDecimal`, running `@coercer` raises the error:
```
NoMethodError: undefined method `[]' for BigDecimal:Class
```

If we add a `BigDecimal` mapping to `PrimitiveCoercer` in `lib/grape/validations/types/primitive_coercer.rb` like so:
```
class PrimitiveCoercer < DryTypeCoercer
        MAPPING = {
          Grape::API::Boolean => DryTypes::Params::Bool,

          # unfortunatelly, a +Params+ scope doesn't contain String
          String              => DryTypes::Coercible::String,
          BigDecimal          => DryTypes::Coercible::Decimal
        }.freeze
```
The test passes and things appear to work - With `@coercer[val]` returning the `BigDecimal` `0.45e2`.
I'm not sure that this is the right way, or even a good way. 

I'm also not sure how coercion to `Numeric` would be fixed, as there is no obvious DryType to map it to.

**Comment by dm1try** [comment]
@FlickStuart good observation
> The test passes and things appear to work 

could you open a PR?

> I'm also not sure how coercion to Numeric would be fixed, as there is no obvious DryType to map it to.

in the first place, an ability to coerce to Numeric looks strange as [Numeric](https://ruby-doc.org/core-2.5.0/Numeric.html) is base class for all numeric classes. I would deprecate this coercion by providing mapping `Numeric` to `Integer` and then remove it at all.

**Comment by FlickStuart** [comment]
@dm1try PR as requested.
I wondered if additional tests for other types of coercion would be useful?
Have left Numeric for someone else.
