### ISSUE TITLE
Optional file param validation

### ISSUE THREAD

**Issue by shlima** [ruby-grape/grape#1970]
I have the following code:

```ruby
params do
  optional :attachment, type: File
end

post do 
end
```

## Expectation

With grape < 1.2.5 `POST` with empty `attachment` param returns 200

## Reality

`POST` action with empty `attachment` returns 400 `{"error":"attachment is invalid"}`

**Comment by dnesteryuk** [comment]
@shlima Do you mean it is nil or a blank string (`''`)? A test would be helpful :slightly_smiling_face:

**Comment by shlima** [comment]
@dnesteryuk I'he got `400` response when blank parameter do exists in the body, example:

POST `/upload` - 200
POST `/upload?attachment` - 400

So this specs I've wrote will fail https://github.com/shlima/grape/commit/f9e5f0b1023b1dc8e5205c75ebd64d8f6f8226dd

**Comment by rouvroyn** [comment]
I am having the same issue :/  but for me it returns 400 even if the parameter is not empty so
POST `/upload` - 200
POST `/upload?attachment=example` - 400 `("error": "attachment is invalid")`

**Comment by dnesteryuk** [comment]
I will have a look next days.
