### ISSUE TITLE
cannot load such file -- grape/extensions/deep_hash_with_indifferent_access after update to 1.3.0

### ISSUE THREAD

**Issue by cintrzyk** [ruby-grape/grape#1972]
Looks like `Grape::Extensions::DeepHashWithIndifferentAccess` was removed here:
https://github.com/ruby-grape/grape/commit/7ed75987bf530b6ccb02f40c1f11fa7d5707c7fd#diff-0beb8afd3f95a465d9cdf19b4bb7aa59

but it's still declared to autoload here:
https://github.com/ruby-grape/grape/blob/v1.3.0/lib/grape.rb#L87

**Comment by dblock** [comment]
Looks like a bug, please PR.
