### ISSUE TITLE
Does not adhere to Rack SPEC

### ISSUE THREAD

**Issue by wagenet** [ruby-grape/grape#1973]
According to https://www.rubydoc.info/github/rack/rack/file/SPEC:

> The Body must respond to each and must only yield String values. The Body itself should not be an instance of String, as this will break in Ruby 1.9. If the Body responds to close, it will be called after iteration. If the body is replaced by a middleware after action, the original body must be closed first, if it responds to close. If the Body responds to to_path, it must return a String identifying the location of a file whose contents are identical to that produced by calling each; this may be used by the server as an alternative, possibly more efficient way to transport the response. The Body commonly is an Array of Strings, the application instance itself, or a File-like object.

However, the SPEC is not conformed to here:

https://github.com/ruby-grape/grape/blob/5fc668b4bbf460a4f5a41741bb8821a369cf8fbc/lib/grape/router.rb#L168

The response body is expected to respond to an array accessor. This is explicitly not required by SPEC.

**Comment by wagenet** [comment]
I shouldn't file ticket early in the morning! That's referring to the headers, not the body. Sorry for the noise.

**Comment by dblock** [comment]
No worries @wagenet  :)

**Comment by wagenet** [comment]
@dblock Turns out the actual issue was #1744 coming back again due to https://github.com/rack/rack/commit/72959ebc2f300f3b2ccb7ae2aae9f199e611dfb6
