### ISSUE TITLE
Multiple parameter instances in query string (v1.3.0)

### ISSUE THREAD

**Issue by LonelyWolf** [ruby-grape/grape#1983]
Here is an example of the `ary` resource with one route which wants an array `p` of values to be passed to it through query string:
```ruby
resource :ary do
  desc 'Array' do
    nickname 'ary'
    is_array true
  end
  params do
    requires :p,
             type: Array[String],
             allow_blank: false,
             documentation: { param_type: 'query', collectionFormat: 'multi' }
  end
  get do
    # ... do something useful ...
  end
end
```

Request with three parameters for test: `/ary?p=v1&p=v2&p=v3`
This kind of request was generated by Swagger-UI. I mean the query string...

With grape versions 1.2.5 and earlier everything was worked fine, but version 1.3.0 returns an error `{"error ":"p is invalid"}`.

A query like `/api/v1/ary?p[]=x&p[]=y&p[]=z` works, but there a few problems: with the Swagger-UI (it does not generate square brackets in requests), with the users of the API (they categorically deny square brackets in requests) and so on...

So, the question is: is it normal behavior or it is a bug?

Or maybe I'm doing something wrong and it is possible to force the grape to deal with multiple values in the query in the form of `p=v1&=v2` ?

**Comment by LonelyWolf** [comment]
As far I know there is no RFC describing a form of multiple instances of single parameter in the query (or maybe I've searched poorly). With the square brackets and without them, all correct.

I tried to find a place in the grape where the query string parsed, with no luck... suspect that Rack really does it.

In the previous versions grape passed such requests and in the `request.params` there was only the last value from the collection. For this reason I used `CGI.parse(request.query_string)` to get an array.

And one more about the format of the query: try to open the link [https://swagger.io/docs/specification/2-0/describing-parameters/](https://swagger.io/docs/specification/2-0/describing-parameters/) and find the `collectionFormat`. there is a table with an example of the query string for `multi` variant...

And thanks for the response.

**Comment by dblock** [comment]
I'm going to declare that Grape has nothing to do with this and close it. We defer parameter parsing to Rack.

If one must work around this, I imagine a Rack middleware could convert one format into the other.

**Comment by LonelyWolf** [comment]
I found who the parses the query - it is `Rack::QueryParser.parse_nested_query`. I've made a monkeypatch and now Rack understands the format I need: with square brackets and without.

Regarding the question that everything worked in previous versions of grape, but stopped in 1.3.0: it seems that now it began to work as it should. There was a bug, but now it is gone.

Thanks so much for kicking me in the right direction.

**Comment by dblock** [comment]
@LonelyWolf Post your monkey patch here for the next person

**Comment by LonelyWolf** [comment]
```ruby
module Rack
  class QueryParser
    def parse_nested_query(qs, d = nil)
      return {} if qs.nil? || qs.empty?

      params = make_params
      qs.split(d ? (COMMON_SEP[d] || /[#{d}] */n) : DEFAULT_SEP).each do |p|
        k, v = p.split('=', 2).map! { |s| unescape(s) }
        # --- begin ---
        if params.key?(k)
          params[k] = [params[k]] unless params[k].is_a?(Array)
          k = "#{k}[]"
        end
        # --- end ---
        normalize_params(params, k, v, param_depth_limit)
      end
      params.to_h
    rescue ArgumentError => e
      raise InvalidParameterError, e.message
    end
  end
end
```
This not pretends to be an ideal solution, but works for me so far.

**Comment by dblock** [comment]
I encourage you to release this Rack middleware as a gem, with tests & al!

**Comment by ericproulx** [comment]
With [grape-swagger](https://github.com/ruby-grape/grape-swagger#array_use_braces) you can set `array_use_braces: true` with `collectionFormat: multi` in you param documentation. Therefore, every array params will end with `[]` in swagger.

**Comment by MilanVilov** [comment]
Thank you @ericproulx , great solution!
