### ISSUE TITLE
exactly_one_of error change after 1.2.3

### ISSUE THREAD

**Issue by ZeroInputCtrl** [ruby-grape/grape#1985]
We upgraded grape from 1.2.3 to 1.2.5 and we noticed we are not getting the correct error back on exactly_one_of statements. We also upgraded to 1.3.0 and did not change.
setup:
```
params do
  optional :id, type: Integer
  optional :name, allow_blank: false, type: String
  exactly_one_of :id, :name
end
```
We previously were getting `id, name are mutually exclusive` when sending in both fields
Now it is `id, name are missing, exactly one parameter must be provided` which does not accurately represent what is happening. The error for mutually_exclusive is correct but does not provide the extra functionality of exactly_one_of

**Comment by dblock** [comment]
I agree this seems wrong. Care to write a spec for this and bisect where this was introduced?

**Comment by ZeroInputCtrl** [comment]
@dblock #1987

**Comment by nbulaj** [comment]
While #1987 merged this issue could be closes, right?

**Comment by dblock** [comment]
Yes, thanks.
