### ISSUE TITLE
Array[File] doesn't validate correctly.

### ISSUE THREAD

**Issue by jpickwell** [ruby-grape/grape#1986]
If you have a parameter of type `Array[File]`, validation always fails because the primitive type coercer is trying to do `@coercer[val]`, and `@coercer` is `::File`.

```ruby
optional(:nested, type: Hash, default: {}) do
  optional :files, type: Array[File]
end
```

Version 1.2.5 doesn't have this issue, so 1.3.0 broke parameter type coercion.

**Comment by dblock** [comment]
Appreciate a spec + fix in a PR. Thanks.
