### ISSUE TITLE
Ruby 2.7 deprecation warning with middleware/base

### ISSUE THREAD

**Issue by skarger** [ruby-grape/grape#1992]
Ruby 2.7 changes the way keyword args work:
https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

This causes the following deprecation warning:

```
gems/rack-2.2.2/lib/rack/builder.rb:158: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
gems/2.7.0/gems/grape-1.3.0/lib/grape/middleware/base.rb:17: warning: The called method `initialize' is defined here
```

Here is the relevant line in rack 2.2.2:
https://github.com/rack/rack/blob/ffa6dc789ca2f35f39acab15467321b1f9f1ca75/lib/rack/builder.rb#L158

I'm not completely clear on how grape should fix. This may help:
https://eregon.me/blog/2019/11/10/the-delegation-challenge-of-ruby27.html

**Comment by dblock** [comment]
Can you please take a look at fixes in #1949 and #1951, we probably need something in the same lines. Feel free to PR.

**Comment by dim** [comment]
I would create a PR, but I am not entirely sure how where exactly this warning originates. Any ideas?

**Comment by skarger** [comment]
@dim I've held off too because I wasn't sure about the fix, but I gave it a shot here:
https://github.com/ruby-grape/grape/pull/2064

@dblock I took the opposite approach of the PRs you mentioned because the call that prompts the warning happens in Rack.

**Comment by dim** [comment]
@skarger I commented on the PR, I think the `options` argument must remain optional

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2064.

**Comment by dim** [comment]
Hmm, I am still seeing this:

```
../gems/rack-2.2.3/lib/rack/builder.rb:158: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
../gems/grape-1.4.0/lib/grape/middleware/error.rb:30: warning: The called method `initialize' is defined here
```

**Comment by skarger** [comment]
@dim that's coming from a different class, `Middleware::Error` vs. `Middleware::Base`.

Fixed form: https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/base.rb#L17
Remaining warning: https://github.com/ruby-grape/grape/blob/master/lib/grape/middleware/error.rb#L30

The Error case may be fixable in a similar way to #2064.
