### ISSUE TITLE
Better documentation around given and mounted (mount configuration)

### ISSUE THREAD

**Issue by urkle** [ruby-grape/grape#2007]
The documentation doesn't clearly explain when I should use mounted or given.

What I have right now are mount like this.
```ruby
   class MyAPI < Grape::API
      resource configuration[:path] || :integration_links do
         nested = configuration[:nested]
         desc "Retrieve blah for #{nested} do
            detail <<~NOTE
               Returns a collection of blah for #{nested}
            NOTE
         end
         get do
             p = declared(params)
             case configuration[:nested]
             when :project
             when :integration
             else
                 raise ArgumentErorr, 'Endpoint mounted incorrectly'
             end
         end
      end
   end
```

This worked in Grape 1.2.3 (well except in grape1.2.3 I used options[:for].configuration[:nested] inside the endpoint get method)

And in 1.3.0 this still works. w/o needing to use "given" or "mounted" anywhere.

So my questions are why and when should we use given/mounted?

**Comment by dblock** [comment]
This is all about parameters. The `given` keyword allows you to require a parameter, only if another one is present. The `mounted` keyword lets you run code every time the API is mounted via `mount` (which can be multiple times). Doesn't look like you're doing either here?  

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
