### ISSUE TITLE
How to use grape in ruby on jets

### ISSUE THREAD

**Issue by nhphuc412** [ruby-grape/grape#2009]
I try to use grape in ruby on jets. Everything good except method post.
example:
i have method post as:
https://github.com/nhphuc412/jets_with_grape/blob/master/app/racks/grape_app.rb

I try to post have no body => everything good. if post have body, i receive error 415.
"The provided content-type 'text/html' is not supported"

cUrl call api:

`curl -X POST \
  http://localhost:8888/api/hello \
  -H 'cache-control: no-cache' \
  -H 'content-type: application/json' \
  -H 'postman-token: c744271c-f9d3-3167-d75a-6dc10541c715' \
  -d '{
	"test": "123"
}'`

Has anyone encountered the same error yet?

**Comment by dblock** [comment]
I am curious to take a look soon, but before that, isn't Jets a server-less framework with APIG taking over the whole API part. Curious why you want Grape mounted here at all?

**Comment by nhphuc412** [comment]
I have micro project use server-less and i selected ruby on jets. This project just provide endpoint api so i try to mount grape to implement api.

About this issue, I got params in body:
`params = ActiveSupport::JSON.decode(request.body.read)`

**Comment by dblock** [comment]
Write a failing spec in the project?

The error comes from https://github.com/ruby-grape/grape/blob/cf57d250c3d77a9a488d9f56918d62fd4ac745ff/lib/grape/middleware/formatter.rb#L99, and what it's trying to say is that your request is being processed as text/html, instead of application/json. I would debug what's happening in https://github.com/ruby-grape/grape/blob/cd813382d17c16598c8d759ff04903df9f515627/lib/grape/middleware/versioner/header.rb#L74 to see what media type is selected and why.

**Comment by nhphuc412** [comment]
yes, thank you. I'll use jets api for now and expect fix version in future.

**Comment by dblock** [comment]
I PRed https://github.com/nhphuc412/jets_with_grape/pull/1, the way you've been mounting the API seems to not be inserting any of Grape's default middleware. How did you happen to come up with `Rack::Server.start`? Do we need to support it somehow?

**Comment by dblock** [comment]
I'd like to have a jets sample ala https://github.com/ruby-grape/grape-on-rack/. If someone (@nhphuc412) wants to work on that and bring the repo to a state where there's README, CI, tests, etc., I'd be happy to move it to the ruby-grape org.

**Comment by dblock** [comment]
Closing the issue because Grape works as expected and the API needs to be mounted via the documented `Rack::Builder` means.
