### ISSUE TITLE
Creating custom validators is difficult

### ISSUE THREAD

**Issue by stanhu** [ruby-grape/grape#2012]
I'm attempting to port a custom validator to Grape v1.3.1:

```ruby
requires :custom, type: ::API::Validations::Types::CustomObject, desc: 'This is a test'
```

At first, I tried to take https://github.com/ruby-grape/grape/blob/41ee988c06b87b036d12c4c7247d06b75bfa0b7f/lib/grape/validations/types/file.rb as an example:

```ruby
module API
  module Validations
    module Types
      class CustomObject
        def coerce(input)
          input
        end

        def coerced?(value)
          value.is_a?(::CustomObject)
        end
      end
    end
  end
end
```

In Grape v1.1.0, this worked (ignore the `coerced_value?` vs.`coerced?` change and lack of inheritance of `Virtus::Attribute`) because `BuildCoercer.create_coercer_instance` would just fall through and create a Virtus Attribute: https://github.com/ruby-grape/grape/blob/v1.1.0/lib/grape/validations/types/build_coercer.rb#L71.

In Grape v1.3.1, with the switch to dry-types, all unknown types fall through to `PrimitiveCoercer` and fails:

1. https://github.com/ruby-grape/grape/blob/812284fd9334fbd07336e2ac095847cb1e87b866/lib/grape/validations/types/build_coercer.rb#L67. 
1. This quietly fails validation because `super` in https://github.com/ruby-grape/grape/blob/812284fd9334fbd07336e2ac095847cb1e87b866/lib/grape/validations/types/primitive_coercer.rb#L42 eventually calls `@coercer[val]` in https://github.com/ruby-grape/grape/blob/812284fd9334fbd07336e2ac095847cb1e87b866/lib/grape/validations/types/dry_type_coercer.rb#L30.
1. This fails because `@coercer` is `nil`.

To get around this, I saw the `custom?` check appears to look for `self.parse`: https://github.com/ruby-grape/grape/blob/41ee988c06b87b036d12c4c7247d06b75bfa0b7f/lib/grape/validations/types.rb#L134-L135. I ended up with:

```ruby
module API
  module Validations
    module Types
      class CustomObject
        def self.coerce(input)
          input
        end

        def self.coerced?(value)
          value.is_a?(::CustomObject)
        end

        def self.parse(value)
          value
        end
      end
    end
  end
end
```

This appears to work for my purposes, but it seems inconsistent (not to mention undocumented) compared to the built-in validators present in Grape.

Note that dry-types has a simple mechanism for checking types: https://dry-rb.org/gems/dry-types/master/custom-types. Ideally, we'd be able to pass in one of these custom types so we don't need all that code above, but this doesn't work either for the same reasons above:

```ruby
requires :custom, type: DryTypes.Instance(Range), desc: 'This is a test'
```

@dnesteryuk My questions are:

1. Should the Grape type validations look more consistent between `Json`, `File`, and custom ones (e.g. class vs. instance methods, `self.parse` method)?
1. If so, how can we make them more consistent? Otherwise, is this just a documentation issue?
1. Should Grape handle custom dry-types (e.g. https://dry-rb.org/gems/dry-types/1.2/custom-types) natively?

**Comment by dnesteryuk** [comment]
@stanhu First of all there is documentation about the required [parse method](https://github.com/ruby-grape/grape#custom-types-and-coercions). Probably, we need to update internal classes, a PR is welcome :slightly_smiling_face: 

I know that Dry-types supports custom types, however, I don't think we need to couple Grape and Dry-types that match. Maintenance of Virtus was dropped, we don't know what might happen to Dry-Types in the future. Also, there are differences in coercing, you might've seen [this method](https://github.com/ruby-grape/grape/blob/600eee97248d334e0dc1770b4d00c9cdada68a89/lib/grape/validations/types/primitive_coercer.rb#L49-L57), so custom types maintained by Dry-types could bring breaking. In general, what can be simpler than

```ruby
class Color
  attr_reader :value
  def initialize(color)
    @value = color
  end

  def self.parse(value)
    fail 'Invalid color' unless %w(blue red green).include?(value)
    new(value)
  end
end
```

A simple plain Ruby class which anybody can understand without checking documentation. :wink:

**Comment by dblock** [comment]
You could roll out a grape-dry-types gem that makes the connection, even if trivial.

**Comment by stanhu** [comment]
@dnesteryuk Ah, thank you! I don't know how I missed that block of documentation. I'll look at improving the internal classes to reflect this.

**Comment by stanhu** [comment]
@dnesteryuk Actually, the example above doesn't work because `coerced?` has to return `true` as well: https://github.com/ruby-grape/grape/blob/8deebb5b6dcc10db1e7eed0706db6749d38218c8/lib/grape/validations/types/custom_type_coercer.rb#L58

I think we need to update the documentation to reflect that? Something like:

```ruby
class Color
  attr_reader :value
  def initialize(color)
    @value = color
  end

  def self.parse(value)
    fail 'Invalid color' unless self.coerced?(value)
    new(value)
  end

  def self.coerced?(value)
    %w(blue red green).include?(value)
  end
end
```

**Comment by stanhu** [comment]
I'll revise my statement because it's not right. dry-types has stronger type checking now, so if the `parse` returns an object other than the type specified in the API, then it will be invalid. For example:

```ruby
class Color
  attr_reader :value
  def initialize(color)
    @value = color
  end

  def self.parse(value)
    fail 'Invalid color' unless self.coerced?(value)
    new SomeThing(value)
  end

  def self.coerced?(value)
    %w(blue red green).include?(value)
  end
end
```

That's because the following block comes into play: https://github.com/ruby-grape/grape/blob/8deebb5b6dcc10db1e7eed0706db6749d38218c8/lib/grape/validations/types/custom_type_coercer.rb#L96-L110

**Comment by dblock** [comment]
What do you think we shall we do with this issue, @stanhu?

**Comment by stanhu** [comment]
@dblock I submitted #2029. Let me know if that makes sense.

Would you mind releasing 1.3.2 soon? Thanks!

**Comment by dblock** [comment]
Thank you. Opened https://github.com/ruby-grape/grape/issues/2030 for a release, add +1.
