### ISSUE TITLE
Returning an empty list on DELETE

### ISSUE THREAD

**Issue by kubaracek** [ruby-grape/grape#2024]
When presenting an empty list [] DELETE requests results with `204 No Content`

I'm trying to present an empty list to the DELETE request but grape always results with 204 and empty body. So far I've tried `present [], with: SomeEntity` and `body []`. Both return the same response.
It's a JSON api

**Comment by LeFnord** [comment]
you are trying to respond something, so you have to set the status to 200

**Comment by dblock** [comment]
See https://github.com/ruby-grape/grape#http-status-code.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
