### ISSUE TITLE
Are we interested in TideLift?

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#2034]
Are we interested in offering enterprise support for Grape via TideLift? Anyone with experience using the service here for enterprise support? I already sort of make myself available for anything urgent like security patches, but it hasn't really come up.

https://tidelift.com/lifter/search/rubygems/grape claims there's $144.65/month for Grape from Enterprise subscriptions. That's enough for a once a year dinner/drinks for maintainers and regular contributors, for example in New York. I'm happy to organize after the pandemic.

I would need at least a 👍from anyone with r/w permissions here.

**Comment by dblock** [comment]
@myxoh 
@dnesteryuk 
@namusyaka 
@dm1try 
@marshall-lee 
@mbleigh

**Comment by phated** [comment]
Thanks @dblock!  I'm happy to answer anyone's questions about Tidelift too 😄

**Comment by dnesteryuk** [comment]
@phated @dblock Does it imply kind of a paid channel where subscribers will ask question and we will have to answer them?

**Comment by phated** [comment]
@dnesteryuk No, Tidelift tasks are outlined on https://tidelift.com/about/lifter-tasks - we allow subscribers to contact the Tidelift team with any questions (though this doesn't really happen right now) and we might reach out to partnered maintainers directly, but we don't open a direct support channel.

**Comment by dnesteryuk** [comment]
I would say, let's try :wink:

**Comment by myxoh** [comment]
Same here, although my time is not what is not what it used to for coding :(

**Comment by dblock** [comment]
I'm going to go ahead with this, will post anything related here.

**Comment by dblock** [comment]
We got $144 for April! I'm throwing a money throwing party :)
