### ISSUE TITLE
Renaming OperationId in Documentation Model Definition. 

### ISSUE THREAD

**Issue by James-Hopkins** [ruby-grape/grape#2035]
I'm trying to get the model name to change in my auto generated swagger documentation, it is currently the operation id.
I believe the way to do this is by using nickname. But when I try this it does nothing.
```
resource '/grandparent/:grandparentId/parent/:parentId/children' do
        desc 'Create a Child' do
          nickname 'addChild'
```

**Comment by dnesteryuk** [comment]
@James-Hopkins please, use [google group](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by magni-** [comment]
Thread in the Google group for those who end up here like me: https://groups.google.com/g/ruby-grape/c/hgCytbWqTuQ/m/CLbciqtWBQAJ
