### ISSUE TITLE
Get headers from outside Grape::API class

### ISSUE THREAD

**Issue by jbutler-lifefuels** [ruby-grape/grape#2052]
This is more of a question than issue/bug. I am looking a way to access the request headers from outside the api class. In the code below, 'Class' isnt always called from the api class, sometimes its called from a model so I dont want to just pass the headers all over the place and I dont see them in ENV.

Pseudo code:
```
Foo < Grape::API
  post do
    Class.do_something
  end
end

Class
  def do_something
    # do something with headers here
  end
end

```

**Comment by dblock** [comment]
`Class` knows nothing about Grape, so you'll have to pass headers into `do_something`. I recommend creating an instance of `Class` with whatever it needs, such as headers.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.
