### ISSUE TITLE
BigDecimal param conversion broke after upgrading from 1.1.0 to 1.3.3

### ISSUE THREAD

**Issue by GProst** [ruby-grape/grape#2074]
Previously (in 1.1.0) if an empty string was passed it was converted to `nil`
Now in 1.3.3 it keeps param as an empty string which isn't expected.

I'd expect it to either work as in 1.1.0 or at least return `400` status

**Comment by dblock** [comment]
Can you please try it against HEAD, I suspect this is fixed in https://github.com/ruby-grape/grape/pull/2067. If not, try writing a spec?

**Comment by GProst** [comment]
@dblock yeah, seems like it's fixed in master
When do you plan to release 1.4.0?

**Comment by dblock** [comment]
Add a +1 to https://github.com/ruby-grape/grape/issues/2030
