### ISSUE TITLE
`allow_blank` defaults to `false` ?

### ISSUE THREAD

**Issue by dramalho** [ruby-grape/grape#2075]
Hi guys

I've done a recent update and this kinda went bellow the spec radar - not anymore - until I saw some real life examples. I have one particular endpoint that's used externally - so I have little control over that - where I saw that a lot of optional params were being passed empty - `param1=&param2=&param3=annoy-david` and those were getting hit with 400 (`{"error"=>{"type"=>"invalid_parameter", "message"=>"does not have a valid value"}}`) so I tracked it down do `allow_blank` defaulting to false (the quick fix was really adding `allow_blank: true` on all my optional parameters). 

I think the change that did it - possibly - was [this](https://github.com/ruby-grape/grape/blame/c552813be09ace1d647566f464f6e27b32e0b44b/lib/grape/validations/validators/base.rb#L22) . The documentation doesn't hint at this, in fact the only reference to `allow_blank` is with two examples of when to use `allow_blank: false` - so I'm a bit confused here on what's the intention or if I'm just being thick (totally valid :) )

I upgraded from 1.2.5 to 1.3.2 - that's worth mentioning

**Comment by dblock** [comment]
It's possible that https://github.com/ruby-grape/grape/pull/2067 has fixed this. Can you please confirm against HEAD? If it doesn't work, try writing a spec.

**Comment by dramalho** [comment]
Maybe indirectly, but easy to test anyway - I'll do that

**Comment by dramalho** [comment]
That's it , I removed all the `allow_blank: true`s that I added, updated the gem, all is green . Any idea when it'll be officially released?

And thanks Daniel :)

**Comment by dblock** [comment]
Add +1 to #2030.
