### ISSUE TITLE
Empty arrays (as passed by her/faraday) are parsed as [nil]

### ISSUE THREAD

**Issue by PragTob** [ruby-grape/grape#2079]
:wave: 

And first thanks for all the work on the project! :green_heart: 

We have a grape API and applications talking to each other, for which we use [her](https://github.com/remi/her) which uses [faraday](https://github.com/lostisland/faraday).

At some point the faraday behavior changed for sending empty arrays https://github.com/lostisland/faraday/pull/801

The problem occurs when we use her to query resoruces `Resources::Something.where(param_name: [])`. It used to be that they were omitted (at least as URL params, unsure) but now they are sent as `param_name[]` in the URL, which is a bugfix. Grape parses this as `[nil]` which is not what I'd expect (I'd expect `[]`) and also then fails the parameter validation (we have a type of `Array[String]`). `allow_blank: true` doesn't help because an array with nil isn't blank (and we'd still have the wrong value to deal with).

We're running the latest grape release (1.3.3).

I'll work around the issue with `coerce_with` or defining my own type or something. Still thought it was worth opening an issue about it.

**Comment by dblock** [comment]
There was a bunch of work related to this in 1.4.0 (HEAD). I suggest writing a spec and seeing if master has fixed this?

**Comment by PragTob** [comment]
@dblock thanks for letting me know :) I have a bunch of specs for this. Let me see if it's fixed on main.

**Comment by PragTob** [comment]
@dblock just tried it out with 197d5b463b83c9417381837186d6dce7c6fd4ef0 - still exactly the same behavior for us.

**Comment by dnesteryuk** [comment]
@PragTob Could you add a spec for this bug, please? 

I've tried this in tests

```ruby
get '/required?cats[]='
```

`declared(params)` gave:

```ruby
{"cats"=>[""]}
```

**Comment by PragTob** [comment]
Morning @dnesteryuk !

I believe the difference is `=` vs. no `=` aka in our case we don't have the `=`/the way faraday/grape queries.

I'll add a PR with a spec (at least) just have to check whether I can do it on company time or if it's gotta be my own :)

**Comment by PragTob** [comment]
Failing spec etc. sits at #2080 now

**Comment by PragTob** [comment]
Moved to https://github.com/rack/rack/issues/1696 as it seems to me it's rather in rack.
