### ISSUE TITLE
Deprecation FileStreamer-like object

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2083]
Hi,

I would like stream attachments through grape. By reading the [doc](https://github.com/ruby-grape/grape#sending-raw-or-no-data), I can do this :

```ruby
class AttachmentStream
  attr_reader :response
  def initialize(response)
    @response = response
  end

  def each
    yield response.read_body
  end
end

source = URI(@attachment_context.url)
Net::HTTP.start(source.host, source.port, use_ssl: true) do |http|
  req = Net::HTTP::Get.new source
   http.request(req) do |res|
     stream AttachmentStream.new(res)
   end
end
```

Unfortunately, there is a warning that says :
```ruby
'[DEPRECATION] Argument as FileStreamer-like object is deprecated. Use path to file instead.'
```

Is is still relevant ?

Thanks

**Comment by dblock** [comment]
Are you reading 1.4.0 docs? https://github.com/ruby-grape/grape/pull/1520 has not been released yet.

**Comment by ericproulx** [comment]
I was reading on master branch, sorry :(
