### ISSUE TITLE
Release v. Next [add your +1 if you want us to]

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#2086]
Please add your +1 to release 1.5.0.

**Comment by magni-** [comment]
Would love a 1.4.1 release for https://github.com/ruby-grape/grape/issues/2087 🙇

**Comment by jdmurphy** [comment]
With the memory leak fixed, could you please cut a 1.4.1?

**Comment by bobbytables** [comment]
Yes please, sorry I'm so spammy today. But the Cache-Control header thing freaks me out with CDNs

**Comment by dblock** [comment]
I released 1.5.0.

**Comment by stanhu** [comment]
Would love v1.5.1 for https://github.com/ruby-grape/grape/pull/2116. I'd much rather see smaller releases than continue to pull in minor releases that create new issues.

**Comment by dblock** [comment]
> Would love v1.5.1 for #2116. I'd much rather see smaller releases than continue to pull in minor releases that create new issues.

Care to take a look at my comment in https://github.com/ruby-grape/grape/pull/2117#issuecomment-706424866?

**Comment by dblock** [comment]
Closing in favor of https://github.com/ruby-grape/grape/issues/2124
