### ISSUE TITLE
Grape v1.4.0 regression: Cache-Control is always set to no-cache

### ISSUE THREAD

**Issue by stanhu** [ruby-grape/grape#2087]
In Grape v1.4.0 https://github.com/ruby-grape/grape/pull/1520/files#diff-8e15cddb80f42ca7d43872846d80ecbeR275 broke our test suite because `Cache-Control` is always set to `no-cache` in https://github.com/ruby-grape/grape/blob/84d68bd3f92a3cffcb3bced8b387bf98779d61ef/lib/grape/dsl/inside_route.rb#L333. 

We set `Cache-Control` to `max-age=0, private, must-revalidate, no-store, no-cache`.

Maybe we should append`no-cache` only if isn't present? Or maybe the headers shouldn't be touched if `nil` is returned?

**Comment by stanhu** [comment]
I'm also not sure if overriding the `Content-Length` and `Transfer-Encoding` by default creates other issues.

**Comment by jarthod** [comment]
Got the exact same problem. Good to see it's already fixed :clap: waiting for the next release then ;)
