### ISSUE TITLE
Custom error for a custom type - coercion

### ISSUE THREAD

**Issue by kubaracek** [ruby-grape/grape#2093]
I'm having trouble returning a custom error when using custom coercion. My type is a bit more advanced hash which on its own holds `type` that can be of a few values and based on this value I'm doing validations of the rest of the hash.

The problem I'm experiencing is that when simply doing `fail "this attribute must be X"` in my class, grape returns default `X is invalid`. I'm catching the error before it reaches the user with `rescue_from Grape::Exceptions::ValidationErrors` but I don't seem to have the error in there to handle it properly.

My end goal is to be able to post a JSON as in the following example and have custom validations based on the type of the object, I've tried to do that with a `given` attribute, but that has it's own issues (which I think have been already reported here, it seems like the second `given` overrides the first)

```json
"foos": [
   { "type": "file",
     "fileName": "nameOfFile",
     "file64": "base64"
   },
   { "type": "note",
     "title": "hello world",
     "text": "Grape is good"
   }
]
```

my params block looks currently as

```ruby
params do
    requires :foos, type: Array, coerce_with: GrapeApi::V1::Types::Foo do
       requires :type, type: String, values: ["file", "note"]
    end
end
```

When I tried to change that to `given` without the coercion which would look as the following example, the validations are broken

```ruby
params do
    requires :foos, type: Array do
       requires :type, type: String, values: ["file", "note"]
       given type: ->(val) { val == "file"} do
          requires :fileName
          requires :file64
       end
       
       given type: ->(val) { val == "note"} do
          requires :title
          requires :text
       end
    end
end
```

What's the best way for me to implement this? the coercion kinda works, but I would like to communicate back to the user that for example the `title` is a required argument when the type is `note`. Currently what he gets is `foos is Invalid` which doesn't say much. Thank you

**Comment by kubaracek** [comment]
I'm just trying a custom type instead of the coercion but the `fail "hello world"` still produces the default `foo is Invalid`

```ruby
class Foo
	attr_reader :value
	def initialize(value)
		@value = value
	end
	def self.parse(value)
		fail "hello world"
		new(value)
	end
end

params do                            
  optional :foo, type: Array[Foo]  
end                                  
                                     
post :foo do                         
  params.inspect                     
end
```

**Comment by kubaracek** [comment]
Ok, found the reason here https://github.com/ruby-grape/grape/blob/master/lib/grape/validations/validators/coerce.rb#L73 the error handling does not care about the original error and raises the default coercion error. I might create a PR for that

**Comment by dblock** [comment]
Please. We should be bubbling up the inner exception.

**Comment by dnesteryuk** [comment]
@kubaracek @dblock I would do it this way https://github.com/ruby-grape/grape/compare/chore/custom-msg-in-invalid-value.

Initially, I thought about raising an exception and using the message of it, but it might give messages to users which must not leak.

For instance:

```
wrong number of arguments (given 1, expected 0)
```

So, developers explicitly need to return `Grape::Validations::Types::InvalidValue` to provide a custom message.

**Comment by dnesteryuk** [comment]
The attached PR provides a mechanism for providing custom messages:

```ruby
class Color
  def self.parse(value)
    return value if %w[blue red green].include?(value)

    Grape::Types::InvalidValue.new('Invalid color')
  end
end
```

It is a part of v1.5.2.
