### ISSUE TITLE
2.7 deprecation in middleware/stack.rb

### ISSUE THREAD

**Issue by Legogris** [ruby-grape/grape#2122]
This seems to be broken since 2.7.0:

```
grape-1.5.0/lib/grape/middleware/stack.rb:87: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
grape-1.5.0/lib/grape/middleware/stack.rb:11: warning: The called method `initialize' is defined here
```

Constructor:
https://github.com/ruby-grape/grape/blob/a28d37a9dc480266431e855cf670f038c54ef1d2/lib/grape/middleware/stack.rb#L11

Problematic calls (AFAICT):
https://github.com/ruby-grape/grape/blob/a28d37a9dc480266431e855cf670f038c54ef1d2/lib/grape/middleware/stack.rb#L75
https://github.com/ruby-grape/grape/blob/a28d37a9dc480266431e855cf670f038c54ef1d2/lib/grape/middleware/stack.rb#L87

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2123
