### ISSUE TITLE
Release 1.5.1

### ISSUE THREAD

**Issue by Legogris** [ruby-grape/grape#2124]
With the recent merges of #2123 and #2121 , grape should hopefully be fully 2.7-compatible. Would be great to have it published on ruby gems.

**Comment by dblock** [comment]
Can someone help with https://github.com/ruby-grape/grape/pull/2117#issuecomment-706424866 and maybe https://github.com/ruby-grape/grape/issues/2100#issuecomment-711987540 in the meantime?

**Comment by Legogris** [comment]
@dblock are those blockers due to https://github.com/ruby-grape/grape/pull/2116?

**Comment by dblock** [comment]
I'd like those addressed, but they aren't blocking. I'll get to a release at some point soon unless another maintainer does.

**Comment by darcang** [comment]
@dblock Hey, any plans to release it in near future? 😄

**Comment by dblock** [comment]
I'll get to a release at some point soon unless another maintainer does.

**Comment by dnesteryuk** [comment]
1.5.1 has been released.
