### ISSUE TITLE
empty array replaced by grape by [""]

### ISSUE THREAD

**Issue by seb-sykio** [ruby-grape/grape#2136]
hi
I have this

        desc "Create a new invoice"
        params do
          requires :invoice, type: Hash do
            optional :counter, type: String, desc: "counter of the invoice"
            requires :start_date, type: String, desc: "start_date of the invoice"
            optional :item_invoices_attributes, type: Array do
              requires :quantity, type: String, desc: "quantity of the invoice"
              requires :price_cents, type: String, desc: "price_cents of the invoice"
            end
          end
        end

and when I send this
"rack.request.form_vars"=>"invoices[][id]&invoices[][counter]&invoices[][start_date]=2020-10-01&invoices[][item_invoices_attributes][]=

@params={"invoices"=>[{"id"=>nil, "counter"=>nil, "start_date"=>"2020-10-01", "item_invoices_attributes"=>[""] 

ie an empty array is replaced by an array with an empty string.

Maybe someone know a way to work around?
Im using grape 1.2.5 and I can't update it cause I also use grape-swager and wine-bouncer which require grape < 1.3 

thanks

**Comment by dblock** [comment]
I think this comes from Rack parser, not from Grape. I would try with more recent versions of Rack and Grape to confirm that this isn't something we fixed, but most likely you'll want to pass JSON documents to the API and not do nested arrays on a query string because the Rack parser doesn't look at the `params` block.

**Comment by seb-sykio** [comment]
I dont do "nested arrays on a query string" 
I use post with json data

```

      it "creates an invoice" do
        post "/api/v1/invoices/bulk", @form_data
        json = json(response.body)
    end
```

**Comment by dblock** [comment]
I don't see a content-type header here, in a spec this would be

```ruby
post '/api/v1/invoices/bulk', @form_data.to_json, 'CONTENT_TYPE' => 'application/json'
```

**Comment by seb-sykio** [comment]
thanks. actually I fixed this by adding ", as: :json"  like this

post "/api/v1/invoices/bulk", @form_data, as: :json

**Comment by dblock** [comment]
Where's that syntax coming from? Rails? Something else? Appreciate any updates to the documentation (we do document content-type).

**Comment by seb-sykio** [comment]
rails / rspec
