### ISSUE TITLE
is it possible to make an api path prefix optional?

### ISSUE THREAD

**Issue by tansaku** [ruby-grape/grape#2138]
in the process of splitting up an API into public and private components, we want to add a `public` prefix to the API path, but we'd like it to be optional while we are in the process of changing over.  Is that possible with the grape `prefix` keyword? e.g.

```rb
prefix :public, optional: true
```

**Comment by dblock** [comment]
I don't think you can make a prefix optional, but have you tried mounting the same API into two locations?

```ruby
namespace :public do
  mount MyAPI
end
mount MyAPI
```

**Comment by tansaku** [comment]
That sounds like a great idea - it certainly leaves the original paths intact.  However I'm not seeing the same endpoints available with a `public/` prefix ... maybe something else in our app ... 

I've managed to get it working with:

```rb
mount MyAPI => '/public/myapi'
mount MyAPI => '/myapi'
```

not sure why the namespace didn't seem to work for us - maybe because we're using these named paths ...?

**Comment by dblock** [comment]
I'll close this since that's definitely a solution, but if you have time maybe write a spec and reopen if my suggestion doesn't work, that would be a bug.
