### ISSUE TITLE
ArgumentError: Representation of type ... cannot be merged

### ISSUE THREAD

**Issue by ksimmi** [ruby-grape/grape#2148]
Hi! 

I have a representation bug on my production. The bug happens very seldom it may be one or two times in a week and me with my colleagues have never got it on development env. After some research I managed to reproduce similar error. 

```
clase API::V1::ExampleEntity < Grape::Entity
...
end

class API::V1::Routes::Example < Grape::API
  namespace :slug do
    desc 'Bug reproducing' do
      entity API::V1::ExampleEntity
    end
    get do
      present TestModel.first, with: API::V1::ExampleEntity
    end
  end  
end  
```
This code works fine without the error, but when I duplicate `present` line I got `ArgumentError: Representation of type API::V1::ExampleEntity cannot be merged`
```
class API::V1::Routes::Example < Grape::API
  ...
    get do
      present TestModel.first, with: API::V1::ExampleEntity
      present TestModel.first, with: API::V1::ExampleEntity
    end
  ...
  ```
  
  It happens because of one if-condition in `grape/dsl/inside_route.rb`
  ```
        def present(*args)
        ...
        elsif entity_class.present? && body
          raise ArgumentError, "Representation of type #{representation.class} cannot be merged." unless representation.respond_to?(:merge)
          representation = body.merge(representation)
        end
        ...
```
When `present` was called at first time `@body` is nil, and the condition is ignoring. When `present` happens at second time the `@body` already contains value and in this case `@body` and representation are the same class.

Maybe my research has no real value and situation on my production has different cause but I need help for resolve described problem.

P.S. Grape 1.5.1 + Rails 6.0.3

**Comment by dblock** [comment]
Multiple `present` statements get merged in a single response. It sounds like your code has set a response earlier.

What should Grape do with that? If you want to replace the current response, a `body nil` would work around that I think, but you probably want to flow your response better and not set a body in the first place.

Does this help?

**Comment by ksimmi** [comment]
Thank you for your reply, it was informative and looks like my code really set response earlier. I got logs from my production and it looks like my server handle the same request twice in the same process. 

> I, [2021-01-20T07:41:59.383601 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Started GET "/api/v2/player/phone" at 2021-01-20 07:41:59 +0000
> I, [2021-01-20T07:41:59.383687 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Processing by ...
> I, [2021-01-20T07:41:59.383471 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Started GET "/api/v2/player/phone" at 2021-01-20 07:41:59 +0000
> I, [2021-01-20T07:41:59.384916 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Processing by ...
> I, [2021-01-20T07:41:59.398780 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Completed GET "/api/v2/player/phone" 200 OK in 15.52ms
> I, [2021-01-20T07:41:59.403410 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562]   ArgumentError: Representation of type API::V2::Entities::Phone cannot be merged.
> I, [2021-01-20T07:41:59.403629 #24299]  INFO -- : [67cd89399b04686fcf7102f3a45d3b9c] [user_id:3966562] Completed GET "/api/v2/player/phone" 500 Internal Server Error in 24.65ms

**Comment by dblock** [comment]
I would like to hear what causes it when you find it, and ensure that it's not something legit, like a keep-alive session, that is keeping state across requests. Will close for now.
