### ISSUE TITLE
Typo in descripcion

### ISSUE THREAD

**Issue by matiasasis** [ruby-grape/grape#2155]
https://github.com/ruby-grape/grape/blob/e7f771e63359e54e2cb0feb7ff52b9746fe13e05/lib/grape/api.rb#L90

**Comment by dblock** [comment]
PR a fix please?

**Comment by matiasasis** [comment]
Will submit PR. I'm checking all files.

**Comment by matiasasis** [comment]
PR here: [#2158](https://github.com/ruby-grape/grape/pull/2158)

**Comment by dblock** [comment]
It helps!
