### ISSUE TITLE
How to: Overwrite default String coercion

### ISSUE THREAD

**Issue by DmytroVasin** [ruby-grape/grape#2166]
Could you suggest how we could overwrite the default coercion of a String?

Here we have standard usage of grape

The requirement is to strip all Strings that we are faced with in-app.

```ruby
requires :first_name, type: String
```

We can solve this problem with:

```ruby
requires :first_name, type: String, coerce_with: ->(value) { value.strip }
```

Of course, we can create a new type StripString, but we want to apply this change for all `String`.

Could you suggest how to overwrite the standard coercion type? Is it possible to do?

**P.S.**
Sorry for this Issue requests - but I did not know where to ask

**Comment by dblock** [comment]
AFAIK there's no standard way to override coercion for a type like String "by default". You could extend coercion in (see https://github.com/ruby-grape/grape/blob/e7f771e63359e54e2cb0feb7ff52b9746fe13e05/lib/grape/validations/params_scope.rb) to allow for something like this. The most reliable and clean way today would probably be a custom `StripString` as you suggest - it's a one time change for parameter declarations and doesn't have any side effects.

The other option I see is to write a middleware that looks through params and calls `strip` on them before anything gets to Grape or its coercion/types system.

I'll close this. Please use [the Grape mailing list](https://groups.google.com/forum/#!forum/ruby-grape) for questions.

**Comment by dblock** [comment]
Btw, I am not opposed to a feature that lets you override coercion for all fields of a given type. You could give it a shot.
