### ISSUE TITLE
env['api.format'] does not override formatter set by content-type 

### ISSUE THREAD

**Issue by waynerobinson** [ruby-grape/grape#2171]
In reference to #1989 (sorry, I have commented in there before I realised the issue was closed).

I'm having exactly the same issue.

If this is used:

```ruby
env['api.format'] = :binary # or :txt
content_type 'application/json' # or header 'Content-Type', 'application/json'
{key: 123}.to_json
```

Then it still calls the JSON formatter. If the `content_type` method is left off, it doesn't.

Here is an example using grape-on-rack:

https://github.com/waynerobinson/grape-on-rack

Please take a look at the extra methods added to `Acme::Ping`.

The only one that doesn't call the JSON formatter is the one where the content type is set to `text/plain`.

**Comment by waynerobinson** [comment]
It looks like the value of the content type overrides the format. See https://github.com/ruby-grape/grape/blob/02d7113d09eb9fcb4264c841d1fdd305e3e8adb5/lib/grape/middleware/formatter.rb#L55

I'm not sure what the safest way is to reverse this?

**Comment by waynerobinson** [comment]
If this test shows the intended behaviour, I don't think we'll be able to override the output by just changing the order the `api_format` is looked up in.

https://github.com/ruby-grape/grape/blob/7741f022b5928f0ddcee27de08555d95ea4556f8/spec/grape/api_spec.rb#L3732-L3739

If we did, it would break the behaviour where there is an explicit format set, but the implementation expects to be able to override it by changing the content type.

For example:

```ruby
format :json

def action
  content_type "text/plain"
  "plain text"
end
```

would still output as JSON if we reversed the lookup to `api_format = env[Grape::Env::API_FORMAT] || mime_types[headers[Grape::Http::Headers::CONTENT_TYPE]]` because it would always pull out `:json` first.

I don't think there's any non-breaking way to override the behaviour of one of the content-type associated formatters at the moment on a per-request basis.

**Comment by iabdulin** [comment]
here's my use case:
I build JSON in the database and want to return it as is, no additional formatting is needed

**Comment by waynerobinson** [comment]
Yeah. Our use case is similar. We have cached data that's already JSON that we'd like to just return vs having to parse and re-encode. 

I'll take a look at starting a PR tomorrow with some options. 👍

**Comment by trialize** [comment]
There is an issue with order of conditions in **Grape::Middleware::Formatter.fetch_formatter**

Original code:
`      
      def fetch_formatter(headers, options)
        api_format =  mime_types[headers[Grape::Http::Headers::CONTENT_TYPE]] || env[Grape::Env::API_FORMAT]
        Grape::Formatter.formatter_for(api_format, **options)
      end
`

Should be:
`
      def fetch_formatter(headers, options)
        api_format = env[Grape::Env::API_FORMAT] || mime_types[headers[Grape::Http::Headers::CONTENT_TYPE]]
        Grape::Formatter.formatter_for(api_format, **options)
      end
`

This would ensure that it'd correctly pick up content-type for your custom formatters.
Example:

`
  content_type :raw_json, 'application/json'
  formatter :raw_json, ->(object, _env) { object }
`

`
get do
        env['api.format'] = :raw_json
        body <<HERE
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
HERE
end
`

**Comment by dblock** [comment]
The PR in https://github.com/ruby-grape/grape/pull/2505 fixes the issue but is not being finished. If anyone here wants to take it on, we would appreciate it!

**Comment by ericproulx** [comment]
@dblock you might want to check my PR #2506

**Comment by ericproulx** [comment]
@dblock I think we should add a feature to return unformatted data aka `raw` data. Lots of people already have some already formatted JSON and there's no need to reformat it again obvisouly. Setting `binary` seems wrong to me and setting `:json` will still call the JSON formatter.

It's kind of a combination of `content_type` and setting `raw: true`

**Comment by dblock** [comment]
@ericproulx It's not a bad idea, let's see it. If I understand correctly you want something that would bypass a formatter, and it makes sense because the intent of all these existing methods is to set a content-type along with data (`binary` should be (is?) `binary/octet-stream`).
