### ISSUE TITLE
`type: Hash` (with arbitrary keys and value types) converts all values to strings

### ISSUE THREAD

**Issue by mcmegavolt** [ruby-grape/grape#2172]
I want to declare a freeform Hash param like this:
```
optional :properties, type: Hash
```
when I do request (with RSpec test) and pass this:
```
{
  properties: {
    num: 1,
    arr: [1, 2, 3],
    bool: true
  }
}
```
I get this in Grape endpoint:
```
params[:properties] =>
{
  num: "1",
  arr: ["1", "2", "3"],
  bool: "true"
}
```

this is a disaster, it is impossible to work with it (((

can anyone help me to handle this, please?

**Comment by dblock** [comment]
You could declare the inner hash with specific types for `num`, `arr` and `bool` and Grape will attempt to cast strings to those. 

However, which content-type are you POSTing this with in your RSpec test? Try sending as JSON (which is how your API will be used). Does this exhibit the same behavior?

**Comment by mcmegavolt** [comment]
@dblock
You were right, I forgot to convert body hash into JSON, also missed the "Content-Type" header ((((
Thanks!
