### ISSUE TITLE
Grape version 1.3.3 can not encode file name in UTF-8 properly

### ISSUE THREAD

**Issue by chiwenchen** [ruby-grape/grape#2181]
I recently upgrade grape from version `1.1.0` to `1.3.3`
but when I upload a file with Chinese file name using grape api, I got this UTF-8 coded filename like this
```
{
              "file" => {
        "filename" => "\xE9\xA2\xA8\xE6\x99\xAF.jpeg",
            "type" => "\"image/jpeg\";charset=utf-8",
            "name" => "file",
        "tempfile" => #<Tempfile:/var/folders/0f/dpffhyw55115qsffs377wjy80000gp/T/RackMultipart20210712-29718-1ss0cd4.jpeg>,
            "head" => "Content-Disposition: form-data; name=\"file\"; filename=\"\xE9\xA2\xA8\xE6\x99\xAF.jpeg\"; filename*=UTF-8''%E9%A2%A8%E6%99%AF.jpeg\r\nContent-Type: \"image/jpeg\";charset=utf-8\r\n"
    }
}
```

when in version 1.1.0, it looks like this
```
{
              "file" => {
        "filename" => "風景.jpeg",
            "type" => "\"image/jpeg\";charset=utf-8",
            "name" => "file",
        "tempfile" => #<Tempfile:/var/folders/0f/dpffhyw55115qsffs377wjy80000gp/T/RackMultipart20210712-56860-1w9zuw3.jpeg>,
            "head" => "Content-Disposition: form-data; name=\"file\"; filename=\"\xE9\xA2\xA8\xE6\x99\xAF.jpeg\"; filename*=UTF-8''%E9%A2%A8%E6%99%AF.jpeg\r\nContent-Type: \"image/jpeg\";charset=utf-8\r\n"
    }
}
```

I tried to add `chartset=utf-8` to my content type header, but it did not work, can anyone helps on how to get the result like the old version, thanks in advance.

**Comment by dblock** [comment]
Try turning this into a spec?

**Comment by chiwenchen** [comment]
@dblock not quite sure what requires for a spec.

**Comment by dblock** [comment]
> @dblock not quite sure what requires for a spec.

You are saying that something worked in 1.0 and doesn't work in 1.3. Write a test that worked in 1.0 and doesn't work in 1.3 and we can (help) fix.

**Comment by dblock** [comment]
> @dblock not quite sure what requires for a spec.

You are saying that something worked in 1.0 and doesn't work in 1.3. Write a test that worked in 1.0 and doesn't work in 1.3 and we can (help) fix.

**Comment by chiwenchen** [comment]
Hi @dblock , I finally found that the issue is cause by the new version of rack (2.2.3), and I already open a https://github.com/rack/rack/pull/1762 try to fix it.

**Comment by dblock** [comment]
Great. I'll close this.
