### ISSUE TITLE
`values` validator and `allow_blank`

### ISSUE THREAD

**Issue by maciejpankanin** [ruby-grape/grape#2185]
Consider this params definition:
```
params do
  requires :id, type: String
  optional :some_param, type: String, values: ["value1", "value2"]
end
```

Recently I spent couple of hours figuring out why `null` is valid value for `some_param`.

I think there should be a few words in documentation about `values` validator saying that `allow_blank` defaults to `true` and it is stronger than supplied `values` options.

**Comment by dblock** [comment]
Make sense, please contribute! Also double check that we have specs for this exact behavior.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2186

**Comment by flosacca** [comment]
I was confused by the fact that the empty string is not a special case that is allowed by default. I've tested the following example mentioned in `README` and an empty string cannot pass.
```ruby
params do
  requires :state, type: Symbol, values: [:active, :inactive]
end
```

There may be a misunderstanding in the original problem. When `optional` is used, `null` would be allowed unless `allow_blank` is explicitly specified to `false`.

I found that `allow_blank: false` enables `AllowBlankValidator` while `allow_blank: true` actually does nothing. So, whether an empty string is allowed by default depends totally on other factors.

**Comment by maciejpankanin** [comment]
Ops, you are right, I think it should be:
```ruby
params do
  optional :state, type: Symbol, values: [:active, :inactive]
end
```

But still, isn't it misbehavior? If I understand it well, when it is `optional` and I send `null` or `''` validation will pas but if it was `requires` I would get a validation error.

It behaves like `null` or empty strings weren't values.

**Comment by dblock** [comment]
Current behavior looks suspicious to me: I certainly don't expect an optional value to allow an empty string. Try writing a spec for this, fixing it and seeing if any other specs fail?
