### ISSUE TITLE
Example custom validator shown in README breaks in Ruby 3

### ISSUE THREAD

**Issue by hkockerbeck** [ruby-grape/grape#2188]
The `README` shows an example for a custom validator
```ruby
class AlphaNumeric < Grape::Validations::Base
  def validate_param!(attr_name, params)
    unless params[attr_name] =~ /\A[[:alnum:]]+\z/
      fail Grape::Exceptions::Validation, params: [@scope.full_name(attr_name)], message: 'must consist of alpha-numeric characters'
    end
  end
end
```

In Ruby 2.7.2, this works just fine. In Ruby 3.0.0, however, an invalid parameter value breaks my test API with the following error:
```
ArgumentError: wrong number of arguments (given 1, expected 0; required keyword: params)
	/home/henning/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/grape-1.5.3/lib/grape/exceptions/validation.rb:11:in `initialize'
	/home/henning/Playground/ruby/test.rb:8:in `exception'
	/home/henning/Playground/ruby/test.rb:8:in `fail'
	/home/henning/Playground/ruby/test.rb:8:in `validate_param!'
```
It looks like the `Grape::Exceptions::Validation` object doesn't receive the keyword argument `params` properly. This probably is because of the superfluous comma in the call to `fail`. Because, according to the style guide, [`raise` should be favored over `fail`](https://github.com/rubocop/ruby-style-guide/issues/512), I'd suggest to change the example from

```
fail Grape::Exceptions::Validation, params: [@scope.full_name(attr_name)], message: 'must consist of alpha-numeric
```

to 

```
raise Grape::Exceptions::Validation.new params: [@scope.full_name(attr_name)], message: 'must consist of alpha-numeric characters'
```

The new version worked in my tests with Ruby 2.7.2, 3.0.0, 3.0.1 and 3.0.2.

**Comment by dblock** [comment]
Thanks for bringing this up! Please contribute?

1. Make sure we have a spec that replicates the example and that it runs in Ruby 3.0.
2. Make the change in README.
