### ISSUE TITLE
Dry-types version 1.5.1

### ISSUE THREAD

**Issue by szysza** [ruby-grape/grape#2215]
Hey, I wanted to ask if there are any plans with upgrading dry-types from version `>= 1.1` to version `1.5.1` (which is currently the latests version)? We're using grape in our project as well as dry-types and can't update it. If you'll need any help then go ahead and let me know, I don't know the internals of grape, but hope that this will be an easy change.

I also wanted to thank all of the maintainers for working on this library. We do appreciate your work

**Comment by dnesteryuk** [comment]
If you run:

```
bundle update dry-types
```

it will be updated in your project. We use Grape 1.6.0 with Dry-types 1.5.1 on production.

**Comment by dblock** [comment]
https://github.com/ruby-grape/grape/blob/master/grape.gemspec#L25 says >= 1.1, closing

**Comment by szysza** [comment]
I've missed the `>` part of it. Thanks once again.
