### ISSUE TITLE
undefined method `multiple?' for Grape::Validations::Types:Module

### ISSUE THREAD

**Issue by cristofer** [ruby-grape/grape#2221]
Hey guys,

`build(deps): bump grape from 1.6.0 to 1.6.1`

This PR https://github.com/ruby-grape/grape/pull/2209 introduced this check https://github.com/ruby-grape/grape/pull/2209/files#diff-e97e1900db45e8b2dbf58e1a31c80ca18d47fe7d7a2ae27a6c98a076c6936b18R177, which breaks in our CI:

```
/home/circleci/repo/vendor/bundle/ruby/2.6.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:359:in `infer_coercion'
/home/circleci/repo/vendor/bundle/ruby/2.6.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:274:in `validates'
/home/circleci/repo/vendor/bundle/ruby/2.6.0/gems/grape-1.6.1/lib/grape/validations/params_scope.rb:195:in `validate_attributes'
/home/circleci/repo/vendor/bundle/ruby/2.6.0/gems/grape-1.6.1/lib/grape/dsl/parameters.rb:135:in `requires'
```

I went through the loads specified here https://github.com/ruby-grape/grape/pull/2209/files#diff-b56aab6c58cef370018ab45d697b38247b363bf034afcd2e4b4d9fff05c3de0eR230 , and indeed couldnt find anything that could make a reference to `multiple?`

Please let me know if you need anything else in order to reproduce the problem.

Thank you for your great work!

**Comment by cristofer** [comment]
NVM, I just saw the fix here https://github.com/ruby-grape/grape/pull/2219, thanks for the quick reaction to that

**Comment by dblock** [comment]
@dm1try should we yank 1.6.1 from rubygems? is everybody running into this?

**Comment by dm1try** [comment]
@dblock maybe, it's a new experience :)
though,  the upgrade to 1.6.2 should work for most users.
