### ISSUE TITLE
Question about rack2 and rails_6 appraisals

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2224]
<img width="514" alt="Screen Shot 2022-01-02 at 19 01 44" src="https://user-images.githubusercontent.com/8418467/147885193-bfacc1bd-2ad5-46d3-9cb8-470c2acdb3c9.png">
<img width="475" alt="Screen Shot 2022-01-02 at 18 56 48" src="https://user-images.githubusercontent.com/8418467/147885195-01932b9b-f956-4733-93d1-527923bafec8.png">

I found that `rack2` and `rails_6` files are running the same version as the `rack2_2` and `rails_6_1`. Is it worth fixing ?

**Comment by dblock** [comment]
Probably yes.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2225
