### ISSUE TITLE
1.6.0 -> 1.6.1 contains breaking change

### ISSUE THREAD

**Issue by ro-savage** [ruby-grape/grape#2230]
Our automated tests are showing

```
rake aborted!
NameError: uninitialized constant Grape::Validations::Base
```

It appears this commit https://github.com/ruby-grape/grape/commit/937b2fc8a7081c5eb74ff8a4a760e30ebabbd780 changed the path from `Grape::Validations::Base` to `Grape::Validations::Validators:Base`

**Comment by dm1try** [comment]
yeah, sorry for that. 

sadly, after the release I [noticed](https://github.com/ruby-grape/grape/pull/2200#issuecomment-1003264156) that the `UPGRADING.md` had not been updated in #2200. so I didn't expect any breaking change from such refactoring.

I'm closing, there is nothing we can do here.

**Comment by dm1try** [comment]
though, we can create a patch for compatibility with 1.6.0 and up a minor version
```ruby
Grape::Validations::Base = Grape::Validations::Validators:Base
```

**Comment by ro-savage** [comment]
@dm1try - We've updated our codebase to use `Grape::Validations::Validators:Base`
But I think it make sense to release `1.6.3` that contains this - so that the latest 1.6.x isn't a breaking change from 1.6.0

**Comment by dblock** [comment]
> @dm1try - We've updated our codebase to use `Grape::Validations::Validators:Base`
> But I think it make sense to release `1.6.3` that contains this - so that the latest 1.6.x isn't a breaking change from 1.6.0

This was a miss. Care to PR this fix @ro-savage ?

**Comment by ro-savage** [comment]
@dblock - Unfortunately I am not a ruby developer, I actually wouldn't know where to put the alias.

**Comment by Jack12816** [comment]
:( Breaking change in a patch version. This does not only affect `Grape::Validations::Base`, but also users who extended existing built-in validators or compositions of it. This is even worse for external package maintainers who rely on the constants.

**Comment by dblock** [comment]
Agreed. Can someone please PR a fix? @dm1try ?

**Comment by dm1try** [comment]
@dblock take a look at #2244
