### ISSUE TITLE
Ruby 3.0 breaks on `use` usage

### ISSUE THREAD

**Issue by mobilutz** [ruby-grape/grape#2231]
We have the following (pseudo) code

```
module BaseHelper
  extend Grape::API::Helpers

  params :type do |type:|
    type = type.to_s
    requires :type,
             type: String,
             values: { value: [type], message: "must have the value `#{type}`" }
  end
end

class API < Grape::API
  helpers BaseHelper

  desc 'Missing keyword error'
  params do
    use :type, type: :api
  end
  get 'error' do
    'This throws a missing keyword error in Ruby 3.0'
  end
end
```

When upgrading from ruby 2.7.5 to 3.0.3 the `use :type, type: :api` line leads to the following error:
```
`block in <module:BaseHelper>': missing keyword: :type (ArgumentError)
```

I created a repo which shows this error: https://github.com/mobilutz/grape-ruby3

With ruby 2.7.5 the error is not thrown and we are using the code successfully on production.

As far as I know, there are some `ArgumentError` raised in 3.0.3 but the ones I found do not correlate to the implementation detail here:
https://www.fastruby.io/blog/ruby/upgrades/upgrade-ruby-from-2.7-to-3.0.html#language-changes

Is there something else needed to debug this?

**Comment by dm1try** [comment]
it looks like we need "double splat" for `options` [here](https://github.com/ruby-grape/grape/blob/master/lib/grape/dsl/parameters.rb#L65).

**Comment by mobilutz** [comment]
Thanks @dm1try for the quick fix.

I stumbled over the missing `**` this morning as well, but you have been faster 😉
