### ISSUE TITLE
Top level route param and lower level namespace

### ISSUE THREAD

**Issue by zellnerFinstreet** [ruby-grape/grape#2240]
It seems like there is a problem with lower level namespace endpoints, when there is a top level endpoint of the same kind (PATCH in this case) that uses a route param.

```
class Test < Api
  resources :test do
    desc("top level test")
    params do
      requires :top_level_param_one, type: Boolean
      requires :any_route_param, type: Integer
    end
    route_param :any_route_param do
      patch do
        "top_level"
      end
    end

    namespace :lower_level_namespace do
      desc("lower level test")
      params do
        requires :lower_level_param_one, type: Boolean
      end
      patch do
        "lower_level"
      end
    end
  end
end
```

**Expected Result:**
A `PATCH` call to `/test/lower_level_namespace` with `lower_level_param_one` param set, should be successful

**Actual Result:**
```
{
  "error": "top_level_param_one is missing, any_route_param is invalid"
}
```

The lower level endpoint requires the params from the top level endpoint. When I remove the route_param from the top level endpoint everything works fine, so it seems like it is caused by the route_param.

I am using `grape-swagger` and `grape-swagger-rails` as well and in Swagger it looks like this:

![image](https://user-images.githubusercontent.com/39985620/153609731-6667bc60-2f57-4536-ad45-215a4858d526.png)

Is this a bug?

**Comment by dm1try** [comment]
> The lower level endpoint requires the params from the top level endpoint. When I remove the route_param from the top level endpoint everything works fine, so it seems like it is caused by the route_param.

yeah, because the request to `/tests/lower_level_namespace` have been processed  as the request to `tests` resource with `id` equal `lower_level_namespace`.

AFAIK, routes are matched in order they are defined.

**Comment by zellnerFinstreet** [comment]
You are right and that totally makes sense. When I change the order of the endpoints it works fine, besides one case:

<img width="980" alt="image" src="https://user-images.githubusercontent.com/39985620/153616636-a22f6807-e3dd-4036-af58-d17b6a297fae.png">

And that proves your point 💡 

Thanks for the quick help 👍

**Comment by dblock** [comment]
Should we close this?

**Comment by zellnerFinstreet** [comment]
Yep, from my side everything is clear. Thanks again 👍
