### ISSUE TITLE
Datatype for Structured Hash Inside Hash Param?

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#2242]
Is it possible to define a hash that takes any key, but the content of the hash is structured JSON data?

For example:

```
{
  "student1": { "first_name": "Bob", "last_name": "Smith", "grade": "99" },
  "student2": { "first_name": "Alice", "last_name": "Jones", "grade": "95" },
  "student3": { "first_name": "John", "last_name": "Doe", "grade": "97" },
  "student4": { "first_name": "Larry", "last_name": "Brown", "grade": "92" }
}
```

I know this works with arrays, but can this be achieved with a hash? The current Hash datatype seems to require you to define the keys beforehand (`student1`, `student2`, `student3`,`student4`).

```
  optional :student, type: Hash do
    optional :first_name, type: String
    optional :last_name, type: String
    optional :grade, type: String
  end
```
However this only allows for a single student, not the student inside the hash.

**Comment by dblock** [comment]
Are you looking or for [custom types](https://github.com/ruby-grape/grape#custom-types-and-coercions)?

**Comment by dm1try** [comment]
> Is it possible to define a hash that takes any key, but the content of the hash is structured JSON data?

Nope.

It depends on the context of  a specific problem, but if you just need an ability to process such Hash data(for example some client sends data in such format and it's hard to change the behavior) then `Array` type in conjunction with `coerce_with` could be used.

**Comment by dm1try** [comment]
```ruby
    it do
      subject.params do
        optional :students, type: Array, coerce_with: ->(data) { data.values } do
          optional :first_name, type: String
          optional :last_name, type: String
          optional :grade, type: String
        end
      end
      subject.get('/students') { params[:students] }
      get '/students', students: {
        "student1": { "first_name": "Bob", "last_name": "Smith", "grade": "99" },
        "student2": { "first_name": "Alice", "last_name": "Jones", "grade": "95" },
        "student3": { "first_name": "John", "last_name": "Doe", "grade": "97" },
        "student4": { "first_name": "Larry", "last_name": "Brown", "grade": "92" }
      }

      expect(last_response.status).to eq(200)
      expect(last_response.body).to eq('[{"first_name"=>"Bob", "last_name"=>"Smith", "grade"=>"99"}, {"first_name"=>"Alice", "last_name"=>"Jones", "grade"=>"95"}, {"first_name"=>"John", "last_name"=>"Doe", "grade"=>"97"}, {"first_name"=>"Larry", "last_name"=>"Brown", "grade"=>"92"}]')
    end
```
P.S. Thanks Copilot for helping me generating the spec^

**Comment by jonmchan** [comment]
@dm1try thanks - yes this is exactly the use case I am looking for. Copilot is awesome! :+1: 

@dblock I would be interested in arbitrary key names which I don't think would work with your examples.

Small update, is I would like the id field which is the key name in the hash. This solution I believe would work for me:

```
    it do
      subject.params do
        optional :students, type: Array, coerce_with: ->(data) { data.map do |k,v| v.merge!(id: k); end } do
          optional :first_name, type: String
          optional :last_name, type: String
          optional :grade, type: String
          optional :id, type: String
        end
      end
      subject.get('/students') { params[:students] }
      get '/students', students: {
        "student1": { "first_name": "Bob", "last_name": "Smith", "grade": "99" },
        "student2": { "first_name": "Alice", "last_name": "Jones", "grade": "95" },
        "student3": { "first_name": "John", "last_name": "Doe", "grade": "97" },
        "student4": { "first_name": "Larry", "last_name": "Brown", "grade": "92" }
      }

      expect(last_response.status).to eq(200)
      expect(last_response.body).to eq('[{"first_name"=>"Bob", "last_name"=>"Smith", "grade"=>"99", "id" => "student1"}, {"first_name"=>"Alice", "last_name"=>"Jones", "grade"=>"95", "id" => "student2"}, {"first_name"=>"John", "last_name"=>"Doe", "grade"=>"97", "id" => "student3"}, {"first_name"=>"Larry", "last_name"=>"Brown", "grade"=>"92", "id" => "student4"}]')
    end
```

If there are no plans for additional support for this functionality in the library, we can close this issue. This solution is sufficient.

**Comment by dm1try** [comment]
> @dm1try thanks - yes this is exactly the use case I am looking for

I'm glad it helped. 

> If there are no interest for additional support for this functionality in the library, we can close this issue. This solution is sufficient.

In addition to @dblock's comment we could extend mapping support for collection types and use DSL like this: `type: Array[String => Student]` but this requires more thinking.

let's close for now)
