### ISSUE TITLE
Handling complex validations question

### ISSUE THREAD

**Issue by rpoole** [ruby-grape/grape#2245]
Hi! I'm looking into using this library, but I'm wondering if there's any support for handling complex validations? Imagine something that might involve checking multiple parameters and can't be supported through the DSL. The built in stuff is great and I love that it's in one place.

Is there a clean way to basically do something like the following?

```ruby
class API < Grape::API
  namespace :test do
    params do
      optional :items, default: {}
      optional :sort_direction
      optional :sort_col
      optional :name, type: String, length: 10
    end
    validate_items do |items|
      # some validations using just items
    end
    validate do |params|
      # some validations using above params in a very complex way that can't be done with the built in helpers
    end
    get do
      # more code here
    end
  end
end
```

Defining custom validations seems like it could work but it'd be ugly. I'd have to group all my params and then create a custom validator per endpoint which feels kind of ugly.

If you're familiar with python/Django rest framework, it'd be similar to a validation provided here:
https://www.django-rest-framework.org/api-guide/serializers/#object-level-validation - you define your params with some built in validations above, but have the flexibility to do whatever you need below.

**Comment by dm1try** [comment]
It totally depends on the context. 
If "complex" means some business specific validation when it's usually done on a different level:
```ruby
helpers do
  def validate_test_items!
     ...
  end 
  
  def validate_test_object!
     ...
  end   
end

get do
  validate_test_items!
  validate_test_object!
  
  run
end 
```
or 
```ruby
helpers do
  def vallidation_error!(object_errors)
    ...
    error!(400, ...)
  end
end
    
get do
   object = TestObject.from_params(params)
   object.validate
   if object.has_errors?
     vallidation_error!(object.errors)
   else 
     object.run
   end
end 
```
btw, in the reference validation is performed in the serializer.

**Comment by rpoole** [comment]
Thanks for the info!
