### ISSUE TITLE
set custom message when using proc to validate value

### ISSUE THREAD

**Issue by blainejohnson17** [ruby-grape/grape#2280]
How can I use a proc to validate and use a custom message?

This way is deprecated:
```ruby
params do
  requires :e, values: { proc: -> (v) { v.even? }, message: 'must be even' }
end
```

The new way doesn't support a custom message:
```ruby
params do
  requires :e, values: -> (v) { v.even? }
end
```

**Comment by dblock** [comment]
I don't believe it's possible. Would be a good feature to add.

**Comment by blainejohnson17** [comment]
@dblock , what do you think about enhancing the `values[:value]` to allow proc with arity 1 to support this use case?
```
params do
  requires :e, values: { value: -> (v) { v.even? }, message: 'must be even' }
end
```

**Comment by dblock** [comment]
I like it. Give the code a try?

**Comment by blainejohnson17** [comment]
sure, I'll give it a go.

**Comment by TheDevJoao** [comment]
Turns out my PR description didn't close this automatically after the merge, @dblock could you close this for us?
