### ISSUE TITLE
Faraday::SSLError on Heroku

### ISSUE THREAD

**Issue by DanTaiko** [ruby-grape/grape#2283]
I had an SSL issue on **Heroku Stack 22**
`Started GET "/api/status" for 188.169.240.73 at 2022-10-07 07:46:43 +0000
caught error of type Faraday::SSLError in after callback inside Grape::Middleware::Formatter : SSL_CTX_load_verify_file: system lib
E, ERROR -- : Faraday::SSLError: SSL_CTX_load_verify_file: system lib
  /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:1040:in "initialize"
  /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:1040:in "new"
  /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:1040:in "connect"
  /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:976:in "do_start"
  /app/vendor/ruby-3.1.2/lib/ruby/3.1.0/net/http.rb:965:in "start"
  /app/vendor/bundle/ruby/3.1.0/gems/faraday-net_http-3.0.0/lib/faraday/adapter/net_http.rb:112:in "request_with_wrapped_block"`
  
  Only Grape requests had this issue. And other requests went fine in the same app (Rails 7 and Ruby 3).
  
  The issue disappered when the Heroku Stack had been downdraded to **Heroku Stack 20**.

**Comment by dblock** [comment]
Google comes up with https://deanpcmad.com/2022/installing-older-ruby-versions-on-ubuntu-22-04/. Does this help?

**Comment by DanTaiko** [comment]
Hey Daniel (@dblock)
Thanks for your fast reply.
:-)
I didn't expect that. My idea was to inform the gem community of my workaround.

As far as I know, Heroku doesn't allow to tweak their system stack. So I downgraded the Heroku stack from Stack 22 to Stack 20 to make my app work. But the link you found gives some ideas what it could be.
Thanks a lot.

I don't mind if you close this issue.

Best regards,
Konstantin Nechepurenko

**Comment by dblock** [comment]
I think this is a legit issue, downgrading isn't really a workaround. I'd like to know what the fix is.

**Comment by DanTaiko** [comment]
Sorry, I cannot to add nothing more to it.
I had not changed the code. The heroku stack downgrading fixed that.
:'-|

**Comment by dblock** [comment]
@DanTaiko Is this an error on the server or client? If it's client, set `ca_path` to `nil` in Faraday setup. This is similar to https://github.com/slack-ruby/slack-ruby-client/issues/415. I'm going to close this unless someone can reproduce something with Grape proper.

**Comment by DanTaiko** [comment]
Hey Daniel (@dblock)
This issue has to do with a SlackRubyBotServer, not with a Slack::Web::Client. And I'm using a Ruby v.3.1.2, not a Ruby v.3.0 as it is in the link you gave.

I'm fine to close this issue.
Regards, Konstantin
