### ISSUE TITLE
Use param foo in default for bar

### ISSUE THREAD

**Issue by jamesarosen** [ruby-grape/grape#2290]
What I'd like to do:
```rb
params do
  requires :foo
  optional :bar, default: -> (other_params) { "bar from foo #{other_params[:foo]} }
end
```
or perhaps
```rb
params do
  requires :foo
  optional :bar, coerce: -> (bar_value, other_params) { "bar from foo #{other_params[:foo]} }
end
```

Unfortunately, neither `default` nor `coerce` seems to accept the other params as an argument. It may be possible to get them from `self` (which is a `ParamsScope`) within that block, but it's not obvious how.

**Comment by dblock** [comment]
Does `params[:foo]` work? If not this is a great feature request.

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2371.
