### ISSUE TITLE
Allow include_missing default value for declared() to be configurable Feature Request

### ISSUE THREAD

**Issue by jonmchan** [ruby-grape/grape#2293]
It is a little bit of clutter for every call of `declared()` to require `include_missing` to be added to it in the case where I want `include_missing` to be false. Consider the use case where we are using this to filter out PUT/PATCH calls and don't want the missing values to be added on. Every single call has to be set as:

```declared(params, include_missing: false)```

For projects that would prefer include_missing to be false by default such that we can simply call `declared(params)`, it would be nice if we can configure this in a global spot like `Grape.options.declared_include_missing_default = true/false`.

Definitely open to feedback and hearing what the maintainers of this project think about this proposed feature - thanks!

**Comment by dblock** [comment]
I think it's an antipattern to declare options globally like this. Maybe the simplest way to do it for your needs is to override [`declared`](https://github.com/ruby-grape/grape/blob/095c6e814696b4225d3f63835102f622d94fa371/lib/grape/dsl/inside_route.rb#L30)? Either a monkey patch or a helper method that calls `declared` with your favorite params?

**Comment by dblock** [comment]
Convince me that a global option is better than this?

```ruby
class API < Grape::API
      helpers do
        def declared_params
          declared(params, { include_missing: false }.merge(options))
        end
      end
      params do
        requires :x, type: Integer
        optional :y, type: Integer
      end
      get do
        declared_params
      end
end
```

In your example it would simplify `article.update(declared(params, include_missing: false))` to `article.update(declared_params)` for example.

**Comment by jonmchan** [comment]
That's a pretty elegant solution. I think I will go ahead and utilize a helper instead. Thanks for posting that example. 

Unless someone else wants to argue for this feature, I'm going to close it out. Grape's limited global config option (only 1 at the moment) is eloquent and does have the benefit of fixed behavior from application to application rather than code behaving differently based on options. This makes grape endpoints copy and pasted or imported from a gem to have consistent behavior which definitely is desirable.

**Comment by dblock** [comment]
Enjoyed this discussion, @jonmchan! Thank you.
