### ISSUE TITLE
Puma v6 raises #<NoMethodError: undefined method `bytesize' for 304:Integer> when an API returns 304

### ISSUE THREAD

**Issue by masa-iwasaki** [ruby-grape/grape#2308]
Puma throws an exception when returning 304 status without setting a body with the combination of puma v6.1.1 and grape v1.7.0. You can check the error in the following sample project.

https://github.com/masa-iwasaki/grape-304-error-with-puma-v6

The above sample code defines the following API.

```ruby
get '/demo' do
  status 304 # same result with :not_modified
end
```

The API returns the following Rack response internally.

```ruby
[304, {}, [304]]
```

Puma v6 does not expect the body of the Rack response to contain an Integer. So when Integer#bytesize is called at the following location, puma raises `#<NoMethodError: undefined method 'bytesize' for 304: Integer>` .

https://github.com/puma/puma/blob/e3d5794a7ebe47577ced4d4dfdd6a6cc969ded01/lib/puma/request.rb#L178

Note that this error does not occur in puma v5.6.5 (probably only in v6 series)

If a response code other than 304 is returned, the HTTP status code is converted to a string in the body of the Rack response as follows.

```ruby
[200, {"Content-Type"=>"application/json"}, ["200"]]
```

The difference is caused by the following conditional branch, where the return value of `get '/demo'` is set directly to the body of the Rack response in the case of 304.

https://github.com/ruby-grape/grape/blob/46695567e5758c50cb7cb297ecfcd6fc9c3d2b8f/lib/grape/middleware/formatter.rb#L28

Since `status 304` returns the status code as a number, `[304]` is returned as the body of the Rack response, as described above, and is eventually passed to puma.

To work around this error, simply return an empty string as the return value.

```ruby
get '/demo' do
  status 304
  ''
end
```

However, this workaround cannot be countered if it is not known, and a mechanism to force the body to be empty when creating a Rack response when an HTTP status code is set that does not require a body, such as 204 or 304, would be easy to understand.

**Comment by dblock** [comment]
If we just look at your example that returns `status 304`, the body is whatever is returned from the `status` method (the integer 304, then converted, etc.). Are you saying that you would always expect a `status 304` to generate an empty `nil` or blank body regardless of what the `get` returns or what `body` method sets?

I would try to make that change and see what specs break for a start. Want to give it a shot?

**Comment by masa-iwasaki** [comment]
> Are you saying that you would always expect a status 304 to generate an empty nil or blank body regardless of what the get returns or what body method sets?

Yes. This is because RFC9110 states that responses with status code 304 refer only to headers, but MDN states that browser behavior may be different if the body is incorrectly set in a persistent connection.

- https://www.rfc-editor.org/rfc/rfc9110.html#name-304-not-modified
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304#compatibility_notes

Therefore, I think it would be desirable to have a method like `return_no_conten` that does not set the body when returning 304.

**Comment by dblock** [comment]
> Therefore, I think it would be desirable to have a method like `return_no_content` that does not set the body when returning 304.

We do have that. See https://github.com/ruby-grape/grape#sending-raw-or-no-data.

> Use body false to return 204 No Content without any data or content-type.

**Comment by masa-iwasaki** [comment]
I had already tried that method, but it seems that specifying `body false` results in 204 No Content 

```ruby
  get '/demo' do
    status 304
    body false
  end
```

```console
curl -v http://localhost:3000/api/demo      
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /api/demo HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Cache-Control: no-cache
< X-Request-Id: de870b88-7283-4796-8c16-e4be78ea3ded
< X-Runtime: 0.014138
< Server-Timing: sql.active_record;dur=1.08, endpoint_run_filters.grape;dur=0.01, endpoint_run_validators.grape;dur=0.00, endpoint_render.grape;dur=0.01, endpoint_run.grape;dur=0.42
< 
* Connection #0 to host localhost left intact
*
```

But I found changing the order results in the expected behavior just now.

```ruby
  get '/demo' do
    body false
    status 304
  end
```

```console
curl -v http://localhost:3000/api/demo 
*   Trying 127.0.0.1:3000...
* Connected to localhost (127.0.0.1) port 3000 (#0)
> GET /api/demo HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.81.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 304 Not Modified
< Cache-Control: no-cache
< X-Request-Id: dfba2d74-8c65-4d19-98a8-9a91edb9fa87
< X-Runtime: 0.031178
< Server-Timing: endpoint_run_filters.grape;dur=0.01, endpoint_run_validators.grape;dur=0.00, endpoint_render.grape;dur=0.01, endpoint_run.grape;dur=0.10
< Content-Length: 0
< 
* Connection #0 to host localhost left intact
```

**Comment by dblock** [comment]
Right, the implementation sets the value to 204 and you can overwrite that.

https://github.com/ruby-grape/grape/blob/46695567e5758c50cb7cb297ecfcd6fc9c3d2b8f/lib/grape/dsl/inside_route.rb#L255

Want to help document some of the above discussion in README?

**Comment by masa-iwasaki** [comment]
That's good. I will create a PR for it.
