### ISSUE TITLE
Not yielding skipping value ?

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2329]
Hi,

[multiple_attributes_iterator](https://github.com/ericproulx/grape/blob/master/lib/grape/validations/multiple_attributes_iterator.rb) and [single_attribute_iterator](https://github.com/ericproulx/grape/blob/master/lib/grape/validations/single_attribute_iterator.rb) are yielding attribute that are eventually skip [here](https://github.com/ericproulx/grape/blob/96e2faf1cb6165eab50209fe045f15784b211d59/lib/grape/validations/validators/multiple_params_base.rb#L12) and [here](https://github.com/ericproulx/grape/blob/96e2faf1cb6165eab50209fe045f15784b211d59/lib/grape/validations/validators/base.rb#L50). Does it make sense to just not yield them and forget the `next if skip_value` ? We would have 1 iteration saved per skip

**Comment by dblock** [comment]
Probably, but that must exist for a reason. I would change it and see what spec break.
