### ISSUE TITLE
"is empty" check error in array inside an optional array of objects

### ISSUE THREAD

**Issue by JavierScars** [ruby-grape/grape#2344]
Hey guys I'm curious if this is a bug or the intended behavior... I have these params validators 

```
optional(:product_ids, type: Array[String])
optional(:all_products, type: Boolean)
optional(:export_list, type: Array) do
  requires(:locale, type: String)
  requires(:product_ids, type: Array[String])
end
at_least_one_of(:export_list, :all_products, :product_ids)
```

If I send a request using this body
```
{
    "email": "test@example.com",
    "export_list": [
        {
            "locale": "en-US",
            "product_ids": []
        },
        {
            "locale": "es-VE",
            "product_ids": []
        }
    ],
    "all_products": true
}
```

In theory, it should work, right? I'm sending at least one of the required parameters and I'm sending the export_list param with the required properties... But I get 

```
[
    "export_list[0][product_ids] is empty",
    "export_list[1][product_ids] is empty"
]
```

**Comment by dblock** [comment]
You have `requires(:product_ids, type: Array[String])` and supplying an empty array, so it's tripping the empty array validator. Does adding `allow_blank: true` solve this? `requires :product_ids, type: Array[String], allow_blank: true`

**Comment by JavierScars** [comment]
Yup, adding allow_blank: true solved the issue. Thanks!
And sorry for the late response!
