### ISSUE TITLE
Parameter renaming doesn't work for hash inside given block.

### ISSUE THREAD

**Issue by seriousdev-gh** [ruby-grape/grape#2347]
Hello.
Parameter renaming doesn't work if there is a hash inside given.

Params:
```
          requires :a, type: Hash do
            optional :c, type: String
            given :c do
              requires :b, type: Hash do
                requires :input_field, as: :output_field
              end
            end
          end
```

Input:
```
{ a: { b: { input_field: 'value' }, c: 'value2' } }
```

After running `declared(params, evaluate_given: true)`:

Expected:
```
{ a: { b: { output_field: 'value' }, c: 'value2' } }
```
Actual:
Parameter input_field is not renamed to output_field.
```
{ a: { b: { input_field: 'value' }, c: 'value2' } }
```

Info: grape version 1.7.1, ruby 3.0.2

**Comment by dblock** [comment]
Try turning this into a spec, let's see that it's still the case in the next 1.8?

**Comment by seriousdev-gh** [comment]
Added spec. Still the case in the latest main branch.

**Comment by dblock** [comment]
This was fixed in https://github.com/ruby-grape/grape/pull/2469, please check it out!
