### ISSUE TITLE
Grape v(1.7.1) isn't compatible with ruby v.3.2.2

### ISSUE THREAD

**Issue by MuhammadRaza29** [ruby-grape/grape#2348]
I have updated my ruby from` 2.7.6` to `3.2.2` Now, Grape isn't working fine with ruby v3.2.2.

I'm using fail `Grape::Exceptions::Validation, params: ["Sample Param"]`. Now, grape is returning the following errors.

`*** ArgumentError Exception: wrong number of arguments (given 1, expected 0; required keyword: params)`.

https://github.com/ruby-grape/grape/blob/master/lib/grape/exceptions/validation.rb is accepting keyword argument but keyword argument is deprecated in ruby v3. 

See: https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/

**Comment by dblock** [comment]
Care to add ruby 3.2.2 to CI? Let's see if that fails too.

**Comment by MuhammadRaza29** [comment]
It's still failing on CircleCi.

**Comment by dblock** [comment]
We don't use CircleCI. Can you please make a PR into this repo so we can see the errors?

**Comment by MuhammadRazaAslam** [comment]
Sorry, there was an issue in my application code. There is no issue in Grape gem.
