### ISSUE TITLE
X-Cascade header Rack 3 issue

### ISSUE THREAD

**Issue by schinery** [ruby-grape/grape#2354]
The `X-Cascade` header in Rack 3 applications appears to need to be lower case, and so it currently doesn't work as expected in Grape apps using Rack 3 using `cascade: true`.

The following spec, which passes in Rack 2, fails as [the default response](https://github.com/ruby-grape/grape/blob/master/lib/grape/router.rb#L140) is returned from Grape instead.

```ruby
it "raises ActionController::RoutingError" do
  expect { get "/api/foo" }.to raise_error(ActionController::RoutingError)
end
```

Manually updating my local Grape gem to use `x-cascade` results in the spec passing again.

**Comment by schinery** [comment]
Related to https://github.com/ruby-grape/grape/issues/2254

**Comment by schinery** [comment]
This is what they are doing for [Sidekiq Web](https://github.com/sidekiq/sidekiq/blob/main/lib/sidekiq/web.rb#L37):

```ruby
    if Gem::Version.new(Rack::RELEASE) < Gem::Version.new("3")
      CONTENT_LANGUAGE = "Content-Language"
      CONTENT_SECURITY_POLICY = "Content-Security-Policy"
      LOCATION = "Location"
      X_CASCADE = "X-Cascade"
    else
      CONTENT_LANGUAGE = "content-language"
      CONTENT_SECURITY_POLICY = "content-security-policy"
      LOCATION = "location"
      X_CASCADE = "x-cascade"
    end
```

Would something similar in [Grape Headers](https://github.com/ruby-grape/grape/blob/master/lib/grape/http/headers.rb) work?

**Comment by dblock** [comment]
It would probably work. Start by writing a Rails 6 and 7 spec?

**Comment by schinery** [comment]
Another option could be to make the `X-Cascade` and `Content-Type` (assuming this should also be changed) to lowercase, as these should work fine in Rack < 3 apps.

> Since HTTP/2 requires it and HTTP/1 works fine with it

https://github.com/rack/rack/issues/1592#issuecomment-584459820

**Comment by schinery** [comment]
@dblock I've thrown something together for both approaches, please let me know your thoughts and whether either of these is going in the right direction:

* Detect Rack version: https://github.com/ruby-grape/grape/pull/2355
* Use lowercase headers as default: https://github.com/ruby-grape/grape/pull/2356

**Comment by dblock** [comment]
Thanks. Let's dig up why that was changed in Rack before deciding which way to go?

**Comment by dblock** [comment]
Closed via https://github.com/ruby-grape/grape/pull/2355.
