### ISSUE TITLE
Error on additional parameters?

### ISSUE THREAD

**Issue by timjnh** [ruby-grape/grape#2358]
Are there any options to trigger error responses if extra parameters are provided?  I'd like to get errors by default if a caller provides fields beyond my specification.  I understand that I can strip them with `declared` but I want to tell people when they're calling my API incorrectly and I'd prefer not to have to write boilerplate to compare `params` and `declared(params)` for every route.

To be clear, I'm looking for this configuration:

```
params do
  requires :user, type: Hash do
    requires :name, type: String
  end
end
```

to return a 400 if I provide the following JSON:

```
{ "user": { "name": "me", "other_field": "bleh" } }
```

**Comment by dblock** [comment]
This is a dup of https://github.com/ruby-grape/grape/issues/810, so I am going to close it, _but_ this is a great feature! Would love to see someone contribute a solution for it. There are some ideas in that issue about how this could be implemented.
