### ISSUE TITLE
Reopen the issue with Rails app streaming (2367)

### ISSUE THREAD

**Issue by datpmt** [ruby-grape/grape#2369]
I kindly request to reopen the aforementioned GitHub issue so that I can provide additional comments and insights. By doing so, I believe we can assist others who may encounter similar problems in the future.

I am reaching out to discuss a recent discovery I made regarding my Rails application's streaming functionality. After some investigation, I found that the issue lies not with Rails itself, but rather with an inconsistent Rack version, as highlighted in the following GitHub issue: https://github.com/rails/rails/issues/38780#issuecomment-601930546.

**Comment by dblock** [comment]
You can comment on closed issues. If you believe this is a bug in grape, please add comments to that issue explaining why, and we'll reopen it.
