### ISSUE TITLE
endpoint method_missing vs override inspect

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2398]
#2236 has added a `method_missing` to override the NoMethodError message since it was huge inside any endpoints. I [found](https://ivoanjo.me/blog/2021/11/01/nomethoderror-ruby-cost/) that it's been [fixed](https://bugs.ruby-lang.org/issues/18285) in ruby 3.3 and the [solution](https://github.com/ruby/ruby/pull/6950) was to not use `inspect` on `undefined method`. I think that instead of using a `method_missing` strategy we could simply override endpoint's `inspect` method like this:

```ruby
def inspect
  "#{self.class} in `#{route.origin}' endpoint"
end
```

and we would achieve the same thing.
Any thoughts ?

Happy New Year :)

**Comment by dblock** [comment]
This is some advanced ruby-fu, so ... I don't know? :)

**Comment by ericproulx** [comment]
> This is some advanced ruby-fu, so ... I don't know? :)

IMO, I would just override the `inspect`. It's faster than passing by `method_missing` which is notoriously known to be slow.
