### ISSUE TITLE
Present with multiple entities

### ISSUE THREAD

**Issue by adamgotterer** [ruby-grape/grape#241]
The response would be the combination of two entities. I've run into this issue with things like pagination blocks. I've had to hack around with body to get something like:

``` javascript
{
  "users": [...],
  "pagination": {
    "page": 1,
    "num_pages": 1000
  }
}
```

Would be interesting to have a "present multi" feature. Maybe something along the lines of:

``` ruby
present_multi [[ @coupons, with: Entities::Users], [ @pagination, with: Entities::Pagination, root: 'pagination' ]]
```

Would love to start a discussion and hear other peoples thoughts?

**Comment by calfzhou** [comment]
Sorry to ping on this old issue, but i have one more question about `desc.success`.

Yes, now i can place multiple `present`s to expose pagination info along with the data collection, but how can i set this to `desc.success`? It only allows one entity -_-

**Comment by dblock** [comment]
@calfzhou I don't think I understand. Can you restate it in a new thread on the Grape mailing list?

**Comment by birla22v** [comment]
I'm sorry to comment on this closed issue but I'm running into the same issue that @calfzhou had. Was there a solution discussed for it? 

Thank you!
