### ISSUE TITLE
Why do you convert PATH_INFO? Is there some RFC?

### ISSUE THREAD

**Issue by vera-akulenko** [ruby-grape/grape#2417]
https://github.com/ruby-grape/grape/blame/c6ad84a4b793a21ec8189fd5121749fb20e81f6f/lib/grape/router.rb#L13-L14

**Comment by ericproulx** [comment]
TBH, I don't know but [Rails](https://github.com/rails/journey/blob/master/lib/journey/router/utils.rb#L14) does the same and even more.

Even though, its a literal copy/paster of [journey](https://github.com/rails/journey/blob/master/lib/journey/router/utils.rb)

**Comment by vera-akulenko** [comment]
I found the answer
https://en.wikipedia.org/wiki/URI_normalization
https://datatracker.ietf.org/doc/html/rfc3986
