### ISSUE TITLE
Drop support rack ~> 1 ?

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2424]
Should we drop support to rack ~> 1 ?

Rails 6.0 which is more than 4 years old is `rack (~> 2.0, >= 2.0.8)`
Sinatra : since `2.0`, rack is `~> 2.0'.

**Comment by dblock** [comment]
What's the benefit of dropping Rack ~> 1 support? Is it EOL?

**Comment by ericproulx** [comment]
According their [Security Policy](https://github.com/rack/rack/security#supported-versions), it's not.
