### ISSUE TITLE
Replace Appraisals by eval_gemfile ?

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2428]
Most gemfiles are sharing the same structure/gems and when it's time to update dependencies, we have to update all the them. Recently, I came across Bundler's [DSL](https://apidock.com/ruby/v2_6_3/Bundler/Dsl/eval_gemfile) where you can call `eval_gemfile` in it. 

For instance `gemfiles/rack_3_0.gemfile` could by simplify as

```ruby
# frozen_string_literal: true

eval_gemfile '../Gemfile'

gem 'rack', '~> 3.0.0'
```

That way all specific Gemfiles could rely on the base Gemfile to fill the common structure and we could drop Appraisals

**Comment by dblock** [comment]
Interesting. Appraisals are generated by a tool from spec, so does this really help or make it more confusing when adding new ones?

**Comment by ericproulx** [comment]
Personnally, when creating a new Gemfile, I just copy/past from an existing one and changing the gem manually. Configuring Appraisals feels cumbersome.

**Comment by ericproulx** [comment]
Done #2431
