### ISSUE TITLE
Investigation memory allocations

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2440]
@dblock I've done a memory profile in our stack and somehow next release has a significant higher memory allocation.

Here's the comparison

master
```ruby
Total allocated: 64160548 bytes (353932 objects)
Total retained:  9020245 bytes (26379 objects)
```

2.0.0
```ruby
Total allocated: 45345507 bytes (205326 objects)
Total retained:  6403149 bytes (14968 objects)
```

72% more on allocated
76% more retained

If you don't mind, I would like to investigate before releasing it to find the culprit.

Thanks

**Comment by dblock** [comment]
> If you don't mind, I would like to investigate before releasing it to find the culprit.

Absolutely. Bisect it?
