### ISSUE TITLE
Dropping builder as dependency ?

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2443]
[builder](https://github.com/jimweirich/builder) is only used for generating xml. Should we keep it as a dependency ? We're using [to_xml](https://github.com/rails/rails/blob/v7.1.3.3/activesupport/lib/active_support/core_ext/hash/conversions.rb) and active_support takes care to require builder when needed and will tell users if its not found.

For those who doesn't format :xml, `builder` is just an overhead.

**Comment by dblock** [comment]
I don't see why not.
