### ISSUE TITLE
Routing priority issue in Grape v2.1.0 when using with rails

### ISSUE THREAD

**Issue by eiskrenkov** [ruby-grape/grape#2452]
Hello, everyone! When upgrading to grape v2.1.0 we've encountered an issue with routing. I created a sample rails new repo for demo purposes - https://github.com/eiskrenkov/grape-routing-issue-demo

## Issue

I'm mounting grape API in rails routes at the top of the file

```ruby
Rails.application.routes.draw do
  mount Twitter::Api => '/'

  get "up" => "rails/health#show", as: :rails_health_check
end
```

When i'm doing GET `http://localhost:3000/up` request in grape v2.0.0 it returns response correctly, but in grape v2.1.1 i'm getting 404 error. It seems like something was changed in route prioritising, if nothing matches grape's routes it doesn't continue the journey

## Steps to reproduce

1. `(export SHOULD_WORK=true; bundle; bundle exec rails s)`

will use grape v2.0.0 and will respond to `http://localhost:3000/up` correctly

2. `(export SHOULD_WORK=false; bundle; bundle exec rails s)`

will use grape v2.1.0 and respond with 404

**Comment by dblock** [comment]
Looks like a regression. Try porting this into a spec in this repo without rails?

**Comment by ericproulx** [comment]
I do confirm, this test in our stack is passing in 2.0.0 but not in 2.1.0. There's is something with the `/` it works when mounting to `/api`.


```ruby
context 'rails mounted' do
    let(:app) do
      require 'rails'
      require 'action_controller/railtie'

      api = Class.new(Grape::API) do
        get('/test_grape'){ 'rails mounted' }
      end

      Class.new(Rails::Application) do
        config.eager_load = true
        config.load_defaults 7.1
        config.api_only = true
        config.consider_all_requests_local = true
        config.hosts << 'example.org'

        routes.append do
          mount api => "/"

          get 'up', to: ->(_env) do
            ['200', {}, ['hello world']]
          end

        end
      end
    end

    before { app.initialize! }

    it 'responds' do
      get '/test_grape'
      expect(last_response).to be_successful
      expect(last_response.body).to eq('rails mounted')
      get '/up'
      expect(last_response).to be_successful
      expect(last_response.body).to eq('hello world')
    end
  end
```

**Comment by SageOfTixPaths** [comment]
Same problem confirmed. I'm moving the `mount` definition for my Grape routes to the bottom of the `routes.rb` file as a temporary fix

**Comment by dblock** [comment]
Can someone bisect this to a change please?

**Comment by eiskrenkov** [comment]
@dblock I just did, the test provided by @ericproulx starts failing at `3ae7b7a720911a11a933b1788fc82764fbeaf52c`, after [this pr](https://github.com/ruby-grape/grape/pull/2435) got merged

**Comment by ericproulx** [comment]
I found something related to the X-Cascade. I'm still digging

**Comment by ericproulx** [comment]
@eiskrenkov are you using rack >= 3 ?

**Comment by eiskrenkov** [comment]
@ericproulx yes, it's `3.1.3` in both [my demo repo](https://github.com/eiskrenkov/grape-routing-issue-demo/blob/8e42c288cc36c48e51298a23f57649ce0df082e5/Gemfile.lock#L186) and grape's `Gemfile.lock` on my machine where i did bisect

**Comment by eiskrenkov** [comment]
Thank you so much for your work guys @dblock @ericproulx <3 Will try the new version once it's out

**Comment by dblock** [comment]
@eiskrenkov please do try HEAD, `github: 'ruby-grape/grape'` in Gemfile, appreciate if you could confirm the fix works.

**Comment by eiskrenkov** [comment]
@dblock sure thing! Just tried it in my project, it helped! Routes that are defined under grape mounting are reachable now. Thank you so much for such a quick fix again!

**Comment by ericproulx** [comment]
@dblock Until now, I couldn't wrap my head around this bug because obviously we had a test for cascading. While looking at the `caller` when calling the default response, I figured that `rack-test` [processes](https://github.com/rack/rack-test/blob/35b73103987828aa228824a6521453a146adff88/lib/rack/test.rb#L362) the request with a `Rack::MockResponse` which will `lowercase` the [headers](https://github.com/rack/rack/blob/800e53fbe15b3424b7a8946b067bf6f2e648d5a8/lib/rack/response.rb#L61) through `Rack::Response` by design. So, even though we were returning `X-Cascade`, the `last_response.headers` would have `x-cascade`.

Now, when running within a rails app, the `default-response` is managed by [Rails's routing](https://github.com/rails/rails/blob/19eebf6d33dd15a0172e3ed2481bec57a89a2404/actionpack/lib/action_dispatch/routing/mapper.rb#L48) which will look for `x-cascade` with Rack 3 instead of `X-Cascade`.

**Comment by ericproulx** [comment]
A test like this one would have catch it
```ruby
context 'cascade within another app' do
  subject { last_response.headers }

  let(:api) do
    Class.new(Grape::API) do
      get('/test'){ return_no_content }
    end
  end

  let(:app) do
    test_api = api
    Rack::Builder.app do
      use Rack::Lint
      run test_api.new
    end
  end

  before { get '/' }

  it { is_expected.to include('x-cascade') }
end
```
`Rack::Lint` would have raised
```ruby
Rack::Lint::LintError:
  uppercase character in header name: X-Cascade
```
