### ISSUE TITLE
Error when rescue Grape::Exceptions::ValidationErrors in json format with backtrance and original_exception

### ISSUE THREAD

**Issue by ericproulx** [ruby-grape/grape#2472]
Following #2471, I found that this case is raising an error.

```ruby
describe 'rescue Grape::Exceptions::ValidationErrors in json format with backtrace and original_exception' do
  let(:app) do
    Class.new(Grape::API) do
      format :json

      rescue_from Grape::Exceptions::ValidationErrors, backtrace: true, original_exception: true do |e|
        error!(e, 418, {}, e.backtrace, e)
      end

      params do
        requires :beer
      end

      get '/' do
      end
    end
  end

  before { get '/' }

  context 'with json response type format' do
    subject { last_response.status }

    it { is_expected.to eq(418) }
  end
end
```

Our [README](https://github.com/ruby-grape/grape?tab=readme-ov-file#validation-errors) shows the same kind of example but without original_exception and backtrace.

Nonetheless, It works for [XML](https://github.com/ruby-grape/grape/blob/56719693012269b0132d09e5e8fd41a906e38a6d/lib/grape/error_formatter/xml.rb#L12) and [TXT](https://github.com/ruby-grape/grape/blob/56719693012269b0132d09e5e8fd41a906e38a6d/lib/grape/error_formatter/txt.rb#L12) because of the simple ternary condition while [JSON](https://github.com/ruby-grape/grape/blob/56719693012269b0132d09e5e8fd41a906e38a6d/lib/grape/error_formatter/json.rb#L21) is doing something different when `Grape::Exceptions::ValidationErrors`

If we want to add `original_exception` and `backtrace` I think we'll need to enhance Grape::Exceptions::ValidationErrors with a new function to include its when dumping JSON.

**Comment by ericproulx** [comment]
@numbata if you want to take a look

**Comment by ericproulx** [comment]
Unfortunately, since `Grape::Exceptions::ValidationErrors` generates an `array` when formatted in JSON, we won't be able to add the properties at the root level. Also, adding them to each element of the array might be to much.

**Comment by numbata** [comment]
Sure would be happy to take it for tomorrow, but it feels as if you are already deep into it.

**Comment by numbata** [comment]
> Unfortunately, since Grape::Exceptions::ValidationErrors generates an array when formatted in JSON, we won't be able to add the properties at the root level. Also, adding them to each element of the array might be to much.

Agreed! And what if we could just skip the backtrace and the original exception filling if the message structure is not suitable for it? Something like that:

```ruby
module Grape
  module ErrorFormatter
    module Json
      extend Base

      class << self
        def call(message, backtrace, options = {}, env = nil, original_exception = nil)
          result = wrap_message(present(message, env))

          result = merge_rescue_options(result, backtrace, options, original_exception) if result.is_a?(Hash)

          ::Grape::Json.dump(result)
        end

        private

        def wrap_message(message)
          if message.is_a?(Hash)
            message
          elsif message.is_a?(Exceptions::ValidationErrors)
            message.as_json
          else
            { error: ensure_utf8(message) }
          end
        end

        def ensure_utf8(message)
          return message unless message.respond_to? :encode

          message.encode('UTF-8', invalid: :replace, undef: :replace)
        end

        def merge_rescue_options(result, backtrace, options, original_exception)
          rescue_options = options[:rescue_options] || {}
          result = result.merge(backtrace: backtrace) if rescue_options[:backtrace] && backtrace && !backtrace.empty?
          result = result.merge(original_exception: original_exception.inspect) if rescue_options[:original_exception] && original_exception

          result
        end
```
