### ISSUE TITLE
Tag grape project with "hacktoberfest" topic

### ISSUE THREAD

**Issue by jcagarcia** [ruby-grape/grape#2503]
Hey @dblock 👋 

Could you consider to tag the Grape project with the “hacktoberfest” topic or have the “hacktoberfest-accepted” label?

https://hacktoberfest.com/participation/#maintainers

Thanks!

**Comment by dblock** [comment]
I added `hacktoberfest` to topics. We already have`hacktoberfest-accepted` from previous years!

**Comment by dblock** [comment]
We have a "you can help" label, https://github.com/ruby-grape/grape/issues?q=is%3Aopen+is%3Aissue+label%3A%22you+can+help%22.

**Comment by jcagarcia** [comment]
Awesome! Yes, that's a perfect naming as well. Thanks a lot!
