### ISSUE TITLE
<module:Twitter>': uninitialized constant Twitter::Grape (NameError) 

### ISSUE THREAD

**Issue by iritesh** [ruby-grape/grape#327]
hi i am trying to use your sample code first i installed the gem grape and then i created a directory and created a file name as grape_sample.rb with code

module Twitter
  class API < Grape::API

```
version 'v1', :using => :header, :vendor => 'twitter'
format :json

helpers do
  def current_user
    @current_user ||= User.authorize!(env)
  end

  def authenticate!
    error!('401 Unauthorized', 401) unless current_user
  end
end

resource :statuses do

  desc "Return a public timeline."
  get :public_timeline do
    Status.limit(20)
  end

  desc "Return a personal timeline."
  get :home_timeline do
    authenticate!
    current_user.statuses.limit(20)
  end

  desc "Return a status."
  params do
    requires :id, :type => Integer, :desc => "Status id."
  end
  get ':id' do
    Status.find(params[:id])
  end

  desc "Create a status."
  params do
    requires :status, :type => String, :desc => "Your status."
  end
  post do
    authenticate!
    Status.create!({
      :user => current_user,
      :text => params[:status]
    })
  end

  desc "Update a status."
  params do
    requires :id, :type => String, :desc => "Status ID."
    requires :status, :type => String, :desc => "Your status."
  end
  put ':id' do
    authenticate!
    current_user.statuses.find(params[:id]).update({
      :user => current_user,
      :text => params[:status]
    })
  end

  desc "Delete a status."
  params do
    requires :id, :type => String, :desc => "Status ID."
  end
  delete ':id' do
    authenticate!
    current_user.statuses.find(params[:id]).destroy
  end

end
```

  end
end

and config.ru with code
equire 'rubygems'

require 'rack'

require './grape_sample'

run Twitter::API

and then run command 
rackup config.ru

and getting error
home/ritesh/rails/grape_sample.rb:2:in `<module:Twitter>': uninitialized constant Twitter::Grape (NameError)
    from /home/ritesh/rails/grape_sample.rb:1:in`<top (required)>'

**Comment by funny-code** [comment]
I had the same problem.When I add require 'grape' in my rb file,I get this:

rackup config.ru
/Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/ordered_hash.rb:3:in `<top (required)>': undefined method `add_builtin_type' for Psych:Module (NoMethodError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:69:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/grape-0.10.1/lib/grape.rb:19:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from /Users/lpy/automan/test.rb:1:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/lpy/automan/config.ru:3:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `instance_eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:55:in `initialize'
	from /Users/lpy/automan/config.ru:in `new'
	from /Users/lpy/automan/config.ru:in `<main>'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `eval'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:49:in `new_from_string'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/builder.rb:40:in `parse_file'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:208:in `app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:336:in `wrapped_app'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:272:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/lib/rack/server.rb:147:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/rack-1.6.0/bin/rackup:4:in `<top (required)>'
	from /usr/bin/rackup:23:in `load'
	from /usr/bin/rackup:23:in `<main>'


config.ru:

require 'rack'
require 'rubygems'
require File.dirname(__FILE__) + '/test'
run Twitter::API

test.rb:

require 'grape'
module Twitter
  class API < Grape::API

    version 'v1', using: :header, vendor: 'twitter'
    format :json

    helpers do
      def current_user
        @current_user ||= User.authorize!(env)
      end

      def authenticate!
        error!('401 Unauthorized', 401) unless current_user
      end
    end

    resource :statuses do

      desc "Return a public timeline."
      get :public_timeline do
        Status.limit(20)
      end

      desc "Return a personal timeline."
      get :home_timeline do
        authenticate!
        current_user.statuses.limit(20)
      end

      desc "Return a status."
      params do
        requires :id, type: Integer, desc: "Status id."
      end
      route_param :id do
        get do
          Status.find(params[:id])
        end
      end

      desc "Create a status."
      params do
        requires :status, type: String, desc: "Your status."
      end
      post do
        authenticate!
        Status.create!({
          user: current_user,
          text: params[:status]
        })
      end

      desc "Update a status."
      params do
        requires :id, type: String, desc: "Status ID."
        requires :status, type: String, desc: "Your status."
      end
      put ':id' do
        authenticate!
        current_user.statuses.find(params[:id]).update({
          user: current_user,
          text: params[:status]
        })
      end

      desc "Delete a status."
      params do
        requires :id, type: String, desc: "Status ID."
      end
      delete ':id' do
        authenticate!
        current_user.statuses.find(params[:id]).destroy
      end

    end
  end
end

**Comment by dblock** [comment]
@funny-code Your problem is different. I found https://github.com/tenderlove/psych/issues/181 too. Care to open a new issue and maybe provide a repro?
