### ISSUE TITLE
Reloading not working correctly (Rails engine)

### ISSUE THREAD

**Issue by lucaspiller** [ruby-grape/grape#358]
I have grape set up within a Rails engine for better separation of concerns, however the reloading suggestion in the documentation doesn't work for me. I also have to set `ActiveSupport::Dependencies.explicitly_unloadable_constants`.

In the engine config I have this:

``` ruby
# auto reload api in development mode
initializer 'reload_api' do
  if Rails.env.development?
    ActiveSupport::Dependencies.explicitly_unloadable_constants << "API::Resources"

    ["app/resources/**/*.rb"].each do |glob|
      files = Dir["#{API::Engine.root}/#{glob}"]
      reloader = ActiveSupport::FileUpdateChecker.new(files) do
        Rails.logger.info ">> Reloading API"
        Rails.application.reload_routes!
      end
      ActionDispatch::Callbacks.to_prepare do
        reloader.execute_if_updated
      end
    end
  end
end
```

I have no idea why this works, but heh. Might be worth adding this to the readme or wiki :)

**Comment by AndrewRayCode** [comment]
I'm having the same problem in Rails 5. I have this in an initializer:

```ruby
# See https://github.com/ruby-grape/grape#reloading-api-changes-in-development
if Rails.env.development? || Rails.env.test?
  ActiveSupport::Dependencies.explicitly_unloadable_constants << 'MyEngine::API'

  api_files = Dir[MyEngine::Engine.root.join('lib', '**', '*.rb')]

  api_reloader = ActiveSupport::FileUpdateChecker.new(api_files) do
    Rails.application.reload_routes!
  end

  ActiveSupport::Reloader.to_prepare do
    api_reloader.execute_if_updated
  end
end
```

And in my engines routes.rb file I have, fairly vanilla:
```
MyEngine::Engine.routes.draw do
  mount MyEngine::API => 'api'
end
```

When I first load the app the grape api works fine and the API result is returned. If i change smoething in api.rb it appears to auto-reload fine.

However, when I visit the _main_ application's routes, then it errors with:

> LoadError (Unable to autoload constant MyEngine::API, expected /app/my_engine/my_api/lib/my_engine/api.rb to define it):

The weird thing is that file does exit, and does correctly autoload the first time. After visiting the main app's route, the nested Grape API no longer works either.
