### ISSUE TITLE
Nested groups/mounts not working as expected

### ISSUE THREAD

**Issue by Neil-Aframe** [ruby-grape/grape#369]
My API has some resources addressable in multiple ways. I was hoping to factor this DRY-style by having two groups with before blocks that resolve params to the internal object, and then mount the same resource management code for viewing/updating etc.

I am blocked on that approach - it seems to be that the most obvious nested mounting approach does not work. The paths in the inner mount are apparently not being registered with rack, and I get a 404 from the rack server (the Grape service is not even getting called). I cannot find any examples or documentation in Grape that would point me at an alternative approach or missing syntax.

Example code that demonstrates my problem, stripped down to a minimal version here: https://gist.github.com/Neil-Aframe/5161270

**Comment by ekampp** [comment]
I just ran into this problem today. Some of the `instance_eval` solutions solved it for me, but it seems like a hack, and something that grape should be able to handle without having to loop around the regular mounting.

**Comment by dblock** [comment]
@ekampp Add your details?

**Comment by ekampp** [comment]
@dblock updated my comment above to include my code.
