### ISSUE TITLE
Intermittent NoMethodError formatter_for errors

### ISSUE THREAD

**Issue by ttsentsiper** [ruby-grape/grape#382]
The setup:
Grape mounted in rails
Part of an attempt to migrate a monolithic app to a service orientated architecture
I am forced to invoke the grape api routes in the rails request cycle (to pretend they are actually separate apps but since everything  is deployed on one server its a lot easier to just invoke grape via the rack interface and mock it like a request).

I am seeing alot of these types of erros, but the are intermittent and I am unable to reproduce them in a dev environment 

NoMethodError: undefined method `formatter_for' for Grape::Formatter::Base:Module

The specific line that we seem to fail on is:

  formatter = Grape::Formatter::Base.formatter_for env['api.format'], options

in lib/grape/middleware/formatter.rb (line 26)

Any insight into this is appreciated.

**Comment by wagner** [comment]
Just got the same error four times after a hot deploy with Puma on a busy environment.

**Comment by jf** [comment]
hi @wagner , what Ruby / version are you using out of curiosity?

**Comment by tony612** [comment]
👍  I just got the same bug :(

**Comment by dblock** [comment]
Was fixed in https://github.com/tony612/grape/commit/66683d9ada1e7d8f84f800220548e980b24d77ce
