### ISSUE TITLE
before_filter

### ISSUE THREAD

**Issue by leondu** [ruby-grape/grape#39]
does Grape provide a mechanism like before_filter in rails controller?

say:

``` ruby
resources :missions do
  before_filter :authenticate!, :only => [:post]

  post do
    create mission here...
  end

  get do
    return all missions here...
  end
end
```

**Comment by blakeperdue** [comment]
@dblock Can you provide an example? @rubencodes @letronje @leondu Did you ever figure this out?

**Comment by tam-vo** [comment]
I'd like to set locale for all actions, how can I do that with all API? I tried with BaseAPI, and define like this:
```
module V1
  class BaseAPI < Grape::API
    before do
      I18n.locale = env['rack.session'][:lang]
    end
  end
end
```
then others will be extended from this class, but above snippet is never run

**Comment by dblock** [comment]
@tam-vo It should. Try this in the actual API class, I imagine that will work. Then try again in the base class, if it doesn't work open a new bug please (with a test would be nice).

**Comment by birbird** [comment]
I wrote two classes for auth and none-auth. But it does not work, please have a look what's wrong with it.
The root Class:
```ruby
class API < Grape::API
  prefix 'api'
  format :json

  rescue_from :all

  mount AuthLessAPI
  mount AuthRequiredAPI
end
```
The auth required class
```ruby
class AuthRequiredAPI < Grape::API

  before do
    error!("401 Unauthorized, 401") unless authenticated
  end

  mount UserAPI
  mount ...
end
```
The auth less class
```ruby
class AuthLessAPI < Grape::API
  ... some api ...
end
```

**Comment by dblock** [comment]
@birbird You'll have to provide a lot more detail on "it doesn't work". I suggest opening a new issue and making code that clearly demonstrates the problem.

**Comment by PranowTest** [comment]
is there any way to scope the filter like before do till some extent, not for all the post/get requests?

**Comment by dblock** [comment]
Yes, see https://github.com/ruby-grape/grape#before-and-after.

**Comment by synth** [comment]
If anyone else comes here, I was having trouble getting callbacks to work in a base grape class that mounted others. The solution for me was to make sure the before/after callbacks are called before the mounting of the other classes are called. 

Here's ours:
````ruby
module Api
  module V2
    class Base < Grape::API
      extend Api::V2::Documentation
      extend Api::V2::Authorization
      include ApiHelper

      after do # must be called before the mount calls below!
        track_request
      end

      mount Api::V2::Endpoints::Auth
      mount Api::V2::Endpoints::Users
    end
  end
end
````
