### ISSUE TITLE
Add support for ActiveModel ActionController::Parameters (ActiveModel::ForbiddenAttributesError with active_model 4)

### ISSUE THREAD

**Issue by Maxim-Filimonov** [ruby-grape/grape#404]
I'm having issue with grape mounted inside rails 4 application. Whenever I try to use a model backed by activerecord with grape I get ActiveModel::ForbiddenAttributesError. I found a workaround which couples grape to Rails ActionController:

``` ruby
safe_params = ActionController::Parameters.new(params).permit(:registration => [:venue_name, :username, :email, :phone ])
Registration.create(safe_params[:registration])
```

Am I doing something wrong or it requires PR to fix?

**Comment by shaqq** [comment]
@dm1try @Maxim-Filimonov @dblock 

Could we re-open this issue? It feels a little hacky to "fix" this by adding hashie-rails. We're also seeing this issue in Napa, so it's not quite just Rails thing (probably ActiveModel or AR).

Also, anyone know what version of Grape this issue started popping up?

**Comment by Maxim-Filimonov** [comment]
@shaqq hashie-rails is not rails specific anymore. Sorry for confusion, It works [with just ActiveSupport](https://github.com/Maxim-Filimonov/hashie_rails/pull/3)
@dblock do we need to rename gem to make it clear or ?

**Comment by dblock** [comment]
I think that yes, the gem should be renamed or we're going to have confused users for a long time :) Maybe something like `hashie-protected-attributes`?

**Comment by dm1try** [comment]
@shaqq as you can see above, it's related to the interaction between `Hashie::Mash` and `ActiveModel`
1. `ActiveModel` [raises](https://github.com/rails/rails/blob/c0584ea0346062982cfe3c776c826ea1b026a8ac/activemodel/lib/active_model/attribute_assignment.rb#L10)  `ForbiddenAttributesError` if passed hash responds to `#permitted?` and return `false`
2. `Hashie::Mash` [returns `false`](https://github.com/intridea/hashie/blob/62281bca63d9a532969d1babfcf7ccdbf9a000e9/lib/hashie/mash.rb#L243) for any undefined attribute if `?` method suffix is used. (so `permitted?` => `false`)

The `hashie-rails` gem works fine, just has bad naming.
Btw, @Maxim-Filimonov is `ActiveSupport` dependency really needed? (seems just `hashie` is sufficient)

**Comment by TangMonk** [comment]
`Hashie::Mash`.`to_h` works
