### ISSUE TITLE
default_format :json not working

### ISSUE THREAD

**Issue by bobek** [ruby-grape/grape#407]
Hi,

I am playing with https://github.com/djones/grape-goliath-example . My current API class looks like:

``` ruby
class Posts < Grape::API
  version 'v1'
  format :json
  default_format :json

  resource 'user' do
    post "/create" do
      params.except('route_info')
    end
  end
end
```

The original version of example is using grape 0.2.2, where both call shown below work as expected. When updated the 0.4.1 (bundle update grape) the following call works:

```
curl -X POST -d '{"post":{"title":"David Jones","body":"this is my message"}}' http://localhost:9000/posts/create -H Content-Type:application/json
```

returning

```
{"post":{"title":"David Jones","body":"this is my message"}}
```

but when application/json is ommited

```
curl -X POST -d '{"post":{"title":"David Jones","body":"this is my message"}}' http://localhost:9000/posts/create
```

the call returns

```
{"{\"post\":{\"title\":\"David Jones\",\"body\":\"this is my message\"}}":null}
```

**Comment by csoreff** [comment]
Still behaving like this for me...format and default_format are :json yet this same exact thing is still happening without Content-Type.

```
curl --include \
     --request POST \
   --data-binary "{
    \"email\": \"test@test.com\",
    \"password\": \"test\"
}" \
'localhost:3000/api/v1/login'
```

results in:

```
#<Hashie::Mash {
    "email": "test@test.com",
    "password": "test"
}=nil>
```

**Comment by dblock** [comment]
Try to (re)write a spec like this @csoreff and PR it? Maybe with a fix?

**Comment by csoreff** [comment]
The test doesn't handle when content type isn't supplied at all, it's given as a blank string:

```
    it 'parses data in default format' do
      subject.post '/data' do
        { x: params[:x] }
      end
      post '/data', '{"x":42}', 'CONTENT_TYPE' => ''
      expect(last_response.status).to eq(201)
      expect(last_response.body).to eq('{"x":42}')
    end
```

When I remove that content type and post without it, it breaks without even making it to #read_rack_input.  

These are both false in #read_body_input so it returns here:

```
(!request.form_data? || !request.media_type)
```

**Comment by dblock** [comment]
You should reopen this as a new issue.

**Comment by dblock** [comment]
Re-reading this, POST with a default content type is not a thing for Rack, it won't parse input as you can see. However, Grape could apply `default_format` to the parser IMO, so JSON should work without a content-type I think.

**Comment by csoreff** [comment]
Grape can't apply default_format because it doesn't even make it to the point where it does so.

**Comment by dblock** [comment]
@csoreff We could make it get there, right? ;)

**Comment by csoreff** [comment]
Oh haha yea, I suppose I read that wrong.  :P
