### ISSUE TITLE
POST and PUT request params get dropped (rails 4, angularjs)

### ISSUE THREAD

**Issue by hc5duke** [ruby-grape/grape#417]
This is likely the same issue from [this google groups thread](https://groups.google.com/forum/#!topic/ruby-grape/stXaN2LlPKE). I created two small projects to demonstrate the issue:
- Rails 3: [github](https://github.com/hc5duke/grape_on_rails3), [heroku](http://grape-on-rails3.herokuapp.com/)
- Rails 4: [github](https://github.com/hc5duke/grape_on_rails4), [heroku](http://grape-on-rails4.herokuapp.com/)

![3 vs 4](https://f.cloud.github.com/assets/76383/604069/72b9da40-cce9-11e2-979d-522b2204403a.png)

Both projects are using `grape` at 948696f459dccd5a8f3ec3211b00be0b792719e0 on `master` with identical gems whenever possible. -rails3 is at v3.2.13, and -rails4 is at v4.0.0.rc1.

In both 3 and 4, jQuery requests are handled correctly, but when angular sends POST or PUT requests, the request is received by grape without any params (unless you hard-code it as part of the url), as evidenced by results fields. It is possible that the issue is angularjs - but given that the requests are nearly identical between what angularjs is sending between these two projects, it seems more likely that something in grape gem + rails 4 interaction is the cause of this bug.

**Comment by kesin** [comment]
Works fine for me!
