### ISSUE TITLE
Helper functions not available in rescue_from

### ISSUE THREAD

**Issue by skwp** [ruby-grape/grape#438]
Hi, we are trapping errors in rescue_from but unable to log them because the logger variable appears out of scope. Any ideas on how to access it? Thanks.

**Comment by jeremyhaile** [comment]
Thanks for the workaround. This is a huge pain. Please fix!

**Comment by thimios** [comment]
Would be great to fix this, also the workaround does not work for me:

class App < Grape::API
  rescue_from ActiveRecord::RecordNotFound do |e|
      env['api.endpoint'].error!( e.message, 404 )
  end
end

Gives: 

ArgumentError: uncaught throw :error

any ideas?

thanks!

**Comment by aserafin** [comment]
I'm using it like this https://github.com/aserafin/grape_logging#logging-exceptions. You can also checkout the gem itself - it provides you with basic similar to Rails logging features.

**Comment by jamesmoriarty** [comment]
@cmaitchison life saver.

**Comment by flocsy** [comment]
+1, logger is essential in the whole code, especially in rescue_from. It's a pity it wasn't solved yet after more than 2 years :(

**Comment by dblock** [comment]
@flocsy Make a PR?

**Comment by zuk** [comment]
Just for the record, `error!` is available in `rescue_from` blocks since 0.12.0. See https://github.com/ruby-grape/grape/pull/974

Other/custom helpers however still aren't.

**Comment by dblock** [comment]
This was fixed on HEAD, thanks @namusyaka.
