### ISSUE TITLE
Optional URL Parameters

### ISSUE THREAD

**Issue by psteininger** [ruby-grape/grape#446]
I am building an api mounted as an engine in a Rails app.
All my rails routes are in a scope with an optional parameter to indicate requested locale:

``` ruby
scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
...
end
```

I wanted to have the same work for my API mounted as such:

``` ruby
scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  ...
  mount Gohike::API => "/api"
end
```

This however does not pass the optional `(:locale)` down to the api as a parameter. The URLs work perfectly. So my other option was to declare an endpoint in Grape API like this (outside of the scope in `routes.rb`:

``` ruby
    get '(:locale)/catalog/:city_id', :rabl => "catalog" do
    ....
    end
```

This does work for url `/api/en/catalog/3` however does not work as an optional parameter like it does in case of the rails route `/api/catalog/3`.

Is there any way to make this work? I can't find anything in the docs.

Thanks in advance !

**Comment by kristianmandrup** [comment]
How about if I have locale as an optional query string parameter. Would that work?

`/en/api/v1/blocks` or `/en/api/v1/blocks?locale=en` ??
