### ISSUE TITLE
Presence of '.' characters in URI confuses Grape

### ISSUE THREAD

**Issue by supriyapjoshi** [ruby-grape/grape#453]
Given the following Grape API:

```
require 'grape/api'

class IndexApi < Grape::API
  content_type :html, 'text/html'
  content_type :json, 'application/json'

  default_format :json

  allow_cross_domain_request_from '*'

  get '/notes/:component_name' do
    "#{params[:component_name]}"
  end
end
```

Here are the results of GETting various URIs:
- `/notes/foo` returns `"foo"`
- `/notes/http%3A%2F%2Fwww%2Eexample` returns `"http://www"`
- `/notes/http%3A%2F%2Fwww%2Eexample.com` returns a 404 Not Found

I would expect the results to be:
- `/notes/foo` returns `"foo"`
- `/notes/http%3A%2F%2Fwww%2Eexample` returns `"http://www.example"`
- `/notes/http%3A%2F%2Fwww%2Eexample.com` returns `"http://www.example.com"`

**Comment by stephenjlevy** [comment]
The problem with using 

```
subject.format :json
subject.get '/notes/*component' do
  params[:component]
end
```

is that now you've created extra routes.  For instance, "notes/test/foo.a" is now valid, when you really only want to allow "notes/foo.a".  Is there any other way around this?

**Comment by dblock** [comment]
You can make any regex here, including something very specific. And you can use `requirements: ` to lock it down further. So in this example you would want to disallow `/` by whitelisting what is possible in the component.

**Comment by atomless** [comment]
@dblock The solution outlined above succeeds for me ONLY if there's just the one period in the path segment. The correct route is hit, however, once there's more than a single period in the path segment the param is always trimmed up to just before the second one. For example, with :`some/end/point/with/this/segment/one.two.three.etc` the correct route is hit with by using : 
```Ruby
get 'some/end/point/with/this/segment/*key' do
    params[:key]
end
```
but the param key value is always trimmed to `one.two` and attempts to make it greedier by adding a requirements regex don't help at all. Is there something else required to support multiple periods in a segment or is this a bug after all?

**Comment by dblock** [comment]
Why don't you write this a spec and I'll try to help you fix it?

**Comment by atomless** [comment]
```Ruby
require 'rubygems'
require 'rack/test'
require 'test/unit'

OUTER_APP = Rack::Builder.parse_file('config.ru').first

class TestApp < Test::Unit::TestCase
  include Rack::Test::Methods

  def app
    OUTER_APP
  end
 
  def test1
    get 'api/v1/thing/by_key/foo'
    puts "#{last_response.body}"
    assert last_response.ok?
  end

  def test2
    get '/thing/by_key/www.wizz.bang.com'
    puts "#{last_response.body}"
    assert last_response.ok?
  end
end
```
The endpoint targeted by this is simply:
```Ruby
params do
    requires :key, :type => String, desc: 'URL encoded UNIQUE key string identifier .'
end
get 'by_key/*key' do
   self.params[:key]
end
```
test1 passes and returns 'foo' and test2 is always a 404.

**Comment by dblock** [comment]
I tried it and it looks legit at the first look, complete code:

```ruby
require 'rubygems'
require 'rack/test'
require 'test/unit'
require 'grape'

class API < Grape::API
  version :v1
  prefix 'api'

  resource :thing do
    params do
        requires :key, :type => String, desc: 'URL encoded UNIQUE key string identifier .'
    end
    get 'by_key/*key', requirements: { key: /.*/ } do
       self.params[:key]
    end
  end
end

class TestApp < Test::Unit::TestCase
  include Rack::Test::Methods

  def app
    API
  end

  def test1
    get 'api/v1/thing/by_key/foo'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end

  def test11
    get 'api/v1/thing/by_key/foo.bar'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end

  def test2
    get '/thing/by_key/foo.bar.baz'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end
end
```

@atomless it would be helpful if you could turn this into a spec in Grape and PRed it.

**Comment by atomless** [comment]
@dblock sorry - when you say "looks legit" do you mean you had the same 404 error. Or it all worked fine for you? If you're getting the same error then yes I'll figure out how to make the test into a spec. Thanks!

**Comment by dblock** [comment]
I am getting the same error, so this looks like a legit bug or at least I didn't quickly find a workaround.

**Comment by dblock** [comment]
Actually scratch that. The example above is missing `/api/v1` in the test. This passes:

```ruby
require 'rubygems'
require 'rack/test'
require 'test/unit'
require 'grape'

class API < Grape::API
  version :v1
  prefix 'api'

  resource :thing do
    params do
        requires :key, :type => String, desc: 'URL encoded UNIQUE key string identifier .'
    end
    get 'by_key/:key', requirements: { key: /.*/ } do
       self.params[:key]
    end
  end
end

class TestApp < Test::Unit::TestCase
  include Rack::Test::Methods

  def app
    API
  end

  def test1
    get 'api/v1/thing/by_key/foo'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end

  def test11
    get 'api/v1/thing/by_key/foo.bar'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end

  def test2
    get '/api/v1/thing/by_key/foo.bar.baz'
#    puts "#{last_response.body}"
    assert last_response.ok?
  end
end
```

**Comment by atomless** [comment]
Aha, interesting. 

With the requirements regex included I too see these test passing.

However, the odd thing is that when the endpoint has the star like so : 
```Ruby
  get 'by_key/*key', requirements: { key: /.*/ } do
    self.params[:key]
  end
```
The key returned by `test2` is just `foo.bar` BUT when the endpoint uses the symbol like so:
```Ruby
  get 'by_key/:key', requirements: { key: /.*/ } do
    self.params[:key]
  end
```
THEN the key returned by `test2` is `foo.bar.baz` !

Another odd thing that may or may not be related - that I noticed while testing this using grape stagger auto doc ui - is that when the endpoint has `*key` then stagger constructs the query with literally `/*key` in the url path and also adds that actual key as a url query param. That is a red herring though as, even when I construct a curl request using the key in the path, with the endpoint using the star I STILL get only `foo.bar` as the response.

**Comment by dblock** [comment]
I am not sure what `/*key` is supposed to match, I think the definition of `:key` comes from `params` anyway. 

All that said I think everything works by design. Open a new issue if you don't agree.

**Comment by atomless** [comment]
@dblock - it was your comment on [Jan 3, 2014](https://github.com/ruby-grape/grape/issues/453#issuecomment-31544963) above that I thought pointed the way to using a path in the endpoint with a star prefix? Not sure whether it all works as designed or not as I'm unsure of the difference between the two kinds of endpoints?

**Comment by dblock** [comment]
I am not sure how that matches, @namusyaka should know a lot more about this
