### ISSUE TITLE
JSON can't be decoded correctly by default if it contains chinese character 

### ISSUE THREAD

**Issue by chaixl** [ruby-grape/grape#467]
After upgrading to rails 3.2.13 or rails 4, JSON from grape can't be decoded correctly by some browers(Firefox, Safari) or JSON parse lib (e.g. JSONKit), if it contains chinese character.

I have to change 'Encoding' to UTF-8 in these browers or add "content_type :json, 'application/json ; charset = utf-8' " to API class to solve this issue.

So I think content_type should contain 'charset = utf-8' by default, right?

related changelog in rails 3.2.13 as below

> Remove surrogate unicode character encoding from ActiveSupport::JSON.encode The encoding scheme was broken for unicode characters outside the basic multilingual plane; since json is assumed to be UTF-8, and we already force the encoding to UTF-8 simply pass through the un-encoded characters.

> Brett Carter

**Comment by tomchristie** [comment]
> I have to change 'Encoding' to UTF-8 in these browers or add "content_type :json, 'application/json ; charset = utf-8' " to API class to solve this issue.

This is a browser issue, not an issue in grape.
JSON should not include a charset in the media type.

From [the `application/json` registry](http://www.iana.org/assignments/media-types/application/json):

> Note:  No "charset" parameter is defined for this registration.
> Adding one really has no effect on compliant recipients.

See also https://tools.ietf.org/html/rfc4627#section-3

**Comment by dm1try** [comment]
I agree with @tomchristie.

ATM you can set content type with encoding manually if you need "out-of-spec solution" for some reason. 

>Possible relevant note: explicitly setting content_type :json, 'application/json; charset=utf-8' seems to stop the API from accepting some json POST requests. A POST with the request headers

This issuee is already fixed.
