### ISSUE TITLE
Better behavior when coercion fails

### ISSUE THREAD

**Issue by solnic** [ruby-grape/grape#483]
Hey!

I noticed you have this:

``` ruby
def coerce_value(type, val)
  converter = Virtus::Attribute.build(:a, type)
  converter.coerce(val)

# not the prettiest but some invalid coercion can currently trigger
# errors in Virtus (see coerce_spec.rb)
rescue
  InvalidValue.new
end
```

and I started wondering in which cases coercions trigger errors in virtus? I'd like to check it out with latest 1.0.0 pre-release of virtus and hopefully fix it (if the problem still exists).

There's also a new interface for checking if a coercion was successful via `Attribute#value_coerced?(val)` - it might be useful for you.

**Comment by dnesteryuk** [comment]
@dblock I guess this one might be closed, Virtus isn't used anymore.

**Comment by dblock** [comment]
Yes. Also #1952 should hopefully give you the ability to do so :) Thanks for your help!
