### ISSUE TITLE
validation fails when params block has a type coercion

### ISSUE THREAD

**Issue by lepfhty** [ruby-grape/grape#491]
Copied this straight from the README and put it in a minimal rackup file:

``` ruby
require 'grape'

class API < Grape::API
  resource :status do
    desc "Return a status."
    params do
      requires :id, type: String
    end
    route_param :id do
      get do
        params[:id]
      end
    end
  end
end

run API
```

A simple GET request fails validation

``` bash
$ curl -XGET http://localhost:9292/status/1
id is invalid
```

Interestingly, if I remove `type: String` from the `requires` declaration, everything works as expected.

**Comment by menisy** [comment]
I'm getting this bug while using a custom type coercion with custom validation, it seems that the coercion is being called (shown by debugging breakpoints), however, for some odd reason the coerced value (an array of strings) is not being passed to the validator, but rather the string param itself.

Using **grape 1.2.4** and **virtus 1.0.5**.

This works:
```ruby
            optional :cat_ids,
                     type: Array,
                     coerce_with: -> (val) { Concerns::Types::IntegersAndNullArray.parse(val) },
                     integers_with_null: true,
                     documentation: { param_type: 'query', collectionFormat: 'csv', values: ['null,1,2,...'] }
```

This doesn't work:
```ruby
            optional :cat_ids,
                     type: Array[String], # or Array[Integer]
                     coerce_with: -> (val) { Concerns::Types::IntegersAndNullArray.parse(val) },
                     integers_with_null: true,
                     documentation: { param_type: 'query', collectionFormat: 'csv', values: ['null,1,2,...'] }
```

was anyone able to get around this somehow?
