### ISSUE TITLE
requester ip

### ISSUE THREAD

**Issue by AlyBadawy** [ruby-grape/grape#528]
I need to get the remote ip for the requester and return it back in the response. I could do that on regular controllers using

```
request.remote_ip
```

however, in grape calls, the 'request' is not a defined variable.

how can I get access to the remote ip on grape?

**Comment by pboling** [comment]
`undefined method `remote_ip' for #<Grape::Request:0x0000011504a090>`

remote_ip is not a part of the Grape::Request.  Not sure if there is another way to access it there.

`env["REMOTE_ADDR"]` appears to work.

**Comment by albertordz** [comment]
hey @dblock is there any official documentations where @teamon took the env["REMOTE_ADDR"] and env["REMOTE_HOST"] from? I dont seem to find it anywhere in the code

**Comment by dblock** [comment]
I am going to guess it's somewhere from Rack.

**Comment by tibbon** [comment]
I'm always getting 127.0.0.1 from `env["REMOTE_ADDR"]`. Maybe the way my load balancer is setup?

**Comment by teamon** [comment]
@tibbon most probably you're right, https://easyengine.io/tutorials/nginx/forwarding-visitors-real-ip/ might help
