### ISSUE TITLE
Routing aliases, its possible?

### ISSUE THREAD

**Issue by guilherme** [ruby-grape/grape#551]
There's some way to do a aliasing of a route? For e.g. 

I have a endpoint A : /api/A, and a endpoint B: /api/B. For a given moment they share behaviors that are common but differ on details, so its justifiable to have the two endpoints. Suppose that after a moment the behavior changed to be equal, instead of modifying where the calls are made to B to A, i want to make an alias to modify this later.
There's a way to do this endpoint alias without copy/paste the code? Like:

``` ruby
 get '/api/A', :aliases => ['/api/B'] do
 end
```

**Comment by brlo** [comment]
If you use:

```ruby
[ '/api/A', '/api/B' ].each do |path|
  get path do
  end
end
```

It will broke `(declared(params, include_missing: false)`.
For path `/api/A` all is fine, but for `/api/B` you'll get empty Mash.
