### ISSUE TITLE
Nested Resources

### ISSUE THREAD

**Issue by daddz** [ruby-grape/grape#57]
Is there a way to have nested resources to get routes like this:

```
 foo id        bar id
      |        |
/foo/:id/bars/:id
```

Something along those lines:

``` ruby
resource :foo do
  resource :bar do
    get '/:id' do
       #...this obviously misses the foo id
```

That would make it easy to map (model) relations to the API.

**Comment by zotherstupidguy** [comment]
@mbleigh could you point out where exactly the code that supports this type of nesting?
