### ISSUE TITLE
Swagger Breaks On Endpoint Param Called "body"

### ISSUE THREAD

**Issue by xevix** [ruby-grape/grape#579]
Grape: 0.6.1
Grape-Rabl: 0.2.2
Grape-Swagger: 0.7.2

Swagger-UI: From git, https://github.com/wordnik/swagger-ui/commit/0c0ffc569f93a7728a83f91a56af7701e1cb8977, last commit Feb. 3 2014

Suppose you have an API endpoint that looks like this:

``` ruby
class Messages < Grape::API

  resources :messages do

    desc "Some method"
    params do
      requires :param_a, type: Integer, desc: "Some parameter that gets ignored"
      requires :body, type: String, desc: "Parameter named 'body' that breaks Swagger"
    end
    post "/test" do
      # The below doesn't matter, since it never gets here
      @message = Message.last
      @message
    end
  end
end
```

This will give an error similar to the one below:

``` javascript
{
  "error": "expected true at line 1, column 2 [parse.c:147]"
}
```

I _think_ that it's `oj` dying because Swagger is sending the body parameter's value as a raw string instead of JSON. Note that `:param_a` will be completely ignored, even if you fill out both. 

You would expect it to send something like this:

``` javascript
{
  "param_a": 1234,
  "body": "testing"
}
```

But instead it sends something like this (taken from Chrome inspector)

```
testing
```

I tried changing the param name to `bodys` and this worked fine. Also, sending via curl from the console works fine:

```
curl -vvv -X POST -H "Content-Type: application/json" -d '{"param_a": 1234, "body": "testing"}' http://localhost:3000/api/users/test.json
```

I'm not sure if this is a Grape or Swagger issue, so I'm reporting here first, but I appreciate any pointers. Thanks!

**Comment by dylanninin** [comment]
Just a mark since this issue sucks a lot.
