### ISSUE TITLE
Allow Setting Custom Error Message with :requires 

### ISSUE THREAD

**Issue by jackdesert** [ruby-grape/grape#621]
Would you mind allowing a custom error message to be set through the 'requires' method? For example, I would like to set a custom error message like this:

```
params do
    requires :name, regexp: /^[a-z]+$/, message: "Name may only contain letters a-z"
end
```

But this doesn't work. And creating a custom validator just to set a custom error message seems like a lot of overhead.

**Comment by MSadir** [comment]
Hi, has anyone taken this on?

**Comment by dm1try** [comment]
@MSadir pretty sure, nobody

If anyone will try to implement this
do not forget about DSL for multiple validations on the single param
```ruby
params do
    optional :name, values:      { value: 1..10, message: 'not in range from 1 to 10' }
                    allow_blank: { value: false, message: 'must present' }
end

**Comment by dnesteryuk** [comment]
@dblock This one is [already implemented](https://github.com/ruby-grape/grape#custom-validation-messages).
