### ISSUE TITLE
error!('Unauthorized', 401) does not work as expected

### ISSUE THREAD

**Issue by born4new** [ruby-grape/grape#628]
I'm using grape in a rails app (4.0.4).

It is the only code with which I have an issue: the others are working just fine.

Basically when I try to access to the ping action below, it does a redirect 302 to the home api and in my tests the status code is 302 instead of 401...It seems really strange to me, but is it supposed to be that way?

``` ruby
      desc "Returns pong if logged in correctly."
      params do
        requires :token, type: String, desc: "Access token."
      end
      get :ping do
        error!('Unauthorized', 401)
      end
```

Thanks in advance for your replies!

**Comment by xiaohui-zhangxh** [comment]
Yes, @rolandjitsu is right, warden captures `401` and throw :warden, to disable this feature, config warden:
```
Rails.configuration.middleware.use Warden::Manager do |config|
  config.intercept_401 = false
end
```
