### ISSUE TITLE
rescue_from must precede mount

### ISSUE THREAD

**Issue by p-originate** [ruby-grape/grape#646]
Documentation does not say this, but it appears that rescue_from statements must precede mount statements in an api class, otherwise rescue_from is ignored.

**Comment by dm1try** [comment]
BTW it's not only about a `rescue_from`
`before/after` blocks and the other base stuff should precede the `mount`, otherwise they will be ignored.
One more problem with "mounted APIs"(or maybe the same).

**Comment by dblock** [comment]
Bump @p-originate, want to PR a documentation update? Maybe @dmitry?
