### ISSUE TITLE
SystemStackError in Grape/Hashie when POSTing GeoJSON file

### ISSUE THREAD

**Issue by bertspaan** [ruby-grape/grape#662]
I've been experiencing SystemStackErrors in Hashie's [mash.rb](https://github.com/intridea/hashie/blob/953edece981f12189896c41288da3bfe31c355d5/lib/hashie/mash.rb#L153), when POSTing somewhat large GeoJSON files to a Grape endpoint. I'm using Grape 0.7.0.

To replicate the bug, do the following:

1. Clone/copy files from [gist](https://gist.github.com/bertspaan/1fa4c333ae809a1c34b9),
2. open two terminals, run `rackup` in one,
3. and `./bug.sh` in the other.

The Grape/Rack terminal will output: 

    [2014-06-17 11:18:37] ERROR SystemStackError: stack level too deep
	    /Users/bert/.rvm/gems/ruby-2.1.1/gems/hashie-3.0.0/lib/hashie/mash.rb:242

**Comment by dm1try** [comment]
I tried your example on the `master` branch.
`rack` raises a range error before Hashie converts the params.
>RangeError: RangeError
	/home/dmitry/.rvm/gems/ruby-2.2.1/gems/rack-1.6.4/lib/rack/utils.rb:135:in `normalize_params'

The main problem that you didn't specify content type for your large GeoJSON.
`curl` uses  `application/x-www-form-urlencoded` type by default for the `--data` params so this GeoJSON is parsed as usual query params(whole content is one BIG KEY with a complex structure but without a value).
After adding "Content-type: application/json" header all works well.   

Anyway thanks for the reporting this issue, seems like the parsing of HTTP "key-value" pairs is interesting thing(I can't find any RFC at the moment).

I'll close, it's not related directly to `grape`.
