### ISSUE TITLE
Possible Require / Regexp validation bug introduced in e2150b5

### ISSUE THREAD

**Issue by zdennis** [ruby-grape/grape#677]
I believe a bug was introduced in commit e2150b5

The problem with this change is that if you combine a `requires` with a `:regexp` option then you will now get two validation errors, e.g.: 

        foobar is missing, foobar is invalid

An example of this would be:

      requires :foobar, type: String, regexp: /^[0-9]$/, desc: "My foobar yo"

When combined with `require` it would seem that the `regexp` validation would not check the existence of the value and add a second error message about the existence of the value.

However, when using optional params it would make more sense for the `regexp` validation to supply its own separate error message.

**Comment by dm1try** [comment]
Continue in #730
