### ISSUE TITLE
Expand parameter validation to type File

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#690]
It's unclear how to require an uploaded multipart file parameter. We could also expand this to file formats.

**Comment by dnesteryuk** [comment]
@dblock I think this [one is covered](https://github.com/ruby-grape/grape/blob/c5cd3326fcbc896e958bf521e1ed35b0b0021452/spec/grape/validations/validators/coerce_spec.rb#L361-L376). Isn't it?

**Comment by dblock** [comment]
Yup. Also if you're sure just close it @dnesteryuk, what do I know? :)
