### ISSUE TITLE
Allow multiple parameter types

### ISSUE THREAD

**Issue by dblock** [ruby-grape/grape#693]
I have the following API: `/api/v1/artworks/tagged?tag[]=`, I'd like to be able to do `/api/v1/artworks/tagged?tag=painting` as well as `/api/v1/artworks/tagged?tag[]=painting&tag[]=sculpture`. So something like this:

``` ruby
params do
  requires :tag, types: [String, Array[String]], desc: "Tag or tags."
end
```

Maybe instead I could write this:

```
params do
  optional :tag, type: String, desc: "Tag or tags."
  optional :tag, type: Array[String], desc: "Tag or tags."
  exactly_one_of :tag
end
```

That would also solve the problem of allowing a parameter like `size` to be a number (eg. 10) or a string, (eg. "all").

**Comment by viranch** [comment]
This can also be approached with making `tag` only an `Array[String]`:

```ruby
params do
  optional :tag, type: Array[String], desc: "Tag or tags."
end
get :tagged do
  p params[:tag] #=> this is always an array
end
```

This will accept both `/tagged?tag=painting` and `/tagged?tag[]=painting&tag[]=sculpture`, except that grape validator will also convert the former to an array with single element. So you can expect the value of `tag` to always be an array in your models.
