### ISSUE TITLE
Group param with a required param defaults to Array

### ISSUE THREAD

**Issue by jdp** [ruby-grape/grape#722]
I'm trying to use a required param inside of a group, like this:

``` ruby
params do
  group :a do
    requires :b
  end
end
```

As an aside, my actual use case looks more like:

``` ruby
params do
  group :a do
    requires :b
  end
  group :c do
    requires :d
  end
  exactly_one_of :a, :c
end
```

But if I send a request that should satisfy that first example, like one of these:

``` shell
$ curl "localhost:9292/case" -d "a[b]=c"
$ curl "localhost:9292/case" -d '{"a":{"b":"c"}}' -H "Content-Type: application/json"
```

I get a response saying `a` is invalid:

``` json
{"error":"a is invalid"}
```

I made [an example here](https://gist.github.com/jdp/cb76505f83dadd90609e) that reproduces the bug. I'm using grape version 0.8.0.

**Comment by jrichter1** [comment]
I'm going to give it a shot to make it raise an error if no type is specified. I'll issue a PR when done and we'll see what comes out of it.

**Comment by dnesteryuk** [comment]
The solution was implemented in the attached PR.
