### ISSUE TITLE
Extend rescue_from to take a with: parameter

### ISSUE THREAD

**Issue by mfunaro** [ruby-grape/grape#790]
It would be nice to define a module with error handling methods, then pass the error handler to the rescue_from method in the following fashion.

    module API
      module ErrorHandler
         def record_not_found
            rack_response API::Utils::ApiErrors.new({type: e.class.name, message: 'Record not found'}).to_json, 404
         end
      end
    end

Then in the GRAPE::API base class one could call rescue_from like this...

    module API
      class Root < Grape::API
        prefix 'api'
        format :json

        helpers API::ErrorHandler

        rescue_from ActiveRecord::RecordNotFound, with: :record_not_found # Use the helper method as the handler for this error
      end
    end

**Comment by florrain** [comment]
Agree too :+1:
