### ISSUE TITLE
Not support ActiveRecord lazy load

### ISSUE THREAD

**Issue by tooooolong** [ruby-grape/grape#839]
``` ruby
namespace :bzp_activities do
  after do
    @activities.update_all(read: true)
  end

  get '/', jbuilder: 'v1/users/bzp_activities' do
    @activities = BzpActivity.where(read: false)
  end
end
```

after block will execute before view rendered
because ActiveRecord is lazy load so i can never get the right result

is there any will to support lazy load
or just to write it in a eager load way

**Comment by merqlove** [comment]
@dblock Yes, it is.
But i did it right via custom formatter.
Other solutions won't help (middleware).
