### ISSUE TITLE
Access request in custom validators.

### ISSUE THREAD

**Issue by nalbeza** [ruby-grape/grape#986]
Is it possible to access request context in custom validators ?

It would be very useful, for example to check for uniqueness or use helpers such as current_user.

**Comment by dblock** [comment]
It certainly is. See https://github.com/intridea/grape/blob/master/lib/grape/validations/params_scope.rb#L8 for how it plucks various things at construction time - I think this is what you're looking for. 

Use the mailing list for questions, if the above doesn't work post some code of what you'd like to accomplish.

**Comment by suan** [comment]
@dblock Would you mind providing a more specific example of how we can get at the request from within a validator? I see that I can access the `@scope` variable from within my validator, but I don't see the params_scope containing any info about the actual request

(In my case, I'd like to get at the request path and headers)

**Comment by dblock** [comment]
Right @suan, I reopened it because I don't actually see how. I'd welcome someone solving it!

**Comment by glennpratt** [comment]
@dblock locally I've changed the signature of Validator#validate! (with backwards compatibility using arity) to:

```ruby
def validate!(params, env)
```

Is env too broad?

**Comment by glennpratt** [comment]
Oh, I see `@request` includes `env` anyway. I'll just do that instead.

**Comment by glennpratt** [comment]
So, should we replace params with request (breaking backwards compatibility) or only send request if the method arity != 1?

**Comment by glennpratt** [comment]
See #1242

**Comment by dnesteryuk** [comment]
@dblock The attached PR already [implemented this task](https://github.com/ruby-grape/grape/blob/master/spec/grape/api/custom_validations_spec.rb#L52-L59) :wink:

**Comment by dblock** [comment]
Closing! Thanks @dnesteryuk
